### ISSUE TITLE
Have issue with Mailgun configurations

### ISSUE THREAD

**Issue by jostyee** [sameersbn/docker-gitlab#1008]
sameersbn/docker-gitlab:8.14.4 my docker-compose.yml settings as below:

```
    - SMTP_ENABLED=true
    - SMTP_DOMAIN=$GITLAB_HOST
    - SMTP_HOST=smtp.mailgun.org
    - SMTP_PORT=587
    - SMTP_USER=$user
    - SMTP_PASS=$pass
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=plain
```

after `docker-compose up` there's no mail related process running, and cannot send mail successfully, sidekiq reports `Net::OpenTimeout: execution expired` error:
```
==> log/sidekiq.log <==
2016-12-12T04:14:09.782Z 501 TID-1u5770 ActionMailer::DeliveryJob JID-350ede649e3552c093e30262 INFO: fail: 30.026 sec
2016-12-12T04:14:09.782Z 501 TID-1u5770 WARN: {"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"ActionMailer::DeliveryJob","queue":"mailers","args":[{"job_class":"ActionMailer::DeliveryJob","job_id":"3cb3175c-2205-48d6-858d-4d63a63fee23","queue_name":"mailers","arguments":["DeviseMailer","reset_password_instructions","deliver_now",{"_aj_globalid":"gid://gitlab/User/14"},"pnhes2B8v1FpULhYaSEy",{"_aj_symbol_keys":[]}],"locale":"en"}],"retry":3,"jid":"350ede649e3552c093e30262","created_at":1481516019.7553616,"enqueued_at":1481516019.7554731,"error_message":"execution expired","error_class":"Net::OpenTimeout","failed_at":1481516049.7824056,"retry_count":0}
2016-12-12T04:14:09.782Z 501 TID-1u5770 WARN: Net::OpenTimeout: execution expired
2016-12-12T04:14:09.782Z 501 TID-1u5770 WARN: /usr/lib/ruby/2.3.0/net/smtp.rb:542:in `initialize'
/usr/lib/ruby/2.3.0/net/smtp.rb:542:in `open'
/usr/lib/ruby/2.3.0/net/smtp.rb:542:in `tcp_socket'
/usr/lib/ruby/2.3.0/net/smtp.rb:552:in `block in do_start'
/usr/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
/usr/lib/ruby/2.3.0/net/smtp.rb:551:in `do_start'
/usr/lib/ruby/2.3.0/net/smtp.rb:521:in `start'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/mail-2.6.4/lib/mail/network/delivery_methods/smtp.rb:113:in `deliver!'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/mail-2.6.4/lib/mail/message.rb:2149:in `do_delivery'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/mail-2.6.4/lib/mail/message.rb:237:in `block in deliver'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/actionmailer-4.2.7.1/lib/action_mailer/base.rb:543:in `block in deliver_mail'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `block in instrument'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `instrument'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/actionmailer-4.2.7.1/lib/action_mailer/base.rb:541:in `deliver_mail'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/mail-2.6.4/lib/mail/message.rb:237:in `deliver'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/actionmailer-4.2.7.1/lib/action_mailer/message_delivery.rb:85:in `deliver_now'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/actionmailer-4.2.7.1/lib/action_mailer/delivery_job.rb:10:in `perform'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.7.1/lib/active_job/execution.rb:32:in `block in perform_now'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/i18n-0.7.0/lib/i18n.rb:257:in `with_locale'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.7.1/lib/active_job/translation.rb:7:in `block (2 levels) in <module:Translation>'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:441:in `instance_exec'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:342:in `block in simple'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:497:in `block in around'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:343:in `block (2 levels) in simple'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.7.1/lib/active_job/logging.rb:23:in `block (4 levels) in <module:Logging>'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `block in instrument'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `instrument'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.7.1/lib/active_job/logging.rb:22:in `block (3 levels) in <module:Logging>'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.7.1/lib/active_job/logging.rb:43:in `block in tag_logger'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:26:in `tagged'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `tagged'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.7.1/lib/active_job/logging.rb:43:in `tag_logger'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.7.1/lib/active_job/logging.rb:19:in `block (2 levels) in <module:Logging>'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:441:in `instance_exec'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:441:in `block in make_lambda'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:342:in `block in simple'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:497:in `block in around'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_perform_callbacks'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.7.1/lib/active_job/execution.rb:31:in `perform_now'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.7.1/lib/active_job/execution.rb:21:in `execute'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activejob-4.2.7.1/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/processor.rb:155:in `execute_job'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/processor.rb:136:in `block (3 levels) in process'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/home/git/gitlab/lib/gitlab/sidekiq_middleware/request_store_middleware.rb:6:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/git/gitlab/lib/gitlab/sidekiq_middleware/memory_killer.rb:17:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/logging.rb:32:in `with_context'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/processor.rb:131:in `block (2 levels) in process'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/processor.rb:171:in `stats'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/processor.rb:130:in `block in process'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq.rb:35:in `block in <module:Sidekiq>'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/processor.rb:122:in `process'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/processor.rb:81:in `process_one'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/processor.rb:69:in `run'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/util.rb:17:in `watchdog'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/sidekiq-4.2.1/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

So can anyone point out what wrong with my configurations? Thanks in advance.

**Comment by jostyee** [comment]
our security group issue, fixed.
