### ISSUE TITLE
gitlab rake aborted

### ISSUE THREAD

**Issue by duncau1234** [sameersbn/docker-gitlab#1018]
### hi there, 
I am trying to use docker-compose file to build my own gitlab. 
when I  docker-compose up, an error occured

```
### gitlab        | Configuring gitlab::database...
gitlab        | Configuring gitlab::redis
gitlab        | Configuring gitlab::secrets...
gitlab        | Configuring gitlab::sidekiq...
gitlab        | Configuring gitlab::gitlab-workhorse...
gitlab        | Configuring gitlab::unicorn...
gitlab        | Configuring gitlab::timezone...
gitlab        | Configuring gitlab::rack_attack...
gitlab        | Configuring gitlab::ci...
gitlab        | Configuring gitlab::artifacts...
gitlab        | Configuring gitlab::lfs...
gitlab        | Configuring gitlab::project_features...
gitlab        | Configuring gitlab::smtp_settings...
gitlab        | Configuring gitlab::oauth...
gitlab        | Configuring gitlab::ldap...
gitlab        | Configuring gitlab::backups...
gitlab        | Configuring gitlab::backups::schedule...
gitlab        | Configuring gitlab::registry...
gitlab        | Configuring gitlab-shell...
gitlab        | Configuring nginx...
gitlab        | Configuring nginx::gitlab...
gitlab        | Migrating database...
gitlab        | rake aborted!
gitlab        | Psych::SyntaxError: (<unknown>): did not find expected key while parsing a block mapping at line 228 column 9
gitlab        | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:103:in `initialize'
gitlab        | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:60:in `new'
gitlab        | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:60:in `instance'
gitlab        | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:37:in `[]'
gitlab        | /home/git/gitlab/config/initializers/1_settings.rb:100:in `<top (required)>'
gitlab        | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
gitlab        | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
gitlab        | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
gitlab        | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
gitlab        | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
gitlab        | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
gitlab        | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:651:in `load_config_initializer'
gitlab        | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
gitlab        | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `each'
gitlab        | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
gitlab        | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
gitlab        | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
gitlab        | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
gitlab        | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
gitlab        | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
gitlab        | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
gitlab        | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
gitlab        | /home/git/gitlab/config/environment.rb:5:in `<top (required)>'
gitlab        | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
gitlab        | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
gitlab        | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
gitlab        | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
gitlab        | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require_environment!'
gitlab        | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
gitlab        | Tasks: TOP => db:migrate => environment
gitlab        | (See full trace by running task with --trace)
gitlab exited with code 0
```

below shows my docker-compose file, please refer it if helping

```
version: '2'

services:
  redis:
    container_name: redis
    restart: always
    image: sameersbn/redis:latest
    command:
    - --loglevel warning
    volumes:
    - /root/tmp/redis:/var/lib/redis:Z


  postgresql:
    container_name: postgresql
    restart: always
    image: sameersbn/postgresql:9.5-3
    volumes:
    - /root/tmp/postgresql:/var/lib/postgresql:Z
    environment:
    - DB_USER=gitlab
    - DB_PASS=gitlab
    - DB_NAME=gitlabhq_production
    - DB_EXTENSION=pg_trgm

  gitlab:
    container_name: gitlab
    restart: always
    image: sameersbn/gitlab:8.14.4
    depends_on:
    - redis
    - postgresql
    ports:
    - "80:80"
    - "10022:22"
    volumes:
    - /root/tmp/gitlab:/home/git/data:Z
    - /root/tmp/log:/var/log/gitlab:Z

    environment:
    - DEBUG=false

    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=gitlab
    - DB_PASS=gitlab
    - DB_NAME=gitlabhq_production

    - REDIS_HOST=redis
    - REDIS_PORT=6379

    - TZ=Asia/Taipei
    - GITLAB_TIMEZONE=Taipei

    - GITLAB_HTTPS=false
    - SSL_SELF_SIGNED=false

    - GITLAB_HOST=
    - GITLAB_PORT=80
    - GITLAB_SSH_PORT=
    #- GITLAB_RELATIVE_URL_ROOT=

    - GITLAB_SECRETS_DB_KEY_BASE=B8JWK9sSrZhvTJLBjT69ZWZmTN2sLL3MMnx5W8ck4gLg36lFGQSnSbht2qH4p8fT
    - GITLAB_SECRETS_SECRET_KEY_BASE=B8JWK9sSrZhvTJLBjT69ZWZmTN2sLL3MMnx5W8ck4gLg36lFGQSnSbht2qH4p8fT
    - GITLAB_SECRETS_OTP_KEY_BASE=B8JWK9sSrZhvTJLBjT69ZWZmTN2sLL3MMnx5W8ck4gLg36lFGQSnSbht2qH4p8fT

    #- GITLAB_ROOT_PASSWORD=
    #- GITLAB_ROOT_EMAIL=

    #- GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
    #- GITLAB_NOTIFY_PUSHER=false

```

**Comment by solidnerd** [comment]
Hey,
you missed some environment variables to start the gitlab container. What you need to set are the following envs `GITLAB_SECRETS_OTP_KEY_BASE`, `GITLAB_SECRETS_DB_KEY_BASE`, and `GITLAB_SECRETS_SECRET_KEY_BASE`.  For an explanation have a look at the [QuickStart](https://github.com/sameersbn/docker-gitlab#quick-start)

**Comment by duncau1234** [comment]
hey, in my first version of compose file I edited, I have already set 3
keys by pwgen command
but it doesn't work
Niclas Mietz <notifications@github.com>於 2016年12月18日 週日，00:54寫道：

**Comment by duncau1234** [comment]
finally, I found the problem, that is some of my configurations shown below going wrong 
would you please to check if statements or formats of configurations are not correct, thanks.

```
    - LDAP_ENABLED=true
    - LDAP_LABEL='LDAP'
    - LDAP_HOST=192.168.14.18
    - LDAP_PORT=389
    - LDAP_UID='sAMAccountName'
    - LDAP_METHOD='plain'
    - LDAP_BIND_DN='CN=test,CN=test_Users,DC=test_ideas,DC=test_iii,DC=test_org,DC=test_tw'
    - LDAP_PASS='d1e2v3o4p5s%'    
    - LDAP_ACTIVE_DIRECTORY=true
    - LDAP_ALLOW_USERNAME_OR_EMAIL_LOGIN=true
    - LDAP_BLOCK_AUTO_CREATED_USERS=false
    - LDAP_BASE='OU=IN_CHINESE,DC=test_ideas,DC=test_iii,DC=test_org,DC=test_tw'
```

**Comment by jostyee** [comment]
In fact GitLab has very poor support for CJK chars.

**Comment by duncau1234** [comment]
finally, I find the problem which causes the error.

firewall of AD server blocks request of my accessing, and thanks for all you guys who answsered me.
