### ISSUE TITLE
Mattermost commands page shows error 500

### ISSUE THREAD

**Issue by Kiina** [sameersbn/docker-gitlab#1057]
So I enabled and provided the url for my mattermost instance. But if I visit the template for the mattermost commands I get an error 500 with this log:

```
Started GET "/admin/application_settings/services/1162/edit" for ***** at 2017-01-19 12:22:44 +0100
Processing by Admin::ServicesController#edit as HTML
Parameters: {"id"=>"1162"}
Completed 500 Internal Server Error in 86ms (ActiveRecord: 5.0ms)

ActionView::Template::Error (undefined method `namespace' for nil:NilClass):
2: - unless @service.activated?
3: .row
4: .col-sm-9.col-sm-offset-3
5: = link_to new_namespace_project_mattermost_path(@project.namespace, @project), class: 'btn btn-lg' do
6: = custom_icon('mattermost_logo', size: 15)
7: = 'Add to Mattermost'
app/views/projects/services/mattermost_slash_commands/_installation_info.html.haml:5:in `_app_views_projects_services_mattermost_slash_commands__installation_info_html_haml__4001714506381749540_62464240'
app/views/projects/services/mattermost_slash_commands/_help.html.haml:15:in `_app_views_projects_services_mattermost_slash_commands__help_html_haml__2178739730624942833_20164120'
app/views/shared/_service_settings.html.haml:4:in `_app_views_shared__service_settings_html_haml___1503517927040710184_38594660'
app/views/admin/services/_form.html.haml:7:in `block in _app_views_admin_services__form_html_haml___2875566267950817132_49304920'
app/views/admin/services/_form.html.haml:6:in `_app_views_admin_services__form_html_haml___2875566267950817132_49304920'
app/views/admin/services/edit.html.haml:2:in `_app_views_admin_services_edit_html_haml__261082129411662130_49623120'
lib/gitlab/middleware/multipart.rb:93:in `call'
lib/gitlab/request_profiler/middleware.rb:15:in `call'
lib/gitlab/middleware/go.rb:16:in `call'
```

Same if I disable mattermost.

**Comment by janhommes** [comment]
I have the Mattermost Command 500 error too. 

The notifications are working for me. Did you enabled `Enable Incoming Webhooks` in Mattermost System Console?

**Comment by Kiina** [comment]
My Mattermost hooks work. I tested it via a curl on my computer. How do your gitlab settings look for it to work?

![image](https://cloud.githubusercontent.com/assets/2419591/22294131/632362f2-e312-11e6-8ed9-f95099f019af.png)

I tried leaving it empty instead of defining the test channel, makes no difference. My systemhook to hubot works.

**Comment by janhommes** [comment]
My configuration looks nearly the same. I used `#gitlab`. Maybe the `#` is missing?

**Comment by Kiina** [comment]
So I found that in a project under services there is a test button for this kind of thing. Error 500 if press test. But atleast I can get some logs.

```
Started GET "/*******/*******/services/mattermost/test" for ******* at 2017-01-25 16:50:28 +0100
Processing by Projects::ServicesController#test as HTML
Parameters: {"namespace_id"=>"**********", "project_id"=>"*********", "id"=>"mattermost"}
Completed 500 Internal Server Error in 144ms (ActiveRecord: 7.2ms)
TypeError (wrong argument type nil (expected String)):
app/models/repository.rb:122:in `commits'
lib/gitlab/data_builder/push.rb:71:in `build_sample'
app/models/service.rb:87:in `test_data'
app/controllers/projects/services_controller.rb:33:in `test'
lib/gitlab/middleware/multipart.rb:93:in `call'
lib/gitlab/request_profiler/middleware.rb:15:in `call'
lib/gitlab/middleware/go.rb:16:in `call'
```

**Comment by Kiina** [comment]
So if you go to a project, then services and mattermost commands there it works (for me). Not sure if this is supposed to be

**Comment by garbast** [comment]
Error 500 for admin/application_settings/integrations/mattermost_slash_commands/edit is still happening
