### ISSUE TITLE
after upgrading from 8.15.2 to 8.16.3 no changes to branches can be made

### ISSUE THREAD

**Issue by janwillies** [sameersbn/docker-gitlab#1074]
The update itself succeeded and gitlab appears to be working fine. However, no changes can be made to branches, resulting in:

```
Completed 500 Internal Server Error in 2089ms (ActiveRecord: 6.3ms)
Repository::CommitError (Could not update branch 95-update-gitlab-to-8-16-3. Please refresh and try again.):
app/models/repository.rb:256:in `update_ref!'
app/models/repository.rb:179:in `block in add_branch'
app/services/git_hooks_service.rb:21:in `execute'
app/models/repository.rb:178:in `add_branch'
app/services/create_branch_service.rb:27:in `execute'
app/controllers/projects/branches_controller.rb:36:in `create'
lib/gitlab/middleware/multipart.rb:93:in `call'
lib/gitlab/request_profiler/middleware.rb:15:in `call'
lib/gitlab/middleware/go.rb:16:in `call'
```

Running `bundle exec rake gitlab:check RAILS_ENV=production` doesn't reveal any problems.

```
Repo storage directories are symlinks?
default... no
Repo paths owned by git:git?
default... yes
Repo paths access is drwxrws---?
default... yes
...
```
Since only branches are affected, it looks like a permission problem. Checking the permissions in `/home/git/data/`:

```
drwxr-xr-x. 12 git  git  4.0K Nov 22 21:16 .
drwxr-xr-x.  1 git  git  4.0K Jan 30 07:59 ..
-rw-r--r--.  1 git  git   128 Apr  6  2016 .secret
drwx------.  2 git  git  4.0K Apr 19  2016 .ssh
drwxr-xr-x.  4 git  git  4.0K Jan 30 01:03 backups
drwxr-xr-x. 21 git  git  4.0K Jan  2 09:53 builds
drwx------.  2 1001 1001  16K Apr 19  2016 lost+found
drwxr-xr-x.  2 1001 1001 4.0K Mar 25  2016 postgresql
drwxrws---. 32 git  git  4.0K Jan 25 11:01 repositories
drwxr-xr-x. 10 git  git  4.0K Apr 27  2016 shared
drwxr-xr-x.  2 root root 4.0K Mar 31  2016 ssh
drwxr-xr-x.  4 git  git  4.0K Jan 29 22:03 tmp
drwx------. 18 git  git  4.0K Dec 13 18:23 uploads
```

**Comment by janwillies** [comment]
The filesystem was 100% full, because some manually created backups where not removed again. 

Is this something an upgrade could check?
