### ISSUE TITLE
Automatic upgrade from 16.6 to 17.3 failing.

### ISSUE THREAD

**Issue by mlewe** [sameersbn/docker-gitlab#1136]
After upgrading my gitlab container from version 16.6 to 17.3, I only got a 500 error, with the following error-message in `production.log`.
```
ActionView::Template::Error (Could not load compiled manifest from /home/git/gitlab/public/assets/webpack/manifest.json - have you run `rake webpack:compile`? (original error No such file or directory @ rb_sysopen - /home/git/gitlab/public/assets/webpack/manifest.json)):
    28:   = stylesheet_link_tag "application", media: "all"
    29:   = stylesheet_link_tag "print",       media: "print"
    30: 
    31:   = javascript_include_tag(*webpack_asset_paths("application"))
    32: 
    33:   - if content_for?(:page_specific_javascripts)
    34:     = yield :page_specific_javascripts
  app/views/layouts/_head.html.haml:31:in `_app_views_layouts__head_html_haml__1347438949035901697_46322760'
  app/views/layouts/application.html.haml:3:in `_app_views_layouts_application_html_haml__2341115093362490173_41948180'
  app/views/layouts/dashboard.html.haml:5:in `_app_views_layouts_dashboard_html_haml___920952330409732785_93242640'
  lib/gitlab/middleware/multipart.rb:93:in `call'
  lib/gitlab/request_profiler/middleware.rb:14:in `call'
  lib/gitlab/middleware/go.rb:16:in `call'
```
I have set up the container with a `GITLAB_RELATIVE_URL_ROOT`.

Manually running `app:rake webpack:compile` seems to have fixed the problem for now.

**Comment by solidnerd** [comment]
Test this again if you check out latest version or later `8.17.4`. Otherwise reopen this issue.

**Comment by mlewe** [comment]
Working perfectly with 8.17.4 👍
