### ISSUE TITLE
ERROR: Registering runner... failed 

### ISSUE THREAD

**Issue by jarvan4dev** [sameersbn/docker-gitlab#1217]
Hello, I am depressed with gitlab-runner, could you give me a hand!

The following is error:

```
MacBook-Pro:~$   docker run --name gitlab-ci-runner -it --rm -h gitlab-ci-runner.local.host   -v /Users/jarvan4dev/Documents/docker/gitlab/gitlab-ci-runner:/home/gitlab_ci_runner/data   sameersbn/gitlab-ci-runner:latest
Starting gitlab-ci-runner...
Please enter the gitlab-ci coordinator URL (e.g. http://gitlab-ci.org/ )
http://localhost:10080/ci
Please enter the gitlab-ci token for this runner: 
-EyVjGAifMfbBz2GxAiF
Registering runner as gitlab-ci-runner.local.host with registration token: -EyVjGAifMfbBz2GxAiF, url: http://localhost:10080/ci.
/usr/lib/ruby/2.1.0/net/http.rb:879:in `initialize': Connection refused - connect(2) for "localhost" port 10080 (Errno::ECONNREFUSED)
	from /usr/lib/ruby/2.1.0/net/http.rb:879:in `open'
	from /usr/lib/ruby/2.1.0/net/http.rb:879:in `block in connect'
	from /usr/lib/ruby/2.1.0/timeout.rb:75:in `timeout'
	from /usr/lib/ruby/2.1.0/net/http.rb:878:in `connect'
	from /usr/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
	from /usr/lib/ruby/2.1.0/net/http.rb:852:in `start'
	from /usr/lib/ruby/2.1.0/net/http.rb:1375:in `request'
	from /home/gitlab_ci_runner/gitlab-ci-runner/vendor/bundle/ruby/2.1.0/gems/httparty-0.11.0/lib/httparty/request.rb:92:in `perform'
	from /home/gitlab_ci_runner/gitlab-ci-runner/vendor/bundle/ruby/2.1.0/gems/httparty-0.11.0/lib/httparty.rb:461:in `perform_request'
	from /home/gitlab_ci_runner/gitlab-ci-runner/vendor/bundle/ruby/2.1.0/gems/httparty-0.11.0/lib/httparty.rb:414:in `post'
	from /home/gitlab_ci_runner/gitlab-ci-runner/lib/network.rb:88:in `register_runner'
	from /home/gitlab_ci_runner/gitlab-ci-runner/lib/setup.rb:38:in `register_runner'
	from /home/gitlab_ci_runner/gitlab-ci-runner/lib/setup.rb:9:in `initialize'
	from ./bin/setup:5:in `new'
	from ./bin/setup:5:in `<main>'
```

The following is my docker components:

```
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS                                                                                           NAMES
3e6c410df221        sameersbn/gitlab:latest       "/sbin/entrypoint...."   8 hours ago         Up 30 minutes       443/tcp, 0.0.0.0:10022->22/tcp, 0.0.0.0:10080->80/tcp                                           gitlab
04f3d7bff312        sameersbn/redis:latest        "/sbin/entrypoint.sh"    8 hours ago         Up 33 minutes       6379/tcp                                                                                        gitlab-redis
75d532b6e054        sameersbn/postgresql:latest   "/sbin/entrypoint.sh"    8 hours ago         Up 33 minutes       5432/tcp                                                                                        gitlab-postgresql
```

**Comment by frostieDE** [comment]
As you seem to be running `gitlab-runner` within Docker, `localhost` refers to the docker container that runs `gitlab-runner` and not your actual host machine (which redirects port `10080` to the docker container which runs gitlab). Thus, you might chance `http://localhost:10080/ci` to `http://172.17.0.1:10080/ci` (note: depending on your configuration, the host ip from within the container might differ).

**Comment by jarvan4dev** [comment]
@frostieDE Thanks so much, but it's not working still, the following is the error

![image](https://cloud.githubusercontent.com/assets/9948677/26478328/13bd6762-41fe-11e7-821e-0b11f61cb4fc.png)

this is my docker container list

```
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS                                                                                           NAMES
3e6c410df221        sameersbn/gitlab:latest       "/sbin/entrypoint...."   9 days ago          Up 19 minutes       443/tcp, 0.0.0.0:10022->22/tcp, 0.0.0.0:10080->80/tcp                                           gitlab
04f3d7bff312        sameersbn/redis:latest        "/sbin/entrypoint.sh"    9 days ago          Up 19 minutes       6379/tcp                                                                                        gitlab-redis
75d532b6e054        sameersbn/postgresql:latest   "/sbin/entrypoint.sh"    9 days ago          Up 19 minutes       5432/tcp                                                                                        gitlab-postgresql
9e0273050747        jarvan4dev/utility            "/usr/sbin/sshd -D"      2 weeks ago         Up 17 hours         0.0.0.0:5672->5672/tcp, 0.0.0.0:15672->15672/tcp, 0.0.0.0:22222->22/tcp, 0.0.0.0:8088->80/tcp   hungry_kalam
```

and I got the ip of gitlab docker container with the command
```
docker inspect --format '{{ .NetworkSettings.IPAddress }}' 3e6c410df221
```

Could you give a help?

**Comment by solidnerd** [comment]
Hey, 
when you are running a docker compose `v2` you don't need to specify any IP Address.

First of all using localhost in a container is **never** a good idea, because every container has it's own localhost (lo) interface. This would be only working when you are changing the network_mode to host, but this is not necessary as well. 

For the case as I described in the beginning you get your own network and your need only to enter as coordinator url the following `http://gitlab` .

But this depends on how your `docker-compose.yml`is declared. But give you better help. I would appreciate to see your `docker-compose.yml` with obfuscated values for password and other secrets.
