### ISSUE TITLE
Migration failed from 9.2.7 to 9.3.0

### ISSUE THREAD

**Issue by TimeBye** [sameersbn/docker-gitlab#1300]
Hi

I'm having issues trying to upgrade from 9.2.7 to 9.3.0,using a mysql-database.
I received this error

```
Migrating database...
Missing Rails.application.secrets.jws_private_key for production environment. The secret will be generated and stored in config/secrets.yml.
rake aborted!
StandardError: An error has occurred, all later migrations canceled:
Validation failed: Name has already been taken
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/validations.rb:79:in `raise_record_invalid'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/validations.rb:43:in `save!'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/transactions.rb:291:in `block in save!'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/transactions.rb:220:in `transaction'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/transactions.rb:291:in `save!'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/persistence.rb:265:in `block in update!'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/transactions.rb:220:in `transaction'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/persistence.rb:263:in `update!'
/home/git/gitlab/db/migrate/20170503140202_turn_nested_groups_into_regular_groups_for_mysql.rb:56:in `block in up'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/relation/batches.rb:51:in `block (2 levels) in find_each'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/relation/batches.rb:51:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/relation/batches.rb:51:in `block in find_each'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/relation/batches.rb:124:in `find_in_batches'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/relation/batches.rb:50:in `find_each'
/home/git/gitlab/db/migrate/20170503140202_turn_nested_groups_into_regular_groups_for_mysql.rb:28:in `up'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:611:in `exec_migration'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:591:in `block in migrate'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:590:in `migrate'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:768:in `migrate'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:1046:in `ddl_transaction'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:959:in `block in migrate'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `migrate'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:823:in `up'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:801:in `migrate'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
ActiveRecord::RecordInvalid: Validation failed: Name has already been taken
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/validations.rb:79:in `raise_record_invalid'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/validations.rb:43:in `save!'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/transactions.rb:291:in `block in save!'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/transactions.rb:220:in `transaction'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/transactions.rb:291:in `save!'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/persistence.rb:265:in `block in update!'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/transactions.rb:220:in `transaction'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/persistence.rb:263:in `update!'
/home/git/gitlab/db/migrate/20170503140202_turn_nested_groups_into_regular_groups_for_mysql.rb:56:in `block in up'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/relation/batches.rb:51:in `block (2 levels) in find_each'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/relation/batches.rb:51:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/relation/batches.rb:51:in `block in find_each'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/relation/batches.rb:124:in `find_in_batches'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/relation/batches.rb:50:in `find_each'
/home/git/gitlab/db/migrate/20170503140202_turn_nested_groups_into_regular_groups_for_mysql.rb:28:in `up'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:611:in `exec_migration'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:591:in `block in migrate'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:590:in `migrate'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:768:in `migrate'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:1046:in `ddl_transaction'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:959:in `block in migrate'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `migrate'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:823:in `up'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/migration.rb:801:in `migrate'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

Could you give me a hand?

```
image: redis:3.2.6
image: mysql:5.7
image: sameersbn/gitlab:9.2.7
```

```
root@a59880bb369e:/# mysql -u root -p -e"show grants for gitlab;"
Enter password: 
+-----------------------------------------------------------------+
| Grants for gitlab@%                                             |
+-----------------------------------------------------------------+
| GRANT USAGE ON *.* TO 'gitlab'@'%'                              |
| GRANT ALL PRIVILEGES ON `gitlabhq_production`.* TO 'gitlab'@'%' |
+-----------------------------------------------------------------+
```

Thanks in advance

**Comment by solidnerd** [comment]
Hey @TimeBye,
it seems that subgroups were removed in 9.3.X and this could cause the error. https://about.gitlab.com/2017/06/22/gitlab-9-3-released/#dropping-support-for-subgroups-in-mysql .

**Comment by frank-dspeed** [comment]
@solidnerd this should then fast get added to the readme i think  as this is the first point where they could see that

**Comment by jianchan** [comment]
@solidnerd I also received this error. but I don't know how to reslove it. 
I find the detail msg below. How can I find the conflict record.

`-- execute("INSERT INTO members (access_level, source_id, source_type, user_id, notification_level, type, created_at, updated_at)\nVALUES (50, 71, 'Namespace', 28, 3, 'GroupMember', '2018-11-13 12:26:25', '2018-11-13 12:26:25'), (50, 71, 'Namespace', 29, 3, 'GroupMember', '2018-11-13 12:26:25', '2018-11-13 12:26:25'), (50, 71, 'Namespace', 33, 3, 'GroupMember', '2018-11-13 12:26:25', '2018-11-13 12:26:25'), (40, 71, 'Namespace', 39, 3, 'GroupMember', '2018-11-13 12:26:25', '2018-11-13 12:26:25'), (50, 71, 'Namespace', 40, 3, 'GroupMember', '2018-11-13 12:26:25', '2018-11-13 12:26:25')\n")
   -> 0.0011s
-- execute("INSERT INTO members (access_level, source_id, source_type, user_id, notification_level, type, created_at, updated_at)\nVALUES (40, 72, 'Namespace', 11, 3, 'GroupMember', '2018-11-13 12:26:25', '2018-11-13 12:26:25')\n")
   -> 0.0009s
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Validation failed: Name has already been taken/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/validations.rb:79:in `raise_record_invalid'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/validations.rb:43:in `save!'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.8/lib/active_record/transactions.rb:291:in `block in save!`


and a part of the database data is

| 526 |           40 |        72 | Namespace   |      11 |                  3 | GroupMember   | 2018-11-13 13:16:46 | 2018-11-13 13:16:46 |          NULL | NULL         | NULL         | NULL               | NULL         | NULL       |
| 527 |           50 |        72 | Namespace   |      14 |                  3 | GroupMember   | 2018-11-13 13:16:46 | 2018-11-13 13:16:46 |          NULL | NULL         | NULL         | NULL               | NULL         | NULL       |
| 136 |           50 |        77 | Namespace   |      11 |                  3 | GroupMember   | 2017-10-20 01:28:30 | 2017-10-20 01:28:30 |          NULL | NULL         | NULL         | NULL               | NULL         | NULL       |
| 185 |           40 |        77 | Namespace   |       9 |                  3 | GroupMember   | 2017-12-04 01:44:07 | 2017-12-04 01:44:07 |            11 | NULL         | NULL         | NULL               | NULL         | NULL       |
| 186 |           40 |        77 | Namespace   |       7 |                  3 | GroupMember   | 2017-12-04 01:44:32 | 2017-12-04 01:44:32 |            11 | NULL         | NULL         | NULL               | NULL         | NULL       |
| 137 |           50 |        78 | Namespace   |      11 |                  3 | GroupMember   | 2017-10-20 01:56:23 | 2017-10-20 01:56:23 |          NULL | NULL         | NULL         | NULL               | NULL         | NULL       |
| 167 |           40 |        78 | Namespace   |      51 |                  3 | GroupMember   | 2017-11-21 09:00:04 | 2017-11-21 09:29:16 |            11 | NULL         | NULL         | NULL               | NULL         | NULL       |
| 138 |           50 |        79 | Namespace   |      11 |                  3 | GroupMember   | 2017-10-20 02:39:23 | 2017-10-20 02:39:23 |          NULL | NULL         | NULL         | NULL               | NULL         | NULL       |
| 139 |           40 |        79 | Namespace   |      51 |                  3 | GroupMember   | 2017-10-20 02:42:12 | 2017-10-20 02:42:12 |            11 | NULL         | NULL         | NULL               | NULL         | NULL       |
| 140 |           40 |        79 | Namespace   |      47 |                  3 | GroupMember   | 2017-10-20 02:42:26 | 2017-10-20 02:42:26 |            11 | NULL         | NULL         | NULL               | NULL         | NULL       |
| 142 |           50 |        81 | Namespace   |       7 |                  3 | GroupMember   | 2017-10-24 09:02:04 | 2017-10-24 09:02:04 |          NULL | NULL         | NULL         | NULL               | NULL         | NULL       |
| 143 |           50 |        82 | Namespace   |      11 |                  3 | GroupMember   | 2017-11-03 07:08:52 | 2017-11-03 07:08:52 |          NULL | NULL         | NULL         | NULL               | NULL         | NULL       |
