### ISSUE TITLE
GitLab page not opening

### ISSUE THREAD

**Issue by GarbageYard** [sameersbn/docker-gitlab#1346]
I am running separate GitLab, Redis and PostgreSQL containers in Kubernetes with GlusterFS for persistence. All hosts are having RancherOS.

```
[root@node-a ~]# cat /etc/os-release
NAME="RancherOS"
VERSION=v1.0.3
ID=rancheros
ID_LIKE=
VERSION_ID=v1.0.3
PRETTY_NAME="RancherOS v1.0.3"
HOME_URL="http://rancher.com/rancher-os/"
SUPPORT_URL="https://forums.rancher.com/c/rancher-os"
BUG_REPORT_URL="https://github.com/rancher/os/issues"
BUILD_ID=
[root@node-a ~]#
[root@node-a ~]#
[root@node-a ~]# docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Wed Jan 11 00:23:16 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Wed Jan 11 00:23:16 2017
 OS/Arch:      linux/amd64
[root@node-a ~]#
[root@node-a ~]#
[root@node-a ~]# docker info
Containers: 28
 Running: 24
 Paused: 0
 Stopped: 4
Images: 24
Server Version: 1.12.6
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.9.34-rancher
Operating System: RancherOS v1.0.3
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.615 GiB
Name: node-a.c.kubernetes-174104.internal
ID: IEVO:AQCT:EOBT:CNOQ:Y32U:KFJC:ZYIG:WWRP:C254:UCA6:YGW5:PF4Y
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

```

GitLab service:
```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: gitlab
  name: gitlab
spec:
  ports:
  - name: "443"
    port: 443
    targetPort: 443
  - name: "80"
    port: 80
    targetPort: 80
  - name: "10022"
    port: 10022
    targetPort: 22
  selector:
    io.kompose.service: gitlab
status:
  loadBalancer: {}
```

When i start GitLab container in Kubernetes, here's the log:
```
[rancher@node-c ~]$ docker logs d84904cf5c02 -f
Initializing logdir...
Initializing datadir...
Installing configuration templates...
Configuring gitlab...
Configuring gitlab::database............................
Configuring gitlab::redis
Configuring gitlab::secrets...
Configuring gitlab::sidekiq...
Configuring gitlab::gitaly...
Configuring gitlab::gitlab-workhorse...
Configuring gitlab::unicorn...
Configuring gitlab::timezone...
Configuring gitlab::rack_attack...
Configuring gitlab::ci...
Configuring gitlab::artifacts...
Configuring gitlab::lfs...
Configuring gitlab::mattermost...
Configuring gitlab::project_features...
Configuring gitlab::oauth...
Configuring gitlab::ldap...
Configuring gitlab::cron_jobs...
Configuring gitlab::backups...
Configuring gitlab::registry...
Configuring gitlab::pages...
Configuring gitlab-shell...
Configuring nginx...
Configuring nginx::gitlab...
Setting up GitLab for firstrun. Please be patient, this could take a while...
Missing Rails.application.secrets.jws_private_key for production environment. The secret will be generated and stored in config/secrets.yml.
gitlabhq_production already exists
Migrating database...
Clearing cache...
2017-09-08 10:14:59,379 CRIT Supervisor running as root (no user in config file)
2017-09-08 10:14:59,380 WARN Included extra file "/etc/supervisor/conf.d/gitaly.conf" during parsing
2017-09-08 10:14:59,380 WARN Included extra file "/etc/supervisor/conf.d/nginx.conf" during parsing
2017-09-08 10:14:59,380 WARN Included extra file "/etc/supervisor/conf.d/gitlab-workhorse.conf" during parsing
2017-09-08 10:14:59,380 WARN Included extra file "/etc/supervisor/conf.d/sshd.conf" during parsing
2017-09-08 10:14:59,381 WARN Included extra file "/etc/supervisor/conf.d/unicorn.conf" during parsing
2017-09-08 10:14:59,381 WARN Included extra file "/etc/supervisor/conf.d/cron.conf" during parsing
2017-09-08 10:14:59,381 WARN Included extra file "/etc/supervisor/conf.d/mail_room.conf" during parsing
2017-09-08 10:14:59,381 WARN Included extra file "/etc/supervisor/conf.d/sidekiq.conf" during parsing
2017-09-08 10:14:59,444 INFO RPC interface 'supervisor' initialized
2017-09-08 10:14:59,444 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2017-09-08 10:14:59,445 INFO supervisord started with pid 1
2017-09-08 10:15:00,448 INFO spawned: 'gitaly' with pid 697
2017-09-08 10:15:00,450 INFO spawned: 'sidekiq' with pid 698
2017-09-08 10:15:00,462 INFO spawned: 'unicorn' with pid 699
2017-09-08 10:15:00,469 INFO spawned: 'gitlab-workhorse' with pid 700
2017-09-08 10:15:00,481 INFO spawned: 'cron' with pid 701
2017-09-08 10:15:00,487 INFO spawned: 'nginx' with pid 702
2017-09-08 10:15:00,494 INFO spawned: 'sshd' with pid 703
2017-09-08 10:15:01,455 INFO success: gitaly entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-09-08 10:15:01,455 INFO success: sidekiq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-09-08 10:15:01,478 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-09-08 10:15:01,478 INFO success: gitlab-workhorse entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-09-08 10:15:01,819 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-09-08 10:15:01,819 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2017-09-08 10:15:01,820 INFO success: sshd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

I couldn't find any error in any of the files within `/var/log/gitlab/` except for the following which too looks something that can be ignored.

```
root@gitlab-748072774-chztb:/var/log/gitlab/gitlab# cat production.log
Raven 2.4.0 configured not to capture errors: DSN not set
Raven 2.4.0 configured not to capture errors: DSN not set
Raven 2.4.0 configured not to capture errors: DSN not set
Raven 2.4.0 configured not to capture errors: DSN not set
Raven 2.4.0 configured not to capture errors: DSN not set
Scheduling removal of build artifacts
StuckCiJobsWorker: Cleaning stuck builds
Scoped order and limit are ignored, it's forced to be batch order and batch size
Scheduling removal of build artifacts
StuckCiJobsWorker: Cleaning stuck builds
```

I am able to telnet to the host on port 80 where the GitLab pod is running but somehow the GitLab page is not opening up. I get the following error when i hit the public URL (http://35.xxx.yyy.zz/):

```
 Network Error (tcp_error)

A communication error occurred: "Connection refused"
The Web Server may be down, too busy, or experiencing other problems preventing it from responding to requests. You may wish to try again at a later time.

For assistance, contact your network support team. 
```

I was trying to investigate using some commands described in [this](https://gitlab.com/gitlab-org/gitlab-ce/issues/23088) page but ```rake``` command is failing.

```
root@gitlab-748072774-chztb:/home/git/gitlab# rake
rake     rake2.3
root@gitlab-748072774-chztb:/home/git/gitlab# which rake2.3
/usr/bin/rake2.3
root@gitlab-748072774-chztb:/home/git/gitlab# rake gitlab:check
/usr/lib/ruby/2.3.0/rubygems.rb:241:in `bin_path': can't find gem rake (>= 0.a) (Gem::GemNotFoundException)
        from /usr/bin/rake:22:in `<main>'
root@gitlab-748072774-chztb:/home/git/gitlab# rake2.3 gitlab:check
/usr/lib/ruby/2.3.0/rubygems.rb:241:in `bin_path': can't find gem rake (>= 0.a) (Gem::GemNotFoundException)
        from /usr/bin/rake2.3:22:in `<main>'
```

Any help will really be appreciated.

**Comment by GarbageYard** [comment]
I found the issue. It was because my GitLab service was configured to use `type: ClusterIP`. What was needed was `type: LoadBalancer` and i had to use external Load Balancer.
