### ISSUE TITLE
Error Code 500 after upgrading to 10.0.4 due to LDAP

### ISSUE THREAD

**Issue by boeserwolf91** [sameersbn/docker-gitlab#1388]
Today I updated my gitlab instance from 9.5.5 to 10.0.4. At first it seemed to work but somehow I can't push / pull to any of my projects. I always get the error code 500.

The unicorn error log shows this:

```
I, [2017-10-22T18:27:13.206051 #603]  INFO -- : listening on addr=/home/git/gitlab/tmp/sockets/gitlab.socket fd=16
I, [2017-10-22T18:27:13.206436 #603]  INFO -- : listening on addr=127.0.0.1:8080 fd=17
I, [2017-10-22T18:27:13.229149 #603]  INFO -- : master process ready
I, [2017-10-22T18:27:13.406292 #696]  INFO -- : worker=0 ready
I, [2017-10-22T18:27:13.420829 #702]  INFO -- : worker=2 ready
I, [2017-10-22T18:27:13.432770 #699]  INFO -- : worker=1 ready
W, [2017-10-22T18:34:08.500353 #699]  WARN -- : #<Unicorn::HttpServer:0x0000000002fb3860>: worker (pid: 699) exceeds memory limit (423473152.0 bytes > 363067190 bytes)
W, [2017-10-22T18:34:08.500497 #699]  WARN -- : Unicorn::WorkerKiller send SIGQUIT (pid: 699) alive: 385 sec (trial 1)
I, [2017-10-22T18:34:08.840599 #603]  INFO -- : reaped #<Process::Status: pid 699 exit 0> worker=1
I, [2017-10-22T18:34:08.970260 #1037]  INFO -- : worker=1 ready
```

The production log shows:

```
Started GET "//stefan.wolf/testproject.git/info/refs?service=git-receive-pack" for 192.168.51.108 at 2017-10-22 18:39:43 +0200
Processing by Projects::GitHttpController#info_refs as */*
  Parameters: {"service"=>"git-receive-pack", "namespace_id"=>"stefan.wolf", "project_id"=>"testproject.git"}
Filter chain halted as :authenticate_user rendered or redirected
Completed 401 Unauthorized in 17ms (Views: 2.4ms | ActiveRecord: 2.0ms)
Started GET "//stefan.wolf/testproject.git/info/refs?service=git-receive-pack" for 192.168.51.108 at 2017-10-22 18:39:43 +0200
Processing by Projects::GitHttpController#info_refs as */*
  Parameters: {"service"=>"git-receive-pack", "namespace_id"=>"stefan.wolf", "project_id"=>"testproject.git"}
Completed 500 Internal Server Error in 39ms (ActiveRecord: 4.1ms)

Net::LDAP::Error (SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed):
  lib/gitlab/ldap/authentication.rb:37:in `login'
  lib/gitlab/ldap/authentication.rb:18:in `block in login'
  lib/gitlab/ldap/authentication.rb:16:in `each'
  lib/gitlab/ldap/authentication.rb:16:in `find'
  lib/gitlab/ldap/authentication.rb:16:in `login'
  lib/gitlab/auth.rb:62:in `block in find_with_user_password'
  lib/gitlab/auth/unique_ips_limiter.rb:17:in `limit_user!'
  lib/gitlab/auth.rb:53:in `find_with_user_password'
  lib/gitlab/auth.rb:111:in `user_with_password_for_git'
  lib/gitlab/auth.rb:36:in `find_for_git_client'
  app/controllers/projects/git_http_client_controller.rb:98:in `handle_basic_authentication'
  app/controllers/projects/git_http_client_controller.rb:34:in `authenticate_user'
  lib/gitlab/i18n.rb:46:in `with_locale'
  lib/gitlab/i18n.rb:52:in `with_user_locale'
  app/controllers/application_controller.rb:326:in `set_locale'
  lib/gitlab/middleware/multipart.rb:93:in `call'
  lib/gitlab/request_profiler/middleware.rb:14:in `call'
  lib/gitlab/middleware/go.rb:17:in `call'
  lib/gitlab/etag_caching/middleware.rb:11:in `call'
  lib/gitlab/request_context.rb:18:in `call'
  lib/gitlab/metrics/requests_rack_middleware.rb:27:in `call'
```

So I think it could be an issue with LDAP. Did the GitLab-Team changed something at this point? I can still access the GitLab page with LDAP... Okay now after loggin out. I can't log in with LDAP anymore. It shows: "Could not authenticate you from Ldapmain because "Ssl connect returned=1 errno=0 state=sslv3 read server certificate b: certificate verify failed"."

Would be great someone can help me. Thanks :)

**Comment by boeserwolf91** [comment]
okay thanks. I found the answer in the GitLab blog post of GitLab 10.0 https://about.gitlab.com/2017/09/22/gitlab-10-0-released/ 
The config option LDAP_VERIFY_SSL was the problem.
