### ISSUE TITLE
Having issue in update the latest version of GitLAB.

### ISSUE THREAD

**Issue by Kaleesastha** [sameersbn/docker-gitlab#1413]
Gitlab update failed in db migration. The exception trace is given below for your reference,

2017-11-19T05:56:34.673873000Z Migrating database...
2017-11-19T05:56:48.807180000Z Missing Rails.application.secrets.jws_private_key for production environment. The secret will be generated and stored in config/secrets.yml.
2017-11-19T05:56:50.217117000Z rake aborted!
2017-11-19T05:56:50.217417000Z StandardError: An error has occurred, all later migrations canceled:
2017-11-19T05:56:50.217937000Z namespace directory cannot be moved
2017-11-19T05:56:50.218209000Z /home/git/gitlab/app/models/concerns/storage/legacy_namespace.rb:20:in `block in move_dir'
2017-11-19T05:56:50.218459000Z /home/git/gitlab/app/models/concerns/storage/legacy_namespace.rb:11:in `each'
2017-11-19T05:56:50.218705000Z /home/git/gitlab/app/models/concerns/storage/legacy_namespace.rb:11:in `move_dir'
2017-11-19T05:56:50.218976000Z /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:432:in `block in make_lambda'
2017-11-19T05:56:50.219234000Z /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:228:in `block in halting_and_conditional'
2017-11-19T05:56:50.232695000Z /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
2017-11-19T05:56:50.232922000Z Gitlab::UpdatePathError: namespace directory cannot be moved

Kindly help me to resolve this issue.

**Comment by mikeblanton** [comment]
Any word on this one? I'm trying to go from 10.0.4 to 10.1.0 and I'm getting a similar issue.
