### ISSUE TITLE
Error when running with docker-compose

### ISSUE THREAD

**Issue by rohithn** [sameersbn/docker-gitlab#1554]
I am trying to set up gitlab with docker-compose. I used the docker-compose.yml in the master branch, but the gitlab module exits with the following error - `NameError: uninitialized constant Hashie`. See stack trace below:

```
gitlab_1      | Initializing logdir...
gitlab_1      | Initializing datadir...
gitlab_1      | Installing configuration templates...
gitlab_1      | Configuring gitlab...
gitlab_1      | Configuring gitlab::database
gitlab_1      | Configuring gitlab::redis
gitlab_1      | Configuring gitlab::secrets...
gitlab_1      | Configuring gitlab::sidekiq...
gitlab_1      | Configuring gitlab::gitaly...
gitlab_1      | Configuring gitlab::monitoring...
gitlab_1      | Configuring gitlab::gitlab-workhorse...
gitlab_1      | Configuring gitlab::unicorn...
gitlab_1      | Configuring gitlab::timezone...
gitlab_1      | Configuring gitlab::rack_attack...
gitlab_1      | Configuring gitlab::ci...
gitlab_1      | Configuring gitlab::artifacts...
gitlab_1      | Configuring gitlab::lfs...
gitlab_1      | Configuring gitlab::uploads...
gitlab_1      | Configuring gitlab::mattermost...
gitlab_1      | Configuring gitlab::project_features...
gitlab_1      | Configuring gitlab::oauth...
gitlab_1      | Configuring gitlab::ldap...
gitlab_1      | Configuring gitlab::cron_jobs...
gitlab_1      | Configuring gitlab::backups...
gitlab_1      | Configuring gitlab::registry...
gitlab_1      | Configuring gitlab::pages...
gitlab_1      | Configuring gitlab-shell...
gitlab_1      | Configuring nginx...
gitlab_1      | Configuring nginx::gitlab...
gitlab_1      | Setting up GitLab for firstrun. Please be patient, this could take a while...
gitlab_1      | rake aborted!
gitlab_1      | Bundler::GemRequireError: There was an error while trying to load the gem 'omniauth-auth0'.
gitlab_1      | Gem Load Error is: uninitialized constant Hashie
gitlab_1      | Backtrace for gem load error is:
gitlab_1      | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/omniauth-1.4.2/lib/omniauth/key_store.rb:5:in `<module:OmniAuth>'
gitlab_1      | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/omniauth-1.4.2/lib/omniauth/key_store.rb:3:in `<top (required)>'
gitlab_1      | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/omniauth-1.4.2/lib/omniauth/strategy.rb:1:in `<top (required)>'
gitlab_1      | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/omniauth-oauth2-1.4.0/lib/omniauth/strategies/oauth2.rb:15:in `<class:OAuth2>'
gitlab_1      | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/omniauth-oauth2-1.4.0/lib/omniauth/strategies/oauth2.rb:14:in `<module:Strategies>'
gitlab_1      | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/omniauth-oauth2-1.4.0/lib/omniauth/strategies/oauth2.rb:8:in `<module:OmniAuth>'
gitlab_1      | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/omniauth-oauth2-1.4.0/lib/omniauth/strategies/oauth2.rb:7:in `<top (required)>'
gitlab_1      | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/omniauth-oauth2-1.4.0/lib/omniauth-oauth2.rb:2:in `<top (required)>'
.
.
.
gitlab_1      | Caused by:
gitlab_1      | NameError: uninitialized constant Hashie
gitlab_1      | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/omniauth-1.4.2/lib/omniauth/key_store.rb:5:in `<module:OmniAuth>'
gitlab_1      | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/omniauth-1.4.2/lib/omniauth/key_store.rb:3:in `<top (required)>'
gitlab_1      | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/omniauth-1.4.2/lib/omniauth/strategy.rb:1:in `<top (required)>'
gitlab_1      | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/omniauth-oauth2-1.4.0/lib/omniauth/strategies/oauth2.rb:15:in `<class:OAuth2>'
gitlab_1      | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/omniauth-oauth2-1.4.0/lib/omniauth/strategies/oauth2.rb:14:in `<module:Strategies>'
gitlab_1      | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/omniauth-oauth2-1.4.0/lib/omniauth/strategies/oauth2.rb:8:in `<module:OmniAuth>'
gitlab_1      | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/omniauth-oauth2-1.4.0/lib/omniauth/strategies/oauth2.rb:7:in `<top (required)>'
gitlab_1      | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/omniauth-oauth2-1.4.0/lib/omniauth-oauth2.rb:2:in `<top (required)>'
gitlab_1      | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/omniauth-auth0-1.4.1/lib/omniauth/strategies/auth0.rb:2:in `<top (required)>'
gitlab_1      | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/omniauth-auth0-1.4.1/lib/omniauth-auth0.rb:2:in `<top (required)>'
gitlab_1      | /var/lib/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `require'
gitlab_1      | /var/lib/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
gitlab_1      | /var/lib/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `each'
gitlab_1      | /var/lib/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `block in require'
gitlab_1      | /var/lib/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `each'
gitlab_1      | /var/lib/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `require'
gitlab_1      | /var/lib/gems/2.3.0/gems/bundler-1.16.1/lib/bundler.rb:114:in `require'
gitlab_1      | /home/git/gitlab/config/application.rb:5:in `<top (required)>'
gitlab_1      | /home/git/gitlab/Rakefile:5:in `require'
gitlab_1      | /home/git/gitlab/Rakefile:5:in `<top (required)>'
gitlab_1      | /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
gitlab_1      | (See full trace by running task with --trace)
```

What am I missing? I tried searching for the error, but couldn't find anything on it.

**Comment by solidnerd** [comment]
Hey @rohithn,
I would be nice to know which version you are currently try to setup ? I seems that something goes wrong with omniauth.
