### ISSUE TITLE
Projects::UpdatePagesService::FailedToExtractError: pages failed to extract

### ISSUE THREAD

**Issue by tomislater** [sameersbn/docker-gitlab#1693]
Here is the log:
```
2018-07-30T15:46:45.221Z 3127 TID-ou5zymo2r PagesWorker JID-1ff431c8b94b2413c5a96bf8 INFO: fail: 0.135 sec
2018-07-30T15:46:45.221Z 3127 TID-ou5zymo2r WARN: {"context":"Job raised exception","job":{"class":"PagesWorker","args":["deploy",168437],"retry":3,"queue":"pages","jid":"1ff431c8b94b2413c5a96bf8","created_at":1532965570.4581258,"enqueued_at":1532965605.0850608,"error_message":"pages failed to extract","error_class":"Projects::UpdatePagesService::FailedToExtractError","failed_at":1532965570.8267655,"retry_count":0},"jobstr":"{\"class\":\"PagesWorker\",\"args\":[\"deploy\",168437],\"retry\":3,\"queue\":\"pages\",\"jid\":\"1ff431c8b94b2413c5a96bf8\",\"created_at\":1532965570.4581258,\"enqueued_at\":1532965605.0850608,\"error_message\":\"pages failed to extract\",\"error_class\":\"Projects::UpdatePagesService::FailedToExtractError\",\"failed_at\":1532965570.8267655,\"retry_count\":0}"}
2018-07-30T15:46:45.221Z 3127 TID-ou5zymo2r WARN: Projects::UpdatePagesService::FailedToExtractError: pages failed to extract
2018-07-30T15:46:45.222Z 3127 TID-ou5zymo2r WARN: /home/git/gitlab/app/services/projects/update_pages_service.rb:99:in `block in extract_zip_archive!'
/home/git/gitlab/app/uploaders/object_storage.rb:447:in `unsafe_use_file'
/home/git/gitlab/app/uploaders/object_storage.rb:249:in `block in use_file'
/home/git/gitlab/app/uploaders/object_storage.rb:405:in `with_exclusive_lease'
/home/git/gitlab/app/uploaders/object_storage.rb:248:in `use_file'
/home/git/gitlab/app/services/projects/update_pages_service.rb:97:in `extract_zip_archive!'
/home/git/gitlab/app/services/projects/update_pages_service.rb:76:in `extract_archive!'
/home/git/gitlab/app/services/projects/update_pages_service.rb:30:in `block in execute'
/usr/lib/ruby/2.4.0/tmpdir.rb:89:in `mktmpdir'
/home/git/gitlab/app/services/projects/update_pages_service.rb:29:in `execute'
/home/git/gitlab/app/workers/pages_worker.rb:14:in `deploy'
/home/git/gitlab/app/workers/pages_worker.rb:9:in `perform'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:187:in `execute_job'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:169:in `block (2 levels) in process'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/home/git/gitlab/lib/gitlab/sidekiq_status/server_middleware.rb:5:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/git/gitlab/lib/gitlab/sidekiq_middleware/request_store_middleware.rb:6:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/git/gitlab/lib/gitlab/sidekiq_middleware/shutdown.rb:52:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/server/active_record.rb:16:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/sentry-raven-2.7.2/lib/raven/integrations/sidekiq.rb:9:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:168:in `block in process'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:139:in `block (6 levels) in dispatch'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/job_retry.rb:98:in `local'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:138:in `block (5 levels) in dispatch'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq.rb:36:in `block in <module:Sidekiq>'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:134:in `block (4 levels) in dispatch'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:199:in `stats'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:129:in `block (3 levels) in dispatch'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/job_logger.rb:8:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:128:in `block (2 levels) in dispatch'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/job_retry.rb:73:in `global'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:127:in `block in dispatch'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/logging.rb:48:in `with_context'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/logging.rb:42:in `with_job_hash_context'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:126:in `dispatch'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:167:in `process'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:85:in `process_one'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/processor.rb:73:in `run'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:16:in `watchdog'
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/sidekiq-5.1.3/lib/sidekiq/util.rb:25:in `block in safe_thread'
```

I have found that when we had changed image from `sameersbn/ubuntu:16.04.20180706` to `ubuntu:xenial-20180705` (in [this commit](https://github.com/sameersbn/docker-gitlab/commit/46e45c92da958ed5562b1bd9ee101ecbe90a0b79)), it failed to build pages.

[Here](https://gitlab.com/gitlab-org/gitlab-ee/blob/master/app/services/projects/update_pages_service.rb#L100) is the GitLab code.

How to fix it? Install `unzip` package. This package is missing in this new image. I can create PR for this.

**Comment by tomislater** [comment]
We can close this issue.
