### ISSUE TITLE
Gitlab does not start anymore

### ISSUE THREAD

**Issue by pilla** [sameersbn/docker-gitlab#1719]
Hi, 

I had an installation running OK, but after a reboot I got this when starting gitlab:

Removing stale Gitaly pid. This is most likely caused by Gitaly crashing the last time it ran.
Starting GitLab Unicorn
Starting GitLab Sidekiq
Starting GitLab Workhorse
Starting Gitaly
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/unicorn-5.1.0/lib/unicorn/configurator.rb:72:in `instance_eval': /home/git/gitlab/config/unicorn.rb:25: syntax error, unexpected '}', expecting => (SyntaxError)
r_processes {{UNICORN_WORKERS}}
                              ^
/home/git/gitlab/config/unicorn.rb:59: syntax error, unexpected '}', expecting =>
timeout {{UNICORN_TIMEOUT}}
                          ^
/home/git/gitlab/config/unicorn.rb:133: syntax error, unexpected end-of-input, expecting '}'
	from /home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/unicorn-5.1.0/lib/unicorn/configurator.rb:72:in `reload'
	from /home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/unicorn-5.1.0/lib/unicorn/configurator.rb:65:in `initialize'
	from /home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:76:in `new'
	from /home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:76:in `initialize'
	from /home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/unicorn-5.1.0/bin/unicorn_rails:209:in `new'
	from /home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/unicorn-5.1.0/bin/unicorn_rails:209:in `<top (required)>'
	from /home/git/gitlab/vendor/bundle/ruby/2.4.0/bin/unicorn_rails:23:in `load'
	from /home/git/gitlab/vendor/bundle/ruby/2.4.0/bin/unicorn_rails:23:in `<main>'
master failed to start, check stderr log for details

And it does not work anymore. 

I tried upgrading to gitlab:11.2.3 ( I was running a previous version of 11.0.xxx) and it still does not work.

**Comment by pilla** [comment]
Aditional logs from docker-compose events:

gitlab_1      | Installing configuration templates...
gitlab_1      | SSL Key, SSL Certificate and DHParam were not found.
gitlab_1      | Assuming that the container is running behind a HTTPS enabled load balancer.
gitlab_1      | Configuring gitlab...
gitlab_1      | Configuring gitlab::database
gitlab_1      | Configuring gitlab::redis
gitlab_1      | Configuring gitlab::secrets...
gitlab_1      | Configuring gitlab::sidekiq...
gitlab_1      | Configuring gitlab::gitaly...
gitlab_1      | Configuring gitlab::monitoring...
gitlab_1      | Configuring gitlab::gitlab-workhorse...
gitlab_1      | Configuring gitlab::unicorn...
gitlab_1      | Configuring gitlab::timezone...
gitlab_1      | Configuring gitlab::rack_attack...
gitlab_1      | Configuring gitlab::ci...
gitlab_1      | Configuring gitlab::artifacts...
gitlab_1      | Configuring gitlab::lfs...
gitlab_1      | Configuring gitlab::uploads...
gitlab_1      | Configuring gitlab::mattermost...
gitlab_1      | Configuring gitlab::project_features...
gitlab_1      | Configuring gitlab::smtp_settings...
gitlab_1      | Configuring gitlab::incoming_email...
gitlab_1      | Configuring gitlab::oauth...
gitlab_1      | Configuring gitlab::ldap...
gitlab_1      | Configuring gitlab::cron_jobs...
gitlab_1      | Configuring gitlab::backups...
gitlab_1      | Configuring gitlab::backups::schedule...
gitlab_1      | Configuring gitlab::registry...
gitlab_1      | Configuring gitlab::pages...
gitlab_1      | Configuring gitlab-shell...
gitlab_1      | Configuring nginx...
gitlab_1      | Configuring nginx::gitlab...
gitlab_1      | Configuring nginx::gitlab::hsts...
gitlab_1      | 2018-09-05 18:13:28,022 CRIT Supervisor running as root (no user in config file)
gitlab_1      | 2018-09-05 18:13:28,022 WARN Included extra file "/etc/supervisor/conf.d/cron.conf" during parsing
gitlab_1      | 2018-09-05 18:13:28,022 WARN Included extra file "/etc/supervisor/conf.d/gitaly.conf" during parsing
gitlab_1      | 2018-09-05 18:13:28,022 WARN Included extra file "/etc/supervisor/conf.d/gitlab-workhorse.conf" during parsing
gitlab_1      | 2018-09-05 18:13:28,022 WARN Included extra file "/etc/supervisor/conf.d/mail_room.conf" during parsing
gitlab_1      | 2018-09-05 18:13:28,022 WARN Included extra file "/etc/supervisor/conf.d/nginx.conf" during parsing
gitlab_1      | 2018-09-05 18:13:28,022 WARN Included extra file "/etc/supervisor/conf.d/sidekiq.conf" during parsing
gitlab_1      | 2018-09-05 18:13:28,022 WARN Included extra file "/etc/supervisor/conf.d/sshd.conf" during parsing
gitlab_1      | 2018-09-05 18:13:28,022 WARN Included extra file "/etc/supervisor/conf.d/unicorn.conf" during parsing
gitlab_1      | /sbin/entrypoint.sh: line 16:   602 Terminated              /usr/bin/supervisord -nc /etc/supervisor/supervisord.conf
gitlab_1      | 2018-09-05 18:13:28,194 CRIT Supervisor running as root (no user in config file)
gitlab_1      | 2018-09-05 18:13:28,194 WARN Included extra file "/etc/supervisor/conf.d/cron.conf" during parsing
gitlab_1      | 2018-09-05 18:13:28,194 WARN Included extra file "/etc/supervisor/conf.d/gitaly.conf" during parsing
gitlab_1      | 2018-09-05 18:13:28,194 WARN Included extra file "/etc/supervisor/conf.d/gitlab-workhorse.conf" during parsing
gitlab_1      | 2018-09-05 18:13:28,194 WARN Included extra file "/etc/supervisor/conf.d/mail_room.conf" during parsing
gitlab_1      | 2018-09-05 18:13:28,194 WARN Included extra file "/etc/supervisor/conf.d/nginx.conf" during parsing
gitlab_1      | 2018-09-05 18:13:28,195 WARN Included extra file "/etc/supervisor/conf.d/sidekiq.conf" during parsing
gitlab_1      | 2018-09-05 18:13:28,195 WARN Included extra file "/etc/supervisor/conf.d/sshd.conf" during parsing
gitlab_1      | 2018-09-05 18:13:28,195 WARN Included extra file "/etc/supervisor/conf.d/unicorn.conf" during parsing
gitlab_1      | 2018-09-05 18:13:28,205 INFO RPC interface 'supervisor' initialized
gitlab_1      | 2018-09-05 18:13:28,205 CRIT Server 'unix_http_server' running without any HTTP authentication checking
gitlab_1      | 2018-09-05 18:13:28,205 INFO supervisord started with pid 1
gitlab_1      | 2018-09-05 18:13:29,208 INFO spawned: 'gitaly' with pid 619
gitlab_1      | 2018-09-05 18:13:29,210 INFO spawned: 'sidekiq' with pid 620
gitlab_1      | 2018-09-05 18:13:29,212 INFO spawned: 'unicorn' with pid 621
gitlab_1      | 2018-09-05 18:13:29,215 INFO spawned: 'mail_room' with pid 622
gitlab_1      | 2018-09-05 18:13:29,218 INFO spawned: 'gitlab-workhorse' with pid 626
gitlab_1      | 2018-09-05 18:13:29,220 INFO spawned: 'cron' with pid 628
gitlab_1      | 2018-09-05 18:13:29,223 INFO spawned: 'nginx' with pid 630
gitlab_1      | 2018-09-05 18:13:29,226 INFO spawned: 'sshd' with pid 632
gitlab_1      | 2018-09-05 18:13:30,531 INFO success: gitaly entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1      | 2018-09-05 18:13:30,531 INFO success: sidekiq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1      | 2018-09-05 18:13:30,531 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1      | 2018-09-05 18:13:30,531 INFO success: mail_room entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1      | 2018-09-05 18:13:30,531 INFO success: gitlab-workhorse entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1      | 2018-09-05 18:13:30,531 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1      | 2018-09-05 18:13:30,531 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1      | 2018-09-05 18:13:30,531 INFO success: sshd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

**Comment by pilla** [comment]
Well, there was a couple of log files with wrong permissions (root) after a rebuilt, now it is working.
