### ISSUE TITLE
Upgrade from 10.1.4 to 11.3.0 problem

### ISSUE THREAD

**Issue by herrmannpchw** [sameersbn/docker-gitlab#1729]
Hi,

After the upgrade, gitlab keeps restarting and unicorn exit with status 1. The errors that I found were:

I, [2018-09-24T20:33:36.694477 #643]  INFO -- : Refreshing Gem list
Missing Rails.application.secrets.openid_connect_signing_key for production environment. The secret will be generated and stored in config/secrets.yml.
/home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:195:in `pid=': Already running on PID:643 (or pid=/home/git/gitlab/tmp/pids/unicorn.pid is stale) (ArgumentError)
	from /home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/unicorn-5.1.0/lib/unicorn/http_server.rb:127:in `start'
	from /home/git/gitlab/vendor/bundle/ruby/2.4.0/gems/unicorn-5.1.0/bin/unicorn_rails:209:in `<top (required)>'
	from /home/git/gitlab/vendor/bundle/ruby/2.4.0/bin/unicorn_rails:23:in `load'
	from /home/git/gitlab/vendor/bundle/ruby/2.4.0/bin/unicorn_rails:23:in `<main>'

=====

2018-09-24 20:34:41,430 INFO RPC interface 'supervisor' initialized
2018-09-24 20:34:41,430 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2018-09-24 20:34:41,431 INFO supervisord started with pid 616
2018-09-24 20:34:42,433 INFO spawned: 'gitaly' with pid 633
2018-09-24 20:34:42,437 INFO spawned: 'sidekiq' with pid 634
2018-09-24 20:34:42,440 INFO spawned: 'unicorn' with pid 635
2018-09-24 20:34:42,457 INFO spawned: 'gitlab-workhorse' with pid 636
2018-09-24 20:34:42,462 INFO spawned: 'cron' with pid 637
2018-09-24 20:34:42,465 INFO spawned: 'nginx' with pid 638
2018-09-24 20:34:42,489 INFO spawned: 'sshd' with pid 641
2018-09-24 20:34:43,678 INFO success: gitaly entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-09-24 20:34:43,678 INFO success: sidekiq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-09-24 20:34:43,679 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-09-24 20:34:43,679 INFO success: gitlab-workhorse entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-09-24 20:34:43,679 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-09-24 20:34:43,679 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-09-24 20:34:43,679 INFO success: sshd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-09-24 20:34:45,960 INFO exited: unicorn (exit status 1; not expected)
2018-09-24 20:34:46,963 INFO spawned: 'unicorn' with pid 669
2018-09-24 20:34:47,964 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-09-24 20:34:50,801 INFO exited: unicorn (exit status 1; not expected)
2018-09-24 20:34:51,804 INFO spawned: 'unicorn' with pid 672
2018-09-24 20:34:52,806 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-09-24 20:34:54,316 INFO exited: unicorn (exit status 1; not expected)
2018-09-24 20:34:55,319 INFO spawned: 'unicorn' with pid 749

=====

UPDATE 10/01/2018:

I thought the problem could be CPU or Memory. But this was not the case. Unicorn continues restarting...

2018-10-01 11:20:17,971 INFO success: sshd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-10-01 11:20:18,765 INFO exited: unicorn (exit status 1; not expected)
2018-10-01 11:20:20,769 INFO spawned: 'unicorn' with pid 773
2018-10-01 11:20:21,549 INFO exited: unicorn (exit status 1; not expected)
2018-10-01 11:20:24,554 INFO spawned: 'unicorn' with pid 776
2018-10-01 11:20:25,326 INFO exited: unicorn (exit status 1; not expected)
2018-10-01 11:20:26,327 INFO gave up: unicorn entered FATAL state, too many start retries too quickly

Any suggestion to resolve this issue?

**Comment by danielsss** [comment]
+1 same issue

**Comment by nsymms** [comment]
Here's my 2 cents' worth and what worked for me:

I often have this issue (unicorn respawns) when upgrading. In the past I've just deleted the storage volumes and started from scratch, restoring from my latest backup and things seem to work ok from then on.

However, with the latest upgrade to v11.9.1 I thought I'd dig in a bit more. Turns out (for me at least) the reason unicorn kept restarting was that after about 2 minutes of the container being up, there wasn't enough memory for unicorn so it died and tried to restart (repeatedly).

The reason for the memory issues was the webpack process that compiles all assets whenever the container starts. There's some memory issues with webpack and the assets inside gitlab that have been causing that compile step to take longer and use more memory. See reference here:  https://gitlab.com/gitlab-org/gitlab-ce/issues/32893.

So I tried a suggestion from the webpack issues list [here](https://github.com/webpack/webpack-dev-server/issues/1433#issuecomment-473342612) and it seemed to solve the problem. It's strange, though, because I have more than one of the sameersbn gitlab container setups running and this particular problem usually only occurs on one of them after an upgrade (and not always the same one).

For those interested, the solution I chose is not a clean one. I modified a file inside the running container. This works for me because I very rarely restart the containers anyway. I found the issue by doing a `top` from inside the gitlab container and watched the `node` process. As soon as its memory usage reached a certain point, the whole container would restart (unicorn was already restarting by this point). So here's what I did to solve the issue for me:

1. start the containers (`docker-compose up -d`)
2. log into the gitlab container (`docker-compose exec gitlab bash`)
3. install nano so we can edit files (`apt update && apt install nano`)
4. su to the git user (`su git`)
5. edit the webpack config file (`nano config/webpack.config.js`)
6. change the `chunks` options to be `'all'` for the 3 `cacheGroups` sections near line 198.
7. save and exit
8. wait for the container to reboot. You can log out and restart it manually if you need to. But if you shut things down and start again, you'll have to re-edit because your edits will be reverted.

Another solution (that I tested and worked) would be to add `--max-old-space-size=8192` to the `node` command line that the rake task uses to compile the assets. I'm not good with ruby so I couldn't find where to add that. I tested this by issuing the appropriate node webpack command with that option and it succeeded without rebooting the container. Still used lots of memory, though.
