### ISSUE TITLE
artifacts broken after upgrading to 11.5.0

### ISSUE THREAD

**Issue by jmarcos-cano** [sameersbn/docker-gitlab#1789]
my artifact dependency is broken, if job A depends on Job B's artifact it will simply fail.

I found this in the production.log:

Processing by Projects::JobsController#show as JSON
  Parameters: {"namespace_id"=>"PlayGround", "project_id"=>"dispatch", "id"=>"94011"}
Completed 500 Internal Server Error in 54ms (ActiveRecord: 9.5ms)

```
Errno::ENOENT (No such file or directory @ rb_sysopen - /home/git/data/shared/artifacts/0f/41/0f4121d0ef1df4c86854c7ebb47ae1c93de8aec8f944035eeaa6495dd71a0678/2018_11_27/94011/143404/job.log):
  app/uploaders/gitlab_uploader.rb:87:in `initialize'
  app/uploaders/gitlab_uploader.rb:87:in `open'
  app/uploaders/gitlab_uploader.rb:87:in `open'
  app/models/ci/job_artifact.rb:76:in `open'
  lib/gitlab/ci/trace.rb:70:in `block in read'
  lib/gitlab/ci/trace/stream.rb:20:in `initialize'
```

please is there any way I can downgrade?

**Comment by GJRTimmer** [comment]
@jmarcos-cano just spin up the container with the previous version and load your pre-upgrade backup.
If that's not an option, I suggest continue upgrading to latest version, maybe their is an known issue which is resolved in a higher version.
