### ISSUE TITLE
restart when update 11.8.3 to 11.9.5

### ISSUE THREAD

**Issue by fengyuchenglun** [sameersbn/docker-gitlab#1896]
when i update gitlab:11.3.3  to gitlab:11.9.5, container restart all the time;
i set GITLAB_RELATIVE_URL_ROOT=/gitlab
i find Recompiling assets (relative_url in use), this could take a while...
but unicorn.stderr.log
```
/home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:205:in `pid=': Already running on PID:695 (or pid=/home/git/gitlab/tmp/pids/unicorn.pid is stale) (ArgumentError)
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:137:in `start'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/bin/unicorn_rails:209:in `<top (required)>'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `load'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `<main>'
/home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:205:in `pid=': Already running on PID:695 (or pid=/home/git/gitlab/tmp/pids/unicorn.pid is stale) (ArgumentError)
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:137:in `start'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/bin/unicorn_rails:209:in `<top (required)>'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `load'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `<main>'
/home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:205:in `pid=': Already running on PID:695 (or pid=/home/git/gitlab/tmp/pids/unicorn.pid is stale) (ArgumentError)
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:137:in `start'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/bin/unicorn_rails:209:in `<top (required)>'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `load'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `<main>'
/home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:205:in `pid=': Already running on PID:695 (or pid=/home/git/gitlab/tmp/pids/unicorn.pid is stale) (ArgumentError)
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:137:in `start'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/bin/unicorn_rails:209:in `<top (required)>'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `load'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `<main>'
/home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:205:in `pid=': Already running on PID:695 (or pid=/home/git/gitlab/tmp/pids/unicorn.pid is stale) (ArgumentError)
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:137:in `start'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/bin/unicorn_rails:209:in `<top (required)>'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `load'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `<main>'
I, [2019-04-09T18:21:48.845032 #643]  INFO -- : Refreshing Gem list
Missing Rails.application.secrets.openid_connect_signing_key for production environment. The secret will be generated and stored in config/secrets.yml.
/home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:205:in `pid=': Already running on PID:643 (or pid=/home/git/gitlab/tmp/pids/unicorn.pid is stale) (ArgumentError)
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:137:in `start'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/bin/unicorn_rails:209:in `<top (required)>'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `load'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `<main>'
I, [2019-04-09T18:22:18.255006 #697]  INFO -- : Refreshing Gem list
I, [2019-04-09T18:22:42.645676 #643]  INFO -- : Refreshing Gem list
Missing Rails.application.secrets.openid_connect_signing_key for production environment. The secret will be generated and stored in config/secrets.yml.
/home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:205:in `pid=': Already running on PID:643 (or pid=/home/git/gitlab/tmp/pids/unicorn.pid is stale) (ArgumentError)
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:137:in `start'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/bin/unicorn_rails:209:in `<top (required)>'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `load'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `<main>'
/home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:205:in `pid=': Already running on PID:643 (or pid=/home/git/gitlab/tmp/pids/unicorn.pid is stale) (ArgumentError)
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:137:in `start'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/bin/unicorn_rails:209:in `<top (required)>'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `load'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `<main>'
/home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:205:in `pid=': Already running on PID:643 (or pid=/home/git/gitlab/tmp/pids/unicorn.pid is stale) (ArgumentError)
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:137:in `start'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/bin/unicorn_rails:209:in `<top (required)>'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `load'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `<main>'
/home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:205:in `pid=': Already running on PID:643 (or pid=/home/git/gitlab/tmp/pids/unicorn.pid is stale) (ArgumentError)
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:137:in `start'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/bin/unicorn_rails:209:in `<top (required)>'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `load'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `<main>'
/home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:205:in `pid=': Already running on PID:643 (or pid=/home/git/gitlab/tmp/pids/unicorn.pid is stale) (ArgumentError)
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:137:in `start'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/bin/unicorn_rails:209:in `<top (required)>'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `load'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `<main>'
/home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:205:in `pid=': Already running on PID:643 (or pid=/home/git/gitlab/tmp/pids/unicorn.pid is stale) (ArgumentError)
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:137:in `start'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/bin/unicorn_rails:209:in `<top (required)>'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `load'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `<main>'
/home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:205:in `pid=': Already running on PID:643 (or pid=/home/git/gitlab/tmp/pids/unicorn.pid is stale) (ArgumentError)
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:137:in `start'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/bin/unicorn_rails:209:in `<top (required)>'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `load'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `<main>'
/home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:205:in `pid=': Already running on PID:643 (or pid=/home/git/gitlab/tmp/pids/unicorn.pid is stale) (ArgumentError)
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:137:in `start'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/bin/unicorn_rails:209:in `<top (required)>'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `load'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `<main>'
/home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:205:in `pid=': Already running on PID:643 (or pid=/home/git/gitlab/tmp/pids/unicorn.pid is stale) (ArgumentError)
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:137:in `start'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/bin/unicorn_rails:209:in `<top (required)>'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `load'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `<main>'
/home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:205:in `pid=': Already running on PID:643 (or pid=/home/git/gitlab/tmp/pids/unicorn.pid is stale) (ArgumentError)
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:137:in `start'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/bin/unicorn_rails:209:in `<top (required)>'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `load'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `<main>'
I, [2019-04-09T18:23:37.773421 #698]  INFO -- : Refreshing Gem list
I, [2019-04-09T18:24:01.753535 #643]  INFO -- : Refreshing Gem list
Missing Rails.application.secrets.openid_connect_signing_key for production environment. The secret will be generated and stored in config/secrets.yml.
/home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:205:in `pid=': Already running on PID:643 (or pid=/home/git/gitlab/tmp/pids/unicorn.pid is stale) (ArgumentError)
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:137:in `start'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/bin/unicorn_rails:209:in `<top (required)>'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `load'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `<main>'
I, [2019-04-09T18:24:31.011259 #700]  INFO -- : Refreshing Gem list
I, [2019-04-09T18:24:54.375105 #643]  INFO -- : Refreshing Gem list
/home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:205:in `pid=': Already running on PID:643 (or pid=/home/git/gitlab/tmp/pids/unicorn.pid is stale) (ArgumentError)
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:137:in `start'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/bin/unicorn_rails:209:in `<top (required)>'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `load'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `<main>'
I, [2019-04-09T18:25:22.953291 #698]  INFO -- : Refreshing Gem list
I, [2019-04-09T18:25:47.038747 #643]  INFO -- : Refreshing Gem list
/home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:205:in `pid=': Already running on PID:643 (or pid=/home/git/gitlab/tmp/pids/unicorn.pid is stale) (ArgumentError)
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:137:in `start'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/bin/unicorn_rails:209:in `<top (required)>'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `load'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `<main>'
I, [2019-04-09T18:26:15.803929 #699]  INFO -- : Refreshing Gem list
I, [2019-04-09T18:26:39.836499 #643]  INFO -- : Refreshing Gem list
Missing Rails.application.secrets.openid_connect_signing_key for production environment. The secret will be generated and stored in config/secrets.yml.
/home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:205:in `pid=': Already running on PID:643 (or pid=/home/git/gitlab/tmp/pids/unicorn.pid is stale) (ArgumentError)
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:137:in `start'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/bin/unicorn_rails:209:in `<top (required)>'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `load'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `<main>'
I, [2019-04-09T18:27:08.202464 #703]  INFO -- : Refreshing Gem list
I, [2019-04-09T18:27:32.129066 #643]  INFO -- : Refreshing Gem list
/home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:205:in `pid=': Already running on PID:643 (or pid=/home/git/gitlab/tmp/pids/unicorn.pid is stale) (ArgumentError)
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:137:in `start'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/unicorn-5.4.1/bin/unicorn_rails:209:in `<top (required)>'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `load'
	from /home/git/gitlab/vendor/bundle/ruby/2.5.0/bin/unicorn_rails:23:in `<main>'
I, [2019-04-09T18:27:59.653247 #697]  INFO -- : Refreshing Gem list
I, [2019-04-09T18:28:23.987002 #643]  INFO -- : Refreshing Gem list
```

**Comment by paddy-hack** [comment]
I ran into the same issue when upgrading from 11.8.1 to 11.9.4 :unamused: .  I also see this when starting an 11.9.4 instance from scratch :rage: .  In both cases, I have `GITLAB_RELATIVE_URL_ROOT=/gitlab` in my `docker-compose.yml` file's `environment` section.  When this setting is removed, both scenarios run fine.

My `docker-compose.yml` contains a `restart: always` policy so the `gitlab` container keeps restarting in case of crashes.  The first start of a 11.9.4 container crashes after about five minutes, containers started after that crash after 2.5 to 3 minutes.  The service is mostly unusable.

I had a look at the asset compilation step in isolation with
```sh
docker-compose run --rm gitlab app:rake gitlab:assets:compile
```
That eventually results in this Webpack backtrace
```console
[...]
`rake:assets:precompile` finished in 2.863246381 seconds
/home/git/gitlab/node_modules/.bin/webpack --config /home/git/gitlab/config/webpack.config.js --bail

<--- Last few GCs --->

[671:0x2800130]    87663 ms: Mark-sweep 1026.6 (1102.0) -> 1026.5 (1103.0) MB, 642.0 / 0.0 ms  allocation failure GC in old space requested
[671:0x2800130]    88279 ms: Mark-sweep 1026.5 (1103.0) -> 1026.4 (1072.5) MB, 615.0 / 0.0 ms  last resort GC in old space requested
[671:0x2800130]    88869 ms: Mark-sweep 1026.4 (1072.5) -> 1026.4 (1072.5) MB, 590.6 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x3341cfb258b9 <JSObject>
    1: addMappingWithCode [/home/git/gitlab/node_modules/source-map/lib/source-node.js:~150] [pc=0xde49a572266](this=0x22d555d8c2f1 <JSGlobal Object>,mapping=0x3fe2e11af739 <Object map = 0x3fe15fcb85f9>,code=0x32ebf4227601 <String[4]: var >)
    2: /* anonymous */ [/home/git/gitlab/node_modules/source-map/lib/source-node.js:~86] [pc=0xde49a56fdad](this=0x19e4fd7fd419 <JSFunction SourceNode (sfi ...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x8ccf9c [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewUninitializedFixedArray(int) [node]
 6: 0xd81903 [node]
 7: v8::internal::Runtime_GrowArrayElements(int, v8::internal::Object**, v8::internal::Isolate*) [node]
 8: 0xde499c042fd
rake aborted!
Command failed with status (): [/home/git/gitlab/node_modules/.bin/webpack...]
/home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/webpack-rails-0.9.11/lib/tasks/webpack.rake:17:in `block (2 levels) in <top (required)>'
/home/git/gitlab/lib/gitlab/task_helpers.rb:18:in `invoke_and_time_task'
/home/git/gitlab/lib/tasks/gitlab/assets.rake:13:in `each'
/home/git/gitlab/lib/tasks/gitlab/assets.rake:13:in `block (3 levels) in <top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => webpack:compile
(See full trace by running task with --trace)
```
A [SO question](https://stackoverflow.com/q/38558989) about the `JavaScript heap out of memory` [suggests](https://stackoverflow.com/a/53443394) to use
```sh
export NODE_OPTIONS=--max_old_space_size=4096
```
so I retried with
```
docker-compose run --rm -e NODE_OPTIONS="--max-old-space-size=4096" gitlab app:rake gitlab:assets:compile
```
This completes without any trouble but the results do not persist in the container (because I used `--rm` but also because `docker-compose up` uses a *different* container!).

> Per [Node CLI Options documentation](https://nodejs.org/api/cli.html#cli_options), you can use either `_` or `-` to separate words in options.

Adding the `NODE_OPTIONS` setting to my `docker-compose.yml` file's `environment` section solved that issue.  After the assets have been compiled, you can disable the setting and restart the container with `docker-compose up -d`.

I have spent some time looking for a suitable value to use with `--max-old-space-size` and it seems that `1440` is close to the lower limit (tested on an 8-core machine with 16GB of memory as well as a dual core/8GB machine).  The results are not exactly reproducible (e.g. using `1436` sometimes succeeds and sometimes fails) and I will use `1536` (1.5GB) myself.  The larger value should be good enough to last me a couple of upgrades :smile: 

The following issues may be related: #1895, #1861.

**Comment by paddy-hack** [comment]
> but the results do not persist in the container (because I used `--rm` but also because `docker-compose` up uses a *different* container!).

Sorry, that was wrong.  The results persist in the `tmp` directory of the `GITLAB_DATA_DIR` (which I have volume mounted).  The reason that they are ignored is because towards the end of the [`migrate_database()` function](https://github.com/sameersbn/docker-gitlab/blob/6bd475ce294ab45c8cb522b362237840327cbb32/assets/runtime/functions#L1724), run at `app:init` and `app:start`, contains the following
```sh
  # clear cache if relative_url has changed.
  [[ -f ${GITLAB_TEMP_DIR}/GITLAB_RELATIVE_URL_ROOT ]] && CACHE_GITLAB_RELATIVE_URL_ROOT=$(cat ${GITLAB_TEMP_DIR}/GITLAB_RELATIVE_URL_ROOT)
  if [[ ! -f ${GITLAB_TEMP_DIR}/GITLAB_RELATIVE_URL_ROOT || ${GITLAB_RELATIVE_URL_ROOT} != ${CACHE_GITLAB_RELATIVE_URL_ROOT} ]]; then
    # assets need to be recompiled when GITLAB_RELATIVE_URL_ROOT is used
    if [[ -n ${GITLAB_RELATIVE_URL_ROOT} ]]; then
      echo "Recompiling assets (relative_url in use), this could take a while..."
      exec_as_git bundle exec rake gitlab:assets:compile >/dev/null 2>&1
    fi

    echo "Clearing cache..."
    exec_as_git bundle exec rake cache:clear >/dev/null 2>&1
    echo "${GITLAB_RELATIVE_URL_ROOT}" > ${GITLAB_TEMP_DIR}/GITLAB_RELATIVE_URL_ROOT
  fi
```
It's the final `echo` command that is responsible for controlling the recompilation.  Just running the `gitlab:assets:compile` `rake` task does not create this file :cry:

**Comment by paddy-hack** [comment]
I've been digging a bit further into this and found that
- [`assets/build/install.sh`](https://github.com/sameersbn/docker-gitlab/blob/6bd475ce294ab45c8cb522b362237840327cbb32/assets/build/install.sh#L171) passes the `NODE_OPTIONS` variable on the command-line with a value of `4096` (4GB).  Doing the same in [`assets/runtime/functions](https://github.com/sameersbn/docker-gitlab/blob/6bd475ce294ab45c8cb522b362237840327cbb32/assets/runtime/functions#L1789) would solve the problem so I submitted #1901 :smile:.
- GitLab CE uses a value of `3584` (3.5GB)
- the [GitLab documentation](https://docs.gitlab.com/ee/install/relative_url.html#relative-url-requirements) recommends at least 2GB
