### ISSUE TITLE
GitLab 11.10.4 restore backup failed

### ISSUE THREAD

**Issue by sugarwyc** [sameersbn/docker-gitlab#1918]
```shell
ALTER TABLE
ALTER TABLE
ALTER TABLE
[DONE]
2019-05-21 15:14:48 +0800 -- done
2019-05-21 15:14:48 +0800 -- Restoring repositories ...
rake aborted!
GRPC::Unavailable: 14:Connect Failed
/home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/grpc-1.15.0-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:31:in `check_status'
/home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/grpc-1.15.0-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:181:in `attach_status_results_and_complete_call'
/home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/grpc-1.15.0-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:377:in `request_response'
/home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/grpc-1.15.0-x86_64-linux/src/ruby/lib/grpc/generic/client_stub.rb:178:in `block in request_response'
/home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/grpc-1.15.0-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:170:in `intercept!'
/home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/grpc-1.15.0-x86_64-linux/src/ruby/lib/grpc/generic/client_stub.rb:177:in `request_response'
/home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/grpc-1.15.0-x86_64-linux/src/ruby/lib/grpc/generic/service.rb:170:in `block (3 levels) in rpc_stub_class'
/home/git/gitlab/lib/gitlab/gitaly_client.rb:158:in `call'
/home/git/gitlab/lib/gitlab/gitaly_client/storage_service.rb:21:in `delete_all_repositories'
/home/git/gitlab/lib/backup/repository.rb:46:in `block in prepare_directories'
/home/git/gitlab/lib/backup/repository.rb:45:in `each'
/home/git/gitlab/lib/backup/repository.rb:45:in `prepare_directories'
/home/git/gitlab/lib/backup/repository.rb:78:in `restore'
/home/git/gitlab/lib/tasks/gitlab/backup.rake:87:in `block (4 levels) in <top (required)>'
/home/git/gitlab/lib/tasks/gitlab/backup.rake:60:in `block (3 levels) in <top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => gitlab:backup:repo:restore
(See full trace by running task with --trace)
```

**Comment by sugarwyc** [comment]
Duplicate #1744
