### ISSUE TITLE
NoMethodError (undefined method `enforce_terms' for #<ApplicationSetting:0x0000000011a73a80>)

### ISSUE THREAD

**Issue by KrisRoofe** [sameersbn/docker-gitlab#1932]
when I access the home page I get 500, and below log

gitlab:11.11.0

```
Started GET "/" for 172.21.0.1 at 2019-06-05 17:35:52 +0530
Processing by RootController#index as HTML
Redirected to http://localhost:10080/users/sign_in
Filter chain halted as :redirect_unlogged_user rendered or redirected
Completed 302 Found in 6ms (ActiveRecord: 0.5ms)
Started GET "/users/sign_in" for 172.21.0.1 at 2019-06-05 17:35:52 +0530
Processing by SessionsController#new as HTML
Completed 500 Internal Server Error in 5ms (ActiveRecord: 0.6ms)

NoMethodError (undefined method `enforce_terms' for #<ApplicationSetting:0x0000000011a73a80>):

app/controllers/application_controller.rb:456:in `should_enforce_terms?'
lib/gitlab/middleware/multipart.rb:103:in `call'
lib/gitlab/request_profiler/middleware.rb:16:in `call'
lib/gitlab/middleware/go.rb:20:in `call'
lib/gitlab/etag_caching/middleware.rb:13:in `call'
lib/gitlab/middleware/correlation_id.rb:16:in `block in call'
lib/gitlab/middleware/correlation_id.rb:15:in `call'
lib/gitlab/middleware/read_only/controller.rb:40:in `call'
lib/gitlab/middleware/read_only.rb:18:in `call'
lib/gitlab/middleware/basic_health_check.rb:25:in `call'
lib/gitlab/request_context.rb:26:in `call'
lib/gitlab/metrics/requests_rack_middleware.rb:29:in `call'
lib/gitlab/middleware/release_env.rb:12:in `call'
```

**Comment by jamesstout** [comment]
Might be a missed rake db:migrate, or the wrong versions. 

Can you post the output from:

`bundle exec rake gitlab:env:info`

and 

`bundle exec rake gitlab:check SANITIZE=true`

(run inside the container as the git user)

Seems it was added here: https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CHANGELOG.md#L4458

In commit: https://gitlab.com/gitlab-org/gitlab-ce/commit/4019c8c256eae72665a2e4b1ffc68891f41f448c

In release 10.8.0: https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CHANGELOG.md#1080-2018-05-22
