### ISSUE TITLE
Files view leads to 500 error

### ISSUE THREAD

**Issue by almereyda** [sameersbn/docker-gitlab#201]
Everything of the Docker is working fine, but the Files view.
From `production.log`:

```
Completed 500 Internal Server Error in 65ms
ActionView::Template::Error (undefined method `[]' for nil:NilClass):
1: - tree, commit = submodule_links(submodule_item)
2: %tr{ class: "tree-item" }
3: %td.tree-item-file-name
4: %i.fa.fa-archive
app/models/repository.rb:162:in `method_missing'
app/models/repository.rb:228:in `submodule_url_for'
app/helpers/submodule_helper.rb:6:in `submodule_links'
app/views/projects/tree/_submodule_item.html.haml:1:in `_app_views_projects_tree__submodule_item_html_haml___167262730891138402_109231340'
app/helpers/tree_helper.rb:19:in `render_tree'
app/views/projects/tree/_tree.html.haml:42:in `_app_views_projects_tree__tree_html_haml___4532811778654094565_122568480'
app/views/projects/tree/show.html.haml:9:in `_app_views_projects_tree_show_html_haml___2682861148371339640_111716760'
app/controllers/projects/tree_controller.rb:13:in `show'
```

Does anyone know if this is a known GitLab error or due to the Docker?

**Comment by sameersbn** [comment]
@almereyda Were you able to resolve this issue?

**Comment by almereyda** [comment]
Thanks for asking. It seems to be repository-wise issue that sometimes
appears, sometimes doesn't. Better close this one here.
