### ISSUE TITLE
500 in admin area.

### ISSUE THREAD

**Issue by stunislaf** [sameersbn/docker-gitlab#2080]
Hi!
I have a issue with 500 error in admin area. 
In particular, a problem with the runner list page.
This issue this problem is on 12.7.0 and earlier versions.

production.log:

```
Started GET "/admin/runners" for 134.17.24.187 at 2020-01-28 21:53:45 +0300
Processing by Admin::RunnersController#index as HTML
Completed 500 Internal Server Error in 54ms (ActiveRecord: 8.1ms | Elasticsearch: 0.0ms)
ActionView::Template::Error ():
35:
36: .col-sm-6
37: .bs-callout
38: = render partial: 'ci/runner/how_to_setup_runner',
39: locals: { registration_token: Gitlab::CurrentSettings.runners_registration_token,
40: type: 'shared',
41: reset_token_url: reset_registration_token_admin_application_settings_path }
lib/gitlab/crypto_helper.rb:27:in 'aes256_gcm_decrypt'
app/models/concerns/token_authenticatable_strategies/encrypted.rb:45:in 'get_token'
app/models/concerns/token_authenticatable_strategies/base.rb:33:in 'ensure_token!'
app/models/concerns/token_authenticatable.rb:43:in 'block in add_authentication_token_field'
app/models/application_setting_implementation.rb:298:in 'runners_registration_token'
lib/gitlab/current_settings.rb:20:in 'method_missing'
app/views/admin/runners/index.html.haml:38:in '_app_views_admin_runners_index_html_haml__4072857386522077370_47215631715360'
app/controllers/application_controller.rb:121:in 'render'
lib/gitlab/session.rb:11:in 'with_session'
app/controllers/application_controller.rb:467:in 'set_session_storage'
lib/gitlab/i18n.rb:55:in 'with_locale'
lib/gitlab/i18n.rb:61:in 'with_user_locale'
app/controllers/application_controller.rb:461:in 'set_locale'
lib/gitlab/application_context.rb:18:in 'with_context'
app/controllers/application_controller.rb:453:in 'set_current_context'
lib/gitlab/error_tracking.rb:34:in 'with_context'
app/controllers/application_controller.rb:545:in 'sentry_context'
lib/gitlab/request_profiler/middleware.rb:17:in 'call'
lib/gitlab/middleware/go.rb:20:in 'call'
lib/gitlab/etag_caching/middleware.rb:13:in 'call'
lib/gitlab/middleware/multipart.rb:117:in 'call'
lib/gitlab/middleware/read_only/controller.rb:48:in 'call'
lib/gitlab/middleware/read_only.rb:18:in 'call'
lib/gitlab/middleware/basic_health_check.rb:25:in 'call'
lib/gitlab/middleware/request_context.rb:23:in 'call'
config/initializers/fix_local_cache_middleware.rb:9:in 'call'
lib/gitlab/metrics/requests_rack_middleware.rb:49:in 'call'
lib/gitlab/middleware/release_env.rb:12:in 'call'%
```

**Comment by stunislaf** [comment]
Same result i get, if try to save any setting in admin settings.

`
Started PATCH "/admin/application_settings/general" for 134.17.24.187 at 2020-01-28 22:08:04 +0300
Processing by Admin::ApplicationSettingsController#general as HTML
Parameters: {"utf8"=>"✓", "authenticity_token"=>"[FILTERED]", "application_setting"=>{"diff_max_patch_bytes"=>"102401"}}
Completed 500 Internal Server Error in 91ms (ActiveRecord: 44.5ms | Elasticsearch: 0.0ms)
OpenSSL::Cipher::CipherError ():
lib/gitlab/crypto_helper.rb:27:in 'aes256_gcm_decrypt'
app/models/concerns/token_authenticatable_strategies/encrypted.rb:45:in 'get_token'
app/models/concerns/token_authenticatable_strategies/base.rb:27:in 'ensure_token'
app/models/concerns/token_authenticatable_strategies/encrypted.rb:32:in 'ensure_token'
app/models/concerns/token_authenticatable.rb:38:in 'block in add_authentication_token_field'
app/services/application_settings/update_service.rb:40:in 'execute'
app/controllers/admin/application_settings_controller.rb:241:in 'perform_update'
app/controllers/admin/application_settings_controller.rb:31:in 'block (2 levels) in <class:ApplicationSettingsController>'
lib/gitlab/session.rb:11:in 'with_session'
app/controllers/application_controller.rb:467:in 'set_session_storage'
lib/gitlab/i18n.rb:55:in 'with_locale'
lib/gitlab/i18n.rb:61:in 'with_user_locale'
app/controllers/application_controller.rb:461:in 'set_locale'
lib/gitlab/application_context.rb:18:in 'with_context'
app/controllers/application_controller.rb:453:in 'set_current_context'
lib/gitlab/error_tracking.rb:34:in 'with_context'
app/controllers/application_controller.rb:545:in 'sentry_context'
lib/gitlab/request_profiler/middleware.rb:17:in 'call'
lib/gitlab/middleware/go.rb:20:in 'call'
lib/gitlab/etag_caching/middleware.rb:13:in 'call'
lib/gitlab/middleware/multipart.rb:117:in 'call'
lib/gitlab/middleware/read_only/controller.rb:48:in 'call'
lib/gitlab/middleware/read_only.rb:18:in 'call'
lib/gitlab/middleware/basic_health_check.rb:25:in 'call'
lib/gitlab/middleware/request_context.rb:23:in 'call'
config/initializers/fix_local_cache_middleware.rb:9:in 'call'
lib/gitlab/metrics/requests_rack_middleware.rb:49:in 'call'
lib/gitlab/middleware/release_env.rb:12:in 'call'
`

**Comment by stunislaf** [comment]
compose file

`
version: '2'
services:
  redis:
    restart: always
    image: sameersbn/redis:4.0.9-2
    container_name: 'gitlab_redis'
    command:
      - --loglevel warning
    volumes:
      - redis-data:/var/lib/redis:Z
  postgresql:
    restart: always
    image: sameersbn/postgresql:10-2
    container_name: 'gitlab_postgresql'
    volumes:
      - postgresql-data:/var/lib/postgresql:Z
    environment:
      - DB_USER##################
      - DB_PASS=##################
      - DB_NAME=##################
      - DB_EXTENSION=pg_trgm
  nginx:
    image: umputun/nginx-le:latest
    hostname: nginx
    restart: always
    container_name: nginx
    links:
      - gitlab
    volumes:
        - ./etc/ssl:/etc/nginx/ssl
        - ./etc/gitlab.conf:/etc/nginx/service.conf
    ports:
        - "80:80"
        - "443:443"
    environment:
        - TZ=Europe/Minsk
        - LETSENCRYPT=true
        - LE_EMAIL=##################
        - LE_FQDN=##################
  gitlab:
    restart: always
    image: sameersbn/gitlab
    container_name: 'gitlab'
    depends_on:
      - redis
      - postgresql
    ports:
      - "2224:22"
    volumes:
      - gitlab-data:/home/git/data:Z
    environment:
      - DEBUG=false
      - DB_ADAPTER=##################
      - DB_HOST=##################
      - DB_PORT=5432
      - DB_USER=##################
      - DB_PASS=##################
      - DB_NAME=##################
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TZ=Europe/Minsk
      - GITLAB_TIMEZONE=Europe/Minsk
      - GITLAB_HTTPS=true
      - SSL_SELF_SIGNED=false
      - GITLAB_HOST=##################
      - GITLAB_PORT=443
      - GITLAB_SSH_PORT=2224
      - GITLAB_SECRETS_DB_KEY_BASE=##################
      - GITLAB_SECRETS_SECRET_KEY_BASE=##################
      - GITLAB_SECRETS_OTP_KEY_BASE=##################
volumes:
  ##################
  ##################
  ##################

`

**Comment by stunislaf** [comment]
I found a solution to the problem [here](https://docs.gitlab.com/ee/raketasks/backup_restore.html#reset-cicd-variables)
