### ISSUE TITLE
When trying to restart docker images unicorn and sidekiq goes restart loop

### ISSUE THREAD

**Issue by jtiai** [sameersbn/docker-gitlab#2089]
When trying to restart containers (by using docker-compose.yml) unicorn and sidekiq enters in
infinite restart loop.

```
gitlab_1      | 2020-02-21 09:42:57,166 INFO success: sidekiq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1      | 2020-02-21 09:43:15,447 INFO exited: unicorn (exit status 1; not expected)
gitlab_1      | 2020-02-21 09:43:16,363 INFO spawned: 'unicorn' with pid 1233
gitlab_1      | 2020-02-21 09:43:16,406 INFO exited: sidekiq (exit status 1; not expected)
gitlab_1      | 2020-02-21 09:43:17,407 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
gitlab_1      | 2020-02-21 09:43:17,409 INFO spawned: 'sidekiq' with pid 1234
gitlab_1      | 2020-02-21 09:43:18,431 INFO success: sidekiq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

From the logs I could find the following:

```
I, [2020-02-21T09:40:08.284875 #1126]  INFO -- : Refreshing Gem list
/usr/lib/ruby/2.6.0/psych.rb:456:in `parse': (<unknown>): did not find expected key while parsing a block mapping at line 286 column 9 (Psych::SyntaxError)
        from /usr/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
        from /usr/lib/ruby/2.6.0/psych.rb:390:in `parse'
        from /usr/lib/ruby/2.6.0/psych.rb:277:in `load'
        from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:103:in `initialize'
        from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:60:in `new'
        from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:60:in `instance'
        from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:37:in `[]'
        from /home/git/gitlab/config/initializers/1_settings.rb:6:in `<top (required)>'
        from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'
        from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `block in load'
        from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
        from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'
        from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/engine.rb:657:in `block in load_config_initializer'
        from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:170:in `instrument'
        from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/engine.rb:656:in `load_config_initializer'
        from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>'
        from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/engine.rb:613:in `each'
        from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/engine.rb:613:in `block in <class:Engine>'
        from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `instance_exec'
        from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/initializable.rb:32:in `run'
        from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /usr/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
        from /usr/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /usr/lib/ruby/2.6.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
        from /usr/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /usr/lib/ruby/2.6.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
        from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/initializable.rb:50:in `each'
        from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/initializable.rb:50:in `tsort_each_child'
        from /usr/lib/ruby/2.6.0/tsort.rb:415:in `call'
        from /usr/lib/ruby/2.6.0/tsort.rb:415:in `each_strongly_connected_component_from'
        from /usr/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /usr/lib/ruby/2.6.0/tsort.rb:347:in `each'
        from /usr/lib/ruby/2.6.0/tsort.rb:347:in `call'
        from /usr/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
        from /usr/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
        from /usr/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
        from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/initializable.rb:60:in `run_initializers'
        from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-5.2.3/lib/rails/application.rb:361:in `initialize!'
        from /home/git/gitlab/config/environment.rb:6:in `<top (required)>'
        from config.ru:19:in `require'
        from config.ru:19:in `block in <main>'
        from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/builder.rb:55:in `instance_eval'
        from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/rack-2.0.7/lib/rack/builder.rb:55:in `initialize'
        from config.ru:1:in `new'
        from config.ru:1:in `<main>'
        from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/unicorn-5.4.1/lib/unicorn.rb:56:in `eval'
        from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/unicorn-5.4.1/lib/unicorn.rb:56:in `block in builder'
        from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/unicorn-5.4.1/bin/unicorn_rails:139:in `block in rails_builder'
        from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:795:in `build_app!'
        from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/unicorn-5.4.1/lib/unicorn/http_server.rb:139:in `start'
        from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/unicorn-5.4.1/bin/unicorn_rails:209:in `<top (required)>'
        from /home/git/gitlab/vendor/bundle/ruby/2.6.0/bin/unicorn_rails:23:in `load'
        from /home/git/gitlab/vendor/bundle/ruby/2.6.0/bin/unicorn_rails:23:in `<main>'
```

Using docker image:
    image: sameersbn/gitlab:12.7.6

**Comment by Laul0** [comment]
See #2085

**Comment by jtiai** [comment]
Looks like setting:
GITLAB_UNICORN_MEMORY_MAX=629145600
Fixed crashing issues.
