### ISSUE TITLE
ActionView::Template::Error: failed to inflate loose object

### ISSUE THREAD

**Issue by spiderqn** [sameersbn/docker-gitlab#2105]
/var/log/gitlab/gitlab-rails/production_json.log <==
{"method":"GET","path":"/","format":"html","controller":"RootController","action":"index","status":500,"error":"ActionView::Template::Error: failed to inflate loose object","duration":71.58,"view":0.0,"db":5.78,"time":"2020-03-24T06:29:38.882Z","params":{},"remote_ip":"10.18.25.146","user_id":,"username":""}

==> /var/log/gitlab/gitlab-rails/production.log <==

ActionView::Template::Error (failed to inflate loose object):
    17:           - if project.creator && use_creator_avatar
    18:             = image_tag avatar_icon(project.creator.email, 40), class: "avatar s40", alt:''
    19:           - else
    20:             = project_icon(project, alt: '', class: 'avatar project-avatar s40')
    21:     .project-details
    22:       %h3.prepend-top-0.append-bottom-0
    23:         = link_to project_path(project), class: dom_class(project) do
  lib/gitlab/git/repository.rb:930:in `target'
  lib/gitlab/git/repository.rb:930:in `block in branches_filter'
  lib/gitlab/git/repository.rb:928:in `each'
  lib/gitlab/git/repository.rb:928:in `each'
  lib/gitlab/git/repository.rb:928:in `map'
  lib/gitlab/git/repository.rb:928:in `branches_filter'
  lib/gitlab/git/repository.rb:122:in `block in branches'
  lib/gitlab/gitaly_client.rb:115:in `block in migrate'
  lib/gitlab/metrics/influx_db.rb:92:in `measure'
  lib/gitlab/gitaly_client.rb:114:in `migrate'
  lib/gitlab/git/repository.rb:917:in `gitaly_migrate'
  lib/gitlab/git/repository.rb:118:in `branches'
  lib/gitlab/git/repository.rb:111:in `block in branch_names'
  lib/gitlab/gitaly_client.rb:115:in `block in migrate'
  lib/gitlab/metrics/influx_db.rb:92:in `measure'
  lib/gitlab/gitaly_client.rb:114:in `migrate'
  lib/gitlab/git/repository.rb:917:in `gitaly_migrate'
  lib/gitlab/git/repository.rb:107:in `branch_names'
  lib/gitlab/git/repository.rb:281:in `discover_default_branch'
  lib/gitlab/git/repository.rb:87:in `block in root_ref'
  lib/gitlab/gitaly_client.rb:115:in `block in migrate'
  lib/gitlab/metrics/influx_db.rb:92:in `measure'
  lib/gitlab/gitaly_client.rb:114:in `migrate'
  lib/gitlab/git/repository.rb:917:in `gitaly_migrate'
  lib/gitlab/git/repository.rb:83:in `root_ref'
  app/models/repository.rb:479:in `root_ref'
  app/models/repository.rb:63:in `block (2 levels) in cache_method'
  lib/repository_cache.rb:20:in `fetch'
  app/models/repository.rb:1085:in `cache_method_output'
  app/models/repository.rb:62:in `block in cache_method'
  app/models/repository.rb:598:in `head_commit'
  app/models/repository.rb:609:in `tree'
  app/models/repository.rb:1101:in `file_on_head'
  app/models/repository.rb:536:in `avatar'
  app/models/repository.rb:63:in `block (2 levels) in cache_method'
  lib/repository_cache.rb:20:in `fetch'
  app/models/repository.rb:1085:in `cache_method_output'
  app/models/repository.rb:62:in `block in cache_method'
  app/models/project.rb:908:in `avatar_in_git'
  app/models/project.rb:914:in `avatar_url'
  app/helpers/application_helper.rb:43:in `project_icon'
  app/views/shared/projects/_project.html.haml:20:in `block (2 levels) in _app_views_shared_projects__project_html_haml___3380901616528475470_70075450445960'
  app/views/shared/projects/_project.html.haml:16:in `block in _app_views_shared_projects__project_html_haml___3380901616528475470_70075450445960'
  app/views/shared/projects/_project.html.haml:13:in `_app_views_shared_projects__project_html_haml___3380901616528475470_70075450445960'
  app/views/shared/projects/_list.html.haml:17:in `block in _app_views_shared_projects__list_html_haml___2303246079902970044_70075452777120'
  app/views/shared/projects/_list.html.haml:15:in `_app_views_shared_projects__list_html_haml___2303246079902970044_70075452777120'
  app/views/dashboard/projects/_projects.html.haml:1:in `_app_views_dashboard_projects__projects_html_haml___2598724004961472965_70075452453540'
  app/views/dashboard/projects/index.html.haml:15:in `_app_views_dashboard_projects_index_html_haml__685893027682825794_70075461927020'
  app/controllers/dashboard/projects_controller.rb:10:in `index'
  app/controllers/root_controller.rb:16:in `index'
  lib/gitlab/i18n.rb:46:in `with_locale'
  lib/gitlab/i18n.rb:52:in `with_user_locale'
  app/controllers/application_controller.rb:326:in `set_locale'
  lib/gitlab/middleware/multipart.rb:93:in `call'
  lib/gitlab/request_profiler/middleware.rb:14:in `call'
  lib/gitlab/middleware/go.rb:17:in `call'
  lib/gitlab/etag_caching/middleware.rb:11:in `call'
  lib/gitlab/request_context.rb:18:in `call'
  lib/gitlab/metrics/requests_rack_middleware.rb:27:in `call'

**Comment by Chingzio** [comment]
我遇到了相同的问题，请问您解决了吗
