### ISSUE TITLE
Upgrade to 12.10.4 does not work

### ISSUE THREAD

**Issue by paolomainardi** [sameersbn/docker-gitlab#2146]
Tried to upgrade from the latest 12.9 and it doesn't work:

```
▶ k logs -f gitlab-7748b9c767-cg95f
Loading /etc/docker-gitlab/runtime/env-defaults
Initializing logdir...
Initializing datadir...
Installing configuration templates...
SSL Key, SSL Certificate and DHParam were not found.
Assuming that the container is running behind a HTTPS enabled load balancer.
Configuring gitlab...
Configuring gitlab::database
Configuring gitlab::redis
Configuring gitlab::secrets...
Configuring gitlab::sidekiq...
Configuring gitlab::gitaly...
Configuring gitlab::monitoring...
Configuring gitlab::gitlab-workhorse...
Configuring gitlab::puma...
Configuring gitlab::timezone...
Configuring gitlab::rack_attack...
Configuring gitlab::ci...
Configuring gitlab::artifacts...
Configuring gitlab::lfs...
Configuring gitlab::uploads...
Configuring gitlab::mattermost...
Configuring gitlab::project_features...
Configuring gitlab::smtp_settings...
Configuring gitlab::oauth...
Configuring gitlab::ldap...
Configuring gitlab::cron_jobs...
Configuring gitlab::backups...
Configuring gitlab::backups::schedule...
Configuring gitlab::backups::gcs...
Configuring gitlab::registry...
Configuring gitlab::pages...
Configuring gitlab::sentry...
Configuring gitlab-shell...
Configuring nginx...
Configuring nginx::gitlab...
Configuring nginx::gitlab::hsts...
Migrating database...
2020-05-17 17:06:08,504 CRIT Supervisor running as root (no user in config file)
2020-05-17 17:06:08,504 INFO Included extra file "/etc/supervisor/conf.d/cron.conf" during parsing
2020-05-17 17:06:08,504 INFO Included extra file "/etc/supervisor/conf.d/gitaly.conf" during parsing
2020-05-17 17:06:08,504 INFO Included extra file "/etc/supervisor/conf.d/gitlab-workhorse.conf" during parsing
2020-05-17 17:06:08,504 INFO Included extra file "/etc/supervisor/conf.d/groups.conf" during parsing
2020-05-17 17:06:08,504 INFO Included extra file "/etc/supervisor/conf.d/mail_room.conf" during parsing
2020-05-17 17:06:08,504 INFO Included extra file "/etc/supervisor/conf.d/nginx.conf" during parsing
2020-05-17 17:06:08,504 INFO Included extra file "/etc/supervisor/conf.d/puma.conf" during parsing
2020-05-17 17:06:08,504 INFO Included extra file "/etc/supervisor/conf.d/sidekiq.conf" during parsing
2020-05-17 17:06:08,504 INFO Included extra file "/etc/supervisor/conf.d/sshd.conf" during parsing
2020-05-17 17:06:08,514 INFO RPC interface 'supervisor' initialized
2020-05-17 17:06:08,514 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2020-05-17 17:06:08,515 INFO supervisord started with pid 656
2020-05-17 17:06:09,517 INFO spawned: 'gitaly' with pid 677
2020-05-17 17:06:09,522 INFO spawned: 'puma' with pid 678
2020-05-17 17:06:09,527 INFO spawned: 'gitlab-workhorse' with pid 679
2020-05-17 17:06:09,535 INFO spawned: 'sidekiq' with pid 685
2020-05-17 17:06:09,545 INFO spawned: 'nginx' with pid 686
2020-05-17 17:06:09,553 INFO spawned: 'sshd' with pid 688
2020-05-17 17:06:09,579 INFO spawned: 'cron' with pid 689
2020-05-17 17:06:10,994 INFO success: gitaly entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-05-17 17:06:10,994 INFO success: puma entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-05-17 17:06:10,994 INFO success: gitlab-workhorse entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-05-17 17:06:10,994 INFO success: sidekiq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-05-17 17:06:10,994 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-05-17 17:06:10,994 INFO success: sshd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-05-17 17:06:10,994 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-05-17 17:06:36,402 INFO exited: puma (exit status 1; not expected)
2020-05-17 17:06:36,443 INFO spawned: 'puma' with pid 800
2020-05-17 17:06:36,445 INFO exited: sidekiq (exit status 1; not expected)
2020-05-17 17:06:37,446 INFO success: puma entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-05-17 17:06:37,449 INFO spawned: 'sidekiq' with pid 804
rake aborted!
Psych::SyntaxError: (<unknown>): did not find expected key while parsing a block mapping at line 893 column 5
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:103:in `initialize'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:60:in `new'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:60:in `instance'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:37:in `[]'
/home/git/gitlab/config/initializers/1_settings.rb:6:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.2/lib/active_support/dependencies.rb:319:in `load'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.2/lib/active_support/dependencies.rb:319:in `block in load'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.2/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.2/lib/active_support/dependencies.rb:319:in `load'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/engine.rb:667:in `block in load_config_initializer'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.2/lib/active_support/notifications.rb:182:in `instrument'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/engine.rb:666:in `load_config_initializer'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/engine.rb:624:in `block (2 levels) in <class:Engine>'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/engine.rb:623:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/engine.rb:623:in `block in <class:Engine>'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/initializable.rb:32:in `instance_exec'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/initializable.rb:32:in `run'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/initializable.rb:61:in `block in run_initializers'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/initializable.rb:50:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/initializable.rb:50:in `tsort_each_child'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/initializable.rb:60:in `run_initializers'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/application.rb:363:in `initialize!'
/home/git/gitlab/config/environment.rb:5:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.2/lib/active_support/dependencies.rb:325:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.2/lib/active_support/dependencies.rb:325:in `block in require'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.2/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.2/lib/active_support/dependencies.rb:325:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/application.rb:339:in `require_environment!'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/application.rb:515:in `block in run_tasks_blocks'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:migrate => db:load_config => environment
(See full trace by running task with --trace)
```

Any ideas @solidnerd ? Could be this one ?  https://github.com/sameersbn/docker-gitlab/commit/4b4cbb8f98027b16cc8e65911eb3446360de5679

**Comment by solidnerd** [comment]
Hey @paolomainardi,
this should be fixed with https://github.com/sameersbn/docker-gitlab/commit/4b4cbb8f98027b16cc8e65911eb3446360de5679 .
I didn't triggered the release already so there is no tag for `12.10.6`. You can try it with the latest tag and set in the deployment `imagePullPolicy: Always` .  I tested the latest branch with one of my instances and it worked for me.

**Comment by solidnerd** [comment]
Otherwise take `solidnerd/gitlab:12.10.6`

**Comment by paolomainardi** [comment]
Ok thanks @solidnerd are you planning to trigger the new release here as well ?

**Comment by solidnerd** [comment]
Yep see my post in #2145

**Comment by paolomainardi** [comment]
Great, thanks!

**Comment by solidnerd** [comment]
You are welcome !

**Comment by solidnerd** [comment]
@paolomainardi  The build will take ~ 1 hour afterwards it will be available on quay or docker hub
