### ISSUE TITLE
rack_attack.rb file overwrite a system file

### ISSUE THREAD

**Issue by achretien** [sameersbn/docker-gitlab#2202]
Since https://gitlab.com/gitlab-org/omnibus-gitlab/-/merge_requests/4149/diffs

The rake_attack.rb file is removed from omnibus and rake_attack_new.rb file has been renamed to rake_attack.rb in gitlab code source.

The current setup erase the code source file at runtime.

The tricks should be removed (the config as been moved to Admin config)

**Comment by azbmb** [comment]
I received this error when starting up the GitLab container in the `application.log`
```
Started GET "/-/liveness" for 127.0.0.1 at 2020-09-21 16:22:15 +0000

NoMethodError (undefined method `web_request?' for #<Rack::Attack::Request:0x000055fea1e2a798>):

ee/lib/ee/gitlab/rack/attack.rb:5:in `block in <module:Attack>'
lib/gitlab/middleware/read_only/controller.rb:51:in `call'
lib/gitlab/middleware/read_only.rb:18:in `call'
lib/gitlab/middleware/same_site_cookies.rb:27:in `call'
lib/gitlab/middleware/basic_health_check.rb:25:in `call'
lib/gitlab/middleware/handle_ip_spoof_attack_error.rb:25:in `call'
lib/gitlab/middleware/request_context.rb:23:in `call'
config/initializers/fix_local_cache_middleware.rb:9:in `call'
lib/gitlab/metrics/requests_rack_middleware.rb:60:in `call'
lib/gitlab/middleware/release_env.rb:12:in `call'
```

I've temporarily fixed/hacked it in my environment, so GitLab can at least run, by commenting the following lines in `assets/runtime/functions` and then rebuilding the image. 

```
diff --git a/assets/runtime/functions b/assets/runtime/functions
index a4e0ef4..a038846 100644
--- a/assets/runtime/functions
+++ b/assets/runtime/functions
@@ -17,7 +17,7 @@ GITLAB_CONFIG="${GITLAB_INSTALL_DIR}/config/gitlab.yml"
 GITLAB_DATABASE_CONFIG="${GITLAB_INSTALL_DIR}/config/database.yml"
 GITLAB_PUMA_CONFIG="${GITLAB_INSTALL_DIR}/config/puma.rb"
 GITLAB_RELATIVE_URL_CONFIG="${GITLAB_INSTALL_DIR}/config/initializers/relative_url.rb"
-GITLAB_RACK_ATTACK_CONFIG="${GITLAB_INSTALL_DIR}/config/initializers/rack_attack.rb"
+#GITLAB_RACK_ATTACK_CONFIG="${GITLAB_INSTALL_DIR}/config/initializers/rack_attack.rb"
 GITLAB_SMTP_CONFIG="${GITLAB_INSTALL_DIR}/config/initializers/smtp_settings.rb"
 GITLAB_RESQUE_CONFIG="${GITLAB_INSTALL_DIR}/config/resque.yml"
 GITLAB_SECRETS_CONFIG="${GITLAB_INSTALL_DIR}/config/secrets.yml"
@@ -1533,7 +1533,7 @@ install_configuration_templates() {
   install_template ${GITLAB_USER}: gitlabhq/gitlab.yml ${GITLAB_CONFIG} 0640
   install_template ${GITLAB_USER}: gitlabhq/database.yml ${GITLAB_DATABASE_CONFIG} 0640
   install_template ${GITLAB_USER}: gitlabhq/puma.rb ${GITLAB_PUMA_CONFIG} 0644
-  install_template ${GITLAB_USER}: gitlabhq/rack_attack.rb ${GITLAB_RACK_ATTACK_CONFIG} 0644
+  #install_template ${GITLAB_USER}: gitlabhq/rack_attack.rb ${GITLAB_RACK_ATTACK_CONFIG} 0644
   install_template ${GITLAB_USER}: gitlabhq/resque.yml ${GITLAB_RESQUE_CONFIG} 0640
   install_template ${GITLAB_USER}: gitlabhq/secrets.yml ${GITLAB_SECRETS_CONFIG} 0600
   install_template ${GITLAB_USER}: gitlab-shell/config.yml ${GITLAB_SHELL_CONFIG} 0640
```

I'm mostly posting this in case anyone else encounters the same issue I had where GitLab wouldn't start and would just return the 500 error page.
