### ISSUE TITLE
Can't start version `12.10.6-1`

### ISSUE THREAD

**Issue by n11sh1** [sameersbn/docker-gitlab#2207]
After upgrading from 12.4.0 to 12.10.6, I encountered this issue #2147 .
So I tried to upgrade from 12.10.6 to 12.10.6-1, then it couldn't start: error 502.

# docker-compose.yml
```yaml
version: '2'

services:
  redis:
    restart: always
    image: sameersbn/redis:4.0.9-2
    command:
    - --loglevel warning
    volumes:
    - /home/docker/gitlab/redis:/var/lib/redis:Z

  postgresql:
    restart: always
    image: sameersbn/postgresql:10-2
    volumes:
    - /home/docker/gitlab/postgresql:/var/lib/postgresql:Z
    environment:
      ...

  gitlab:
    restart: always
    image: sameersbn/gitlab:12.10.6-1
    depends_on:
    - redis
    - postgresql
    ports:
    - "80:80"
    - "443:443"
    - "10022:22"
    volumes:
    - /home/docker/gitlab/gitlab:/home/git/data:Z
    - /home/docker/gitlab/registry/certs:/certs
    environment:
      ...
```

# Logs
**/var/log/gitlab/gitlab/gitlab-workhorse.log** 
```
time="2020-08-12T21:19:06+09:00" level=error msg=error correlation_id=iLxHp2AnHg4 duration_ms=0 error="badgateway: failed to receive response: dial unix /home/git/gitlab/tmp/sockets/gitlab.socket: connect: no such file or directory" method=GET uri=/
gitlab.sample.com 122.216.25.178 - - [2020/08/12:21:19:06 +0900] "GET / HTTP/1.1" 502 2940 "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36" 0
time="2020-08-12T21:19:06+09:00" level=error msg=error correlation_id=Gz78OVyg0i6 duration_ms=0 error="badgateway: failed to receive response: dial unix /home/git/gitlab/tmp/sockets/gitlab.socket: connect: no such file or directory" method=GET uri=/favicon.ico
gitlab.sample.com 122.216.25.178 - - [2020/08/12:21:19:06 +0900] "GET /favicon.ico HTTP/1.1" 502 2940 "https://gitlab.sample.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36" 0
```

**/home/git/gitlab/tmp/sockets/**
```
total 0
drwxr-xr-x 3 git git 35 May 17 21:58 .
drwxr-xr-x 6 git git 91 May 17 22:10 ..
-rw-r--r-- 1 git git  0 May 17 21:58 .gitkeep
drwxr-xr-x 2 git git 41 Aug 13 00:15 private
```

**/var/log/gitlab/supervisor/supervisord.log**
```
2020-08-13 00:15:30,758 INFO supervisord started with pid 1
2020-08-13 00:15:31,760 INFO spawned: 'gitaly' with pid 1932
2020-08-13 00:15:31,762 INFO spawned: 'puma' with pid 1933
2020-08-13 00:15:31,764 INFO spawned: 'gitlab-workhorse' with pid 1934
2020-08-13 00:15:31,767 INFO spawned: 'sidekiq' with pid 1935
2020-08-13 00:15:31,769 INFO spawned: 'gitlab-pages' with pid 1936
2020-08-13 00:15:31,772 INFO spawned: 'nginx' with pid 1937
2020-08-13 00:15:31,774 INFO spawned: 'sshd' with pid 1938
2020-08-13 00:15:31,776 INFO spawned: 'cron' with pid 1939
2020-08-13 00:15:32,789 INFO success: gitaly entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-08-13 00:15:32,789 INFO success: puma entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-08-13 00:15:32,789 INFO success: gitlab-workhorse entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-08-13 00:15:32,789 INFO success: sidekiq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-08-13 00:15:32,789 INFO success: gitlab-pages entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-08-13 00:15:32,789 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-08-13 00:15:32,789 INFO success: sshd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-08-13 00:15:32,789 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-08-13 00:15:42,528 INFO exited: puma (exit status 1; not expected)
2020-08-13 00:15:42,547 INFO spawned: 'puma' with pid 2061
2020-08-13 00:15:42,547 INFO exited: sidekiq (exit status 1; not expected)
2020-08-13 00:15:43,259 INFO spawned: 'sidekiq' with pid 2062
2020-08-13 00:15:43,895 INFO success: puma entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-08-13 00:15:45,231 INFO success: sidekiq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-08-13 00:15:50,305 INFO exited: puma (exit status 1; not expected)
2020-08-13 00:15:50,914 INFO spawned: 'puma' with pid 2074
2020-08-13 00:15:50,936 INFO exited: sidekiq (exit status 1; not expected)
2020-08-13 00:15:51,539 INFO spawned: 'sidekiq' with pid 2075
```

**/var/log/gitlab/supervisor/puma.log**
```
/usr/lib/ruby/2.6.0/psych.rb:456:in `parse': (<unknown>): did not find expected ',' or ']' while parsing a flow sequence at line 974 column 21 (Psych::SyntaxError)
	from /usr/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
	from /usr/lib/ruby/2.6.0/psych.rb:390:in `parse'
	from /usr/lib/ruby/2.6.0/psych.rb:277:in `load'
	from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:103:in `initialize'
	from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:60:in `new'
	from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:60:in `instance'
	from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:37:in `[]'
	from /home/git/gitlab/config/initializers/1_settings.rb:6:in `<top (required)>'
	from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.2/lib/active_support/dependencies.rb:319:in `load'
	from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.2/lib/active_support/dependencies.rb:319:in `block in load'
	from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.2/lib/active_support/dependencies.rb:291:in `load_dependency'
	from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.2/lib/active_support/dependencies.rb:319:in `load'
	from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/engine.rb:667:in `block in load_config_initializer'
	from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.2/lib/active_support/notifications.rb:182:in `instrument'
	from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/engine.rb:666:in `load_config_initializer'
	from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/engine.rb:624:in `block (2 levels) in <class:Engine>'
	from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/engine.rb:623:in `each'
	from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/engine.rb:623:in `block in <class:Engine>'
	from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/initializable.rb:32:in `instance_exec'
	from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/initializable.rb:32:in `run'
	from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /usr/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
	from /usr/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/lib/ruby/2.6.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /usr/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/lib/ruby/2.6.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/initializable.rb:50:in `each'
	from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/initializable.rb:50:in `tsort_each_child'
	from /usr/lib/ruby/2.6.0/tsort.rb:415:in `call'
	from /usr/lib/ruby/2.6.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /usr/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/lib/ruby/2.6.0/tsort.rb:347:in `each'
	from /usr/lib/ruby/2.6.0/tsort.rb:347:in `call'
	from /usr/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
	from /usr/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
	from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/initializable.rb:60:in `run_initializers'
	from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/application.rb:363:in `initialize!'
	from /home/git/gitlab/config/environment.rb:5:in `<top (required)>'
	from config.ru:18:in `require'
	from config.ru:18:in `block in <main>'
	from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/rack-2.0.9/lib/rack/builder.rb:55:in `instance_eval'
	from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/rack-2.0.9/lib/rack/builder.rb:55:in `initialize'
	from config.ru:in `new'
	from config.ru:in `<main>'
	from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/rack-2.0.9/lib/rack/builder.rb:49:in `eval'
	from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/rack-2.0.9/lib/rack/builder.rb:49:in `new_from_string'
	from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/rack-2.0.9/lib/rack/builder.rb:40:in `parse_file'
	from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/gitlab-puma-4.3.3.gitlab.2/lib/puma/configuration.rb:321:in `load_rackup'
	from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/gitlab-puma-4.3.3.gitlab.2/lib/puma/configuration.rb:246:in `app'
	from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/gitlab-puma-4.3.3.gitlab.2/lib/puma/runner.rb:155:in `load_and_bind'
	from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/gitlab-puma-4.3.3.gitlab.2/lib/puma/cluster.rb:413:in `run'
	from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/gitlab-puma-4.3.3.gitlab.2/lib/puma/launcher.rb:172:in `run'
	from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/gitlab-puma-4.3.3.gitlab.2/lib/puma/cli.rb:80:in `run'
	from /home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/gitlab-puma-4.3.3.gitlab.2/bin/puma:10:in `<top (required)>'
	from /home/git/gitlab/vendor/bundle/ruby/2.6.0/bin/puma:23:in `load'
	from /home/git/gitlab/vendor/bundle/ruby/2.6.0/bin/puma:23:in `<main>'
{"timestamp":"2020-08-12T15:11:46.288Z","pid":2417,"message":"Puma starting in cluster mode..."}
{"timestamp":"2020-08-12T15:11:46.288Z","pid":2417,"message":"* Version 4.3.3.gitlab.2 (ruby 2.6.5-p114), codename: Mysterious Traveller"}
{"timestamp":"2020-08-12T15:11:46.288Z","pid":2417,"message":"* Min threads: 1, max threads: 16"}
{"timestamp":"2020-08-12T15:11:46.288Z","pid":2417,"message":"* Environment: production"}
{"timestamp":"2020-08-12T15:11:46.288Z","pid":2417,"message":"* Process workers: 3"}
{"timestamp":"2020-08-12T15:11:46.288Z","pid":2417,"message":"* Preloading application"}
```

**/var/log/gitlab/supervisor/sidekiq.log**
```
(<unknown>): did not find expected ',' or ']' while parsing a flow sequence at line 974 column 21
/usr/lib/ruby/2.6.0/psych.rb:456:in `parse'
/usr/lib/ruby/2.6.0/psych.rb:456:in `parse_stream'
/usr/lib/ruby/2.6.0/psych.rb:390:in `parse'
/usr/lib/ruby/2.6.0/psych.rb:277:in `load'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:103:in `initialize'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:60:in `new'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:60:in `instance'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:37:in `[]'
/home/git/gitlab/config/initializers/1_settings.rb:6:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.2/lib/active_support/dependencies.rb:319:in `load'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.2/lib/active_support/dependencies.rb:319:in `block in load'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.2/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.2/lib/active_support/dependencies.rb:319:in `load'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/engine.rb:667:in `block in load_config_initializer'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.2/lib/active_support/notifications.rb:182:in `instrument'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/engine.rb:666:in `load_config_initializer'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/engine.rb:624:in `block (2 levels) in <class:Engine>'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/engine.rb:623:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/engine.rb:623:in `block in <class:Engine>'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/initializable.rb:32:in `instance_exec'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/initializable.rb:32:in `run'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
/usr/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/lib/ruby/2.6.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
/usr/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/lib/ruby/2.6.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/initializable.rb:50:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/initializable.rb:50:in `tsort_each_child'
/usr/lib/ruby/2.6.0/tsort.rb:415:in `call'
/usr/lib/ruby/2.6.0/tsort.rb:415:in `each_strongly_connected_component_from'
/usr/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/lib/ruby/2.6.0/tsort.rb:347:in `each'
/usr/lib/ruby/2.6.0/tsort.rb:347:in `call'
/usr/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
/usr/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/initializable.rb:60:in `run_initializers'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/railties-6.0.2/lib/rails/application.rb:363:in `initialize!'
/home/git/gitlab/config/environment.rb:5:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.2/lib/active_support/dependencies.rb:325:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.2/lib/active_support/dependencies.rb:325:in `block in require'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.2/lib/active_support/dependencies.rb:291:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.2/lib/active_support/dependencies.rb:325:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/cli.rb:288:in `boot_system'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/lib/sidekiq/cli.rb:46:in `run'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.7/bin/sidekiq:12:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/bin/sidekiq:23:in `load'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/bin/sidekiq:23:in `<main>'
WARNING: PID file creation will be removed in Sidekiq 6.0, see #4045. Please use a proper process supervisor to start and manage your services
WARNING: Logfile redirection will be removed in Sidekiq 6.0, see #4045. Sidekiq will only log to STDOUT
```

**Comment by n11sh1** [comment]
Resolved

**Comment by pierreozoux** [comment]
@n11sh1 how did you resolved?

Thanks!
