### ISSUE TITLE
ActiveRecord::ActiveRecordError: No such column: application_settings.outbound_local_requests_whitelist

### ISSUE THREAD

**Issue by MartinJLee** [sameersbn/docker-gitlab#2212]
If this isn't the right place to ask question related to upgrading from synology/gitlab(which is based on sameersbn/gitlab image), please direct me to the forum.

I'm upgrading GitLab version from synology/gitlab:11.11.8 to sameersbn/gitlab:13.2.6.
and encountered the following error during migration.
I'm have copied all existing config from old docker to the latest docker-compose file. 
here is my docker-compose file
``` yaml
version: '2.3'

services:
  redis:
    container_name: redis
    restart: always
    image: redis:5.0.9
    command:
    - --loglevel warning
    volumes:
    - /volume1/docker/gitlab/redis:/var/lib/redis:Z

  postgresql:
    container_name: postgresql
    restart: always
    image: sameersbn/postgresql:11-20200524
    volumes:
    - /volume1/docker/gitlab/postgresql:/var/lib/postgresql:Z
    environment:
    - DB_USER=gitlab_user
    - DB_PASS=gitlab_pass
    - DB_NAME=gitlab
    - DB_EXTENSION=pg_trgm,btree_gist

  registry:
    container_name: registry
    restart: always
    image: registry:2.7.1
    ports:
    - "35000:5000"
    volumes:
    - /volume1/docker/gitlab/registry/registry:/registry
    - /volume1/docker/gitlab/registry/certs:/certs
    environment:
    - REGISTRY_AUTH=token
    - REGISTRY_STORAGE_DELETE_ENABLED=true
    - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/certs/registry-auth.crt
    - REGISTRY_AUTH_TOKEN_ISSUER=gitlab-issuer
    - REGISTRY_AUTH_TOKEN_SERVICE=container_registry
    - REGISTRY_AUTH_TOKEN_REALM=https://gitlab.$DOMAIN/jwt/auth
    - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/registry
    - REGISTRY_LOG_LEVEL=info

  verdaccio:
    container_name: verdaccio
    restart: always
    image: bufferoverflow/verdaccio-gitlab:2.2.0
    ports:
    - "4873:4873"
    volumes:
    - /volume1/docker/gitlab/verdaccio/config.yaml:/verdaccio/conf/config.yaml
    - /volume1/docker/gitlab/verdaccio/storage:/verdaccio/storage
    environment:
    - NODE_VERSION=10.15.3
    - YARN_VERSION=1.13.0
    - VERDACCIO_APPDIR=/opt/verdaccio
    - VERDACCIO_USER_NAME=verdaccio
    - VERDACCIO_USER_UID=10001
    - VERDACCIO_PORT=4873
    - VERDACCIO_PROTOCOL=http
    - HOME=/opt/verdaccio

  gitlab:
    container_name: gitlab
    restart: always
    image: sameersbn/gitlab:13.2.6
    depends_on:
    - redis
    - postgresql
    - registry
    - verdaccio
    ports:
    - "30022:22"
    - "30443:443"
    - "30080:80"
    volumes:
    - /volume1/docker/gitlab/gitlab:/home/git/data:Z
    - /volume1/docker/gitlab/registry/certs:/registry_certs:Z
    healthcheck:
      test: ["CMD", "/usr/local/sbin/healthcheck"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 5m
    environment:
    - DEBUG=true

    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=gitlab_user
    - DB_PASS=gitlab_pass
    - DB_NAME=gitlab

    - REDIS_HOST=redis
    - REDIS_PORT=6379

    - GITLAB_HTTPS=true
    - SSL_SELF_SIGNED=true

    - SSL_REGISTRY_KEY_PATH=/registry_certs/registry.key
    - SSL_REGISTRY_CERT_PATH=/registry_certs/registry.crt

    - GITLAB_REGISTRY_CERT_PATH=/registry_certs/registry-auth.crt
    - GITLAB_REGISTRY_KEY_PATH=/registry_certs/registry-auth.key
    - GITLAB_REGISTRY_ISSUER=gitlab-issuer
    - GITLAB_REGISTRY_ENABLED=true
    - GITLAB_REGISTRY_HOST=registry.gitlab.$DOMAIN
    - GITLAB_REGISTRY_PORT=443
    - GITLAB_REGISTRY_API_URL=http://registry:5000

    - GITLAB_USER=git
    - GITLAB_HOME=/home/git
    - GITLAB_LOG_DIR=/var/log/gitlab
    - GITLAB_CACHE_DIR=/etc/docker-gitlab
    - RAILS_ENV=production
    - NODE_ENV=production
    - GITLAB_INSTALL_DIR=/home/git/gitlab
    - GITLAB_SHELL_INSTALL_DIR=/home/git/gitlab-shell
    - GITLAB_GITALY_INSTALL_DIR=/home/git/gitaly
    - GITLAB_DATA_DIR=/home/git/data
    - GITLAB_BUILD_DIR=/etc/docker-gitlab/build
    - GITLAB_RUNTIME_DIR=/etc/docker-gitlab/runtime
    - GITLAB_HOST=gitlab.$DOMAIN
    - GITLAB_PORT=443
    - GITLAB_SSH_PORT=22
    - GITLAB_SECRETS_DB_KEY_BASE=replaced with existing key
    - GITLAB_SECRETS_SECRET_KEY_BASE=replaced with existing key
    - GITLAB_SECRETS_OTP_KEY_BASE=replaced with existing key

    - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
    - GITLAB_NOTIFY_PUSHER=false

    - GITLAB_EMAIL=admin@$DOMAIN
    - GITLAB_EMAIL_REPLY_TO=noreply@$DOMAIN
    - GITLAB_INCOMING_EMAIL_ADDRESS=admin@DOMAIN

    - GITLAB_BACKUP_SCHEDULE=daily
    - GITLAB_BACKUP_TIME=01:00

    - SMTP_ENABLED=true
    - SMTP_DOMAIN=mail.DOMAIN
    - SMTP_HOST=mail.DOMAIN
    - SMTP_PORT=587
    - SMTP_USER=martin.lee@DOMAIN
    - SMTP_PASS=PASSWORD
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=login
```

Here is error part of GitLab log
```
+ sudo -HEu git bundle exec rake db:migrate
2020-08-23 15:01:04,095 CRIT Supervisor running as root (no user in config file)
2020-08-23 15:01:04,095 INFO Included extra file "/etc/supervisor/conf.d/cron.conf" during parsing
2020-08-23 15:01:04,095 INFO Included extra file "/etc/supervisor/conf.d/gitaly.conf" during parsing
2020-08-23 15:01:04,095 INFO Included extra file "/etc/supervisor/conf.d/gitlab-workhorse.conf" during parsing
2020-08-23 15:01:04,095 INFO Included extra file "/etc/supervisor/conf.d/groups.conf" during parsing
2020-08-23 15:01:04,095 INFO Included extra file "/etc/supervisor/conf.d/mail_room.conf" during parsing
2020-08-23 15:01:04,095 INFO Included extra file "/etc/supervisor/conf.d/nginx.conf" during parsing
2020-08-23 15:01:04,095 INFO Included extra file "/etc/supervisor/conf.d/puma.conf" during parsing
2020-08-23 15:01:04,095 INFO Included extra file "/etc/supervisor/conf.d/sidekiq.conf" during parsing
2020-08-23 15:01:04,096 INFO Included extra file "/etc/supervisor/conf.d/sshd.conf" during parsing
2020-08-23 15:01:04,109 INFO RPC interface 'supervisor' initialized
2020-08-23 15:01:04,109 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2020-08-23 15:01:04,110 INFO supervisord started with pid 1990
2020-08-23 15:01:05,112 INFO spawned: 'gitaly' with pid 2011
2020-08-23 15:01:05,114 INFO spawned: 'puma' with pid 2012
2020-08-23 15:01:05,117 INFO spawned: 'gitlab-workhorse' with pid 2013
2020-08-23 15:01:05,120 INFO spawned: 'sidekiq' with pid 2014
2020-08-23 15:01:05,123 INFO spawned: 'nginx' with pid 2015
2020-08-23 15:01:05,126 INFO spawned: 'sshd' with pid 2019
2020-08-23 15:01:05,129 INFO spawned: 'cron' with pid 2020
2020-08-23 15:01:06,688 INFO success: gitaly entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-08-23 15:01:06,688 INFO success: puma entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-08-23 15:01:06,688 INFO success: gitlab-workhorse entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-08-23 15:01:06,688 INFO success: sidekiq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-08-23 15:01:06,688 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-08-23 15:01:06,688 INFO success: sshd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-08-23 15:01:06,688 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract_adapter.rb:746:in `column_for'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/postgresql/schema_statements.rb:696:in `change_column_default_for_alter'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/postgresql/schema_statements.rb:408:in `change_column_default'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/migration.rb:811:in `block in migrate'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:471:in `with_connection'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/migration.rb:810:in `migrate'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'

Caused by:
ActiveRecord::ActiveRecordError: No such column: application_settings.outbound_local_requests_whitelist
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract_adapter.rb:746:in `column_for'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/postgresql/schema_statements.rb:696:in `change_column_default_for_alter'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/postgresql/schema_statements.rb:408:in `change_column_default'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/migration.rb:890:in `block in method_missing'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/migration.rb:858:in `block in say_with_time'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/migration.rb:858:in `say_with_time'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/migration.rb:879:in `method_missing'
/home/git/gitlab/db/migrate/20190725012225_change_outbound_local_requests_whitelist_default.rb:16:in `up'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/migration.rb:831:in `exec_migration'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/migration.rb:812:in `block (2 levels) in migrate'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/migration.rb:811:in `block in migrate'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:471:in `with_connection'
/home/git/gitlab/vendor/bundle/ruby/2.6.0/gems/activerecord-6.0.3.1/lib/active_record/migration.rb:810:in `migrate'
```
Any suggestions will be very appreciated.
Thank you.

**Comment by MartinJLee** [comment]
Somehow managed to fix the issue.
Open shell on the container
``` sh
docker-compose run gitlab /bin/bash
```
Initialize gitlab
```sh
/sbin/entrypoint.sh app:init
```
Place [20180824202952_add_outbound_requests_whitelist_to_application_settings.rb](https://gitlab.com/gitlab-org/gitlab-foss/-/blob/2949cef813674555cf9f0cf919e3717876fb0e63/db/migrate/20180824202952_add_outbound_requests_whitelist_to_application_settings.rb) under db/migrate/
then run
``` sh
/home/git/gitlab# sudo -u git -H bundle exec rake db:migrate RAILS_ENV=production
```
