### ISSUE TITLE
gitlab backup Failed to minio ( s3 )

### ISSUE THREAD

**Issue by jicki** [sameersbn/docker-gitlab#2355]
```
rake aborted!
Excon::Error::Timeout: read timeout reached
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/socket.rb:295:in `select_with_timeout'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/socket.rb:67:in `rescue in readline'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/socket.rb:63:in `readline'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/response.rb:63:in `parse'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/response_parser.rb:7:in `response_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:448:in `response'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:279:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-core-2.1.0/lib/fog/core/connection.rb:81:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-xml-0.1.3/lib/fog/xml/connection.rb:9:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/storage.rb:629:in `_request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/storage.rb:624:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/requests/storage/abort_multipart_upload.rb:15:in `abort_multipart_upload'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/models/storage/file.rb:345:in `rescue in multipart_save'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/models/storage/file.rb:318:in `multipart_save'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/models/storage/file.rb:275:in `save'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-core-2.1.0/lib/fog/core/collection.rb:50:in `create'
/home/git/gitlab/lib/backup/manager.rb:52:in `upload'
/home/git/gitlab/lib/tasks/gitlab/backup.rake:28:in `block (3 levels) in <top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'

Caused by:
OpenSSL::SSL::SSLErrorWaitReadable: read would block
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/openssl-2.2.0/lib/openssl/buffering.rb:205:in `sysread_nonblock'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/openssl-2.2.0/lib/openssl/buffering.rb:205:in `read_nonblock'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/socket.rb:64:in `readline'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/response.rb:63:in `parse'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/response_parser.rb:7:in `response_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:448:in `response'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:279:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-core-2.1.0/lib/fog/core/connection.rb:81:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-xml-0.1.3/lib/fog/xml/connection.rb:9:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/storage.rb:629:in `_request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/storage.rb:624:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/requests/storage/abort_multipart_upload.rb:15:in `abort_multipart_upload'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/models/storage/file.rb:345:in `rescue in multipart_save'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/models/storage/file.rb:318:in `multipart_save'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/models/storage/file.rb:275:in `save'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-core-2.1.0/lib/fog/core/collection.rb:50:in `create'
/home/git/gitlab/lib/backup/manager.rb:52:in `upload'
/home/git/gitlab/lib/tasks/gitlab/backup.rake:28:in `block (3 levels) in <top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'

Caused by:
Excon::Error::Timeout: read timeout reached
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/socket.rb:295:in `select_with_timeout'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/socket.rb:67:in `rescue in readline'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/socket.rb:63:in `readline'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/response.rb:63:in `parse'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/response_parser.rb:7:in `response_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:448:in `response'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:279:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/idempotent.rb:50:in `error_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/base.rb:17:in `error_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/base.rb:17:in `error_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:304:in `rescue in request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:230:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/idempotent.rb:50:in `error_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/base.rb:17:in `error_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/base.rb:17:in `error_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:304:in `rescue in request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:230:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/idempotent.rb:50:in `error_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/base.rb:17:in `error_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/base.rb:17:in `error_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:304:in `rescue in request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:230:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-core-2.1.0/lib/fog/core/connection.rb:81:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-xml-0.1.3/lib/fog/xml/connection.rb:9:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/storage.rb:629:in `_request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/storage.rb:624:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/requests/storage/upload_part.rb:25:in `upload_part'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/models/storage/file.rb:334:in `multipart_save'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/models/storage/file.rb:275:in `save'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-core-2.1.0/lib/fog/core/collection.rb:50:in `create'
/home/git/gitlab/lib/backup/manager.rb:52:in `upload'
/home/git/gitlab/lib/tasks/gitlab/backup.rake:28:in `block (3 levels) in <top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'

Caused by:
OpenSSL::SSL::SSLErrorWaitReadable: read would block
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/openssl-2.2.0/lib/openssl/buffering.rb:205:in `sysread_nonblock'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/openssl-2.2.0/lib/openssl/buffering.rb:205:in `read_nonblock'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/socket.rb:64:in `readline'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/response.rb:63:in `parse'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/response_parser.rb:7:in `response_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:448:in `response'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:279:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/idempotent.rb:50:in `error_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/base.rb:17:in `error_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/base.rb:17:in `error_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:304:in `rescue in request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:230:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/idempotent.rb:50:in `error_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/base.rb:17:in `error_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/base.rb:17:in `error_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:304:in `rescue in request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:230:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/idempotent.rb:50:in `error_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/base.rb:17:in `error_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/base.rb:17:in `error_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:304:in `rescue in request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:230:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-core-2.1.0/lib/fog/core/connection.rb:81:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-xml-0.1.3/lib/fog/xml/connection.rb:9:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/storage.rb:629:in `_request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/storage.rb:624:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/requests/storage/upload_part.rb:25:in `upload_part'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/models/storage/file.rb:334:in `multipart_save'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/models/storage/file.rb:275:in `save'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-core-2.1.0/lib/fog/core/collection.rb:50:in `create'
/home/git/gitlab/lib/backup/manager.rb:52:in `upload'
/home/git/gitlab/lib/tasks/gitlab/backup.rake:28:in `block (3 levels) in <top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'

Caused by:
Excon::Error::Timeout: read timeout reached
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/socket.rb:295:in `select_with_timeout'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/socket.rb:67:in `rescue in readline'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/socket.rb:63:in `readline'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/response.rb:63:in `parse'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/response_parser.rb:7:in `response_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:448:in `response'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:279:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/idempotent.rb:50:in `error_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/base.rb:17:in `error_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/base.rb:17:in `error_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:304:in `rescue in request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:230:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/idempotent.rb:50:in `error_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/base.rb:17:in `error_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/base.rb:17:in `error_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:304:in `rescue in request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:230:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-core-2.1.0/lib/fog/core/connection.rb:81:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-xml-0.1.3/lib/fog/xml/connection.rb:9:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/storage.rb:629:in `_request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/storage.rb:624:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/requests/storage/upload_part.rb:25:in `upload_part'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/models/storage/file.rb:334:in `multipart_save'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/models/storage/file.rb:275:in `save'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-core-2.1.0/lib/fog/core/collection.rb:50:in `create'
/home/git/gitlab/lib/backup/manager.rb:52:in `upload'
/home/git/gitlab/lib/tasks/gitlab/backup.rake:28:in `block (3 levels) in <top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'

Caused by:
OpenSSL::SSL::SSLErrorWaitReadable: read would block
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/openssl-2.2.0/lib/openssl/buffering.rb:205:in `sysread_nonblock'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/openssl-2.2.0/lib/openssl/buffering.rb:205:in `read_nonblock'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/socket.rb:64:in `readline'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/response.rb:63:in `parse'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/response_parser.rb:7:in `response_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:448:in `response'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:279:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/idempotent.rb:50:in `error_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/base.rb:17:in `error_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/base.rb:17:in `error_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:304:in `rescue in request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:230:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/idempotent.rb:50:in `error_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/base.rb:17:in `error_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/base.rb:17:in `error_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:304:in `rescue in request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:230:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-core-2.1.0/lib/fog/core/connection.rb:81:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-xml-0.1.3/lib/fog/xml/connection.rb:9:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/storage.rb:629:in `_request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/storage.rb:624:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/requests/storage/upload_part.rb:25:in `upload_part'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/models/storage/file.rb:334:in `multipart_save'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/models/storage/file.rb:275:in `save'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-core-2.1.0/lib/fog/core/collection.rb:50:in `create'
/home/git/gitlab/lib/backup/manager.rb:52:in `upload'
/home/git/gitlab/lib/tasks/gitlab/backup.rake:28:in `block (3 levels) in <top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'

Caused by:
Excon::Error::Timeout: read timeout reached
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/socket.rb:295:in `select_with_timeout'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/socket.rb:67:in `rescue in readline'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/socket.rb:63:in `readline'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/response.rb:63:in `parse'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/response_parser.rb:7:in `response_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:448:in `response'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:279:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/idempotent.rb:50:in `error_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/base.rb:17:in `error_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/base.rb:17:in `error_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:304:in `rescue in request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:230:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-core-2.1.0/lib/fog/core/connection.rb:81:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-xml-0.1.3/lib/fog/xml/connection.rb:9:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/storage.rb:629:in `_request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/storage.rb:624:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/requests/storage/upload_part.rb:25:in `upload_part'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/models/storage/file.rb:334:in `multipart_save'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/models/storage/file.rb:275:in `save'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-core-2.1.0/lib/fog/core/collection.rb:50:in `create'
/home/git/gitlab/lib/backup/manager.rb:52:in `upload'
/home/git/gitlab/lib/tasks/gitlab/backup.rake:28:in `block (3 levels) in <top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'

Caused by:
OpenSSL::SSL::SSLErrorWaitReadable: read would block
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/openssl-2.2.0/lib/openssl/buffering.rb:205:in `sysread_nonblock'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/openssl-2.2.0/lib/openssl/buffering.rb:205:in `read_nonblock'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/socket.rb:64:in `readline'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/response.rb:63:in `parse'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/response_parser.rb:7:in `response_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:448:in `response'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:279:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/idempotent.rb:50:in `error_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/base.rb:17:in `error_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/base.rb:17:in `error_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:304:in `rescue in request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:230:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-core-2.1.0/lib/fog/core/connection.rb:81:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-xml-0.1.3/lib/fog/xml/connection.rb:9:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/storage.rb:629:in `_request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/storage.rb:624:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/requests/storage/upload_part.rb:25:in `upload_part'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/models/storage/file.rb:334:in `multipart_save'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/models/storage/file.rb:275:in `save'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-core-2.1.0/lib/fog/core/collection.rb:50:in `create'
/home/git/gitlab/lib/backup/manager.rb:52:in `upload'
/home/git/gitlab/lib/tasks/gitlab/backup.rake:28:in `block (3 levels) in <top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'

Caused by:
Excon::Error::BadGateway: Expected(200) <=> Actual(502 Bad Gateway)
excon.error.response

/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/expects.rb:13:in `response_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/middlewares/response_parser.rb:12:in `response_call'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:448:in `response'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/excon-0.71.1/lib/excon/connection.rb:279:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-core-2.1.0/lib/fog/core/connection.rb:81:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-xml-0.1.3/lib/fog/xml/connection.rb:9:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/storage.rb:629:in `_request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/storage.rb:624:in `request'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/requests/storage/upload_part.rb:25:in `upload_part'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/models/storage/file.rb:334:in `multipart_save'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-aws-3.9.0/lib/fog/aws/models/storage/file.rb:275:in `save'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/fog-core-2.1.0/lib/fog/core/collection.rb:50:in `create'
/home/git/gitlab/lib/backup/manager.rb:52:in `upload'
/home/git/gitlab/lib/tasks/gitlab/backup.rake:28:in `block (3 levels) in <top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
Tasks: TOP => gitlab:backup:create
(See full trace by running task with --trace)
done
Uploading backup archive to remote storage stg-gitlab ... 
```

**Comment by linuxoid69** [comment]
@jicki Hi. How did you resolve this problem?
