### ISSUE TITLE
ArgumentError when logging in

### ISSUE THREAD

**Issue by freecrap** [sameersbn/docker-gitlab#2378]
```
Processing by SessionsController#create as HTML
  Parameters: {"authenticity_token"=>"[FILTERED]", "user"=>{"login"=>"alex@ilovetwins.com", "password"=>"[FILTERED]", "remember_me"=>"1"}}
  Rendered layout layouts/devise.html.haml (Duration: 306.3ms | Allocations: 23820)
Filter chain halted as :authenticate_with_two_factor rendered or redirected
Completed 200 OK in 486ms (Views: 271.2ms | ActiveRecord: 47.8ms | Elasticsearch: 0.0ms | Allocations: 28057)
Started POST "/users/sign_in" for 1.2.3.4 at 2021-07-02 09:22:09 +0100
  
ArgumentError (marshal data too short):
  
lib/gitlab/middleware/read_only/controller.rb:50:in `call'
lib/gitlab/middleware/read_only.rb:18:in `call'
lib/gitlab/middleware/same_site_cookies.rb:27:in `call'
lib/gitlab/middleware/handle_malformed_strings.rb:21:in `call'
lib/gitlab/middleware/basic_health_check.rb:25:in `call'
lib/gitlab/middleware/handle_ip_spoof_attack_error.rb:25:in `call'
lib/gitlab/middleware/request_context.rb:21:in `call'
config/initializers/fix_local_cache_middleware.rb:11:in `call'
lib/gitlab/middleware/rack_multipart_tempfile_factory.rb:19:in `call'
lib/gitlab/metrics/requests_rack_middleware.rb:74:in `call'
lib/gitlab/middleware/release_env.rb:12:in `call'
Started GET "/favicon.ico" for 1.2.3.4 at 2021-07-02 09:22:09 +0100
root@gitlab:/home/git/gitlab/log# exit
```

**Comment by kkimurak** [comment]
It would be duplicate of #2373 .
