### ISSUE TITLE
Issue with gitlab image in OCP 4

### ISSUE THREAD

**Issue by sitikanthamishra** [sameersbn/docker-gitlab#2413]
Hello

I have deployed gitlab "image = " with postgres and redis , but every time it shows an error with puma and pod goes for crashloopbackoff error.

I have also tried with image with latest tag in quay,io

command used for deployment

oc new-app quay.io/sameersbn/gitlab:13.12.4 --name=gitlab -e 'GITLAB_HOST=https://gitlab.apps.example.com'  -e 'DB_TYPE=postgres' -e 'DB_HOST=postgresql' -e 'DB_PORT=5432'    -e 'DB_NAME=gitlab'   -e 'DB_USER=admin' -e 'DB_PASS=redhat'   -e 'REDIS_HOST=redis' -e 'REDIS_PORT=6379' -e 'GITLAB_SECRETS_DB_KEY_BASE=1234567890'

Error message
2021-09-06 10:44:36,458 INFO exited: puma (exit status 1; not expected)

rake aborted!

NoMethodError: undefined method `empty?' for 1234567890:Integer

/home/git/gitlab/lib/gitlab/utils.rb:54:in `ensure_utf8_size'

/home/git/gitlab/config/settings.rb:142:in `attr_encrypted_db_key_base_32'

/home/git/gitlab/app/models/concerns/ci/new_has_variable.rb:12:in `block in <module:NewHasVariable>'

/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/concern.rb:122:in `class_eval'

/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.6/lib/active_support/concern.rb:122:in `append_features'

/home/git/gitlab/app/models/ci/instance_variable.rb:7:in `include'

/home/git/gitlab/app/models/ci/instance_variable.rb:7:in `<class:InstanceVariable>'

/home/git/gitlab/app/models/ci/instance_variable.rb:4:in `<module:Ci>'

/home/git/gitlab/app/models/ci/instance_variable.rb:3:in `<top (required)>'

**Comment by kkimurak** [comment]
(Note that I've never used OCP)

Please make sure that `GITLAB_SECRETS_DB_KEY_BASE` is alphanumeric string, not integer. The value you set (`1234567890`) will be recognized as integer (and the error message says so).

> NoMethodError: undefined method `empty?' for 1234567890:Integer

`GITLAB_SECRETS_DB_KEY_BASE` must be string that has 32 chars  length. Please refer the code in [`gitlab/config/settings.rb`](https://gitlab.com/gitlab-org/gitlab-foss/-/blob/ab7ca19e6844c37a715e378801409e297fd51512/config/settings.rb#L128-149) or check [setting introduction in README.md](https://github.com/sameersbn/docker-gitlab#available-configuration-parameters).
