### ISSUE TITLE
TypeError (no implicit conversion of Symbol into String): app/models/concerns/ci/contextable.rb:64

### ISSUE THREAD

**Issue by BertrandGouny** [sameersbn/docker-gitlab#2451]
Get 500 error when i try to create a pipeline :

https://gitlab.com/gitlab-org/gitlab/-/blob/v14.4.1-ee/app/models/concerns/ci/contextable.rb#L64

Gitlab 14.4.1
Gitlab Runner 14.4

Might be a configuration error ? Any clue welcome :)

```
Started POST "/xxxxxxxxx/xxxxxxxx/-/pipelines" for xx.xx.xx.xx at 2021-11-08 13:08:50 +0000
Processing by Projects::PipelinesController#create as JSON
  Parameters: {"ref"=>"refs/heads/develop", "variables_attributes"=>"[FILTERED]", "namespace_id"=>"xxxxxxxxx", "project_id"=>"xxxxxxxx", "pipeline"=>{"ref"=>"refs/heads/develop", "variables_attributes"=>"[FILTERED]"}}
Started POST "/api/v4/jobs/request" for xx.xx.xx.xx at 2021-11-08 13:08:51 +0000
Completed 500 Internal Server Error in 722ms (ActiveRecord: 193.6ms | Elasticsearch: 0.0ms | Allocations: 209586)
  
TypeError (no implicit conversion of Symbol into String):
  
app/models/concerns/ci/contextable.rb:64:in `include?'
app/models/concerns/ci/contextable.rb:64:in `block in predefined_variables'
app/models/concerns/ci/contextable.rb:58:in `tap'
app/models/concerns/ci/contextable.rb:58:in `predefined_variables'
app/models/concerns/ci/contextable.rb:14:in `block in scoped_variables'
app/models/concerns/ci/contextable.rb:13:in `tap'
app/models/concerns/ci/contextable.rb:13:in `scoped_variables'
lib/gitlab/ci/build/context/build.rb:24:in `block in variables'
lib/gitlab/utils/strong_memoize.rb:30:in `strong_memoize'
lib/gitlab/ci/build/context/build.rb:19:in `variables'
lib/gitlab/ci/pipeline/seed/build.rb:176:in `variable_expansion_errors'
lib/gitlab/ci/pipeline/seed/build.rb:60:in `block in errors'
lib/gitlab/utils/strong_memoize.rb:30:in `strong_memoize'
lib/gitlab/ci/pipeline/seed/build.rb:59:in `errors'
lib/gitlab/ci/pipeline/seed/stage.rb:39:in `each'
lib/gitlab/ci/pipeline/seed/stage.rb:39:in `flat_map'
lib/gitlab/ci/pipeline/seed/stage.rb:39:in `block in errors'
lib/gitlab/utils/strong_memoize.rb:30:in `strong_memoize'
lib/gitlab/ci/pipeline/seed/stage.rb:38:in `errors'
lib/gitlab/ci/pipeline/seed/pipeline.rb:16:in `each'
lib/gitlab/ci/pipeline/seed/pipeline.rb:16:in `flat_map'
lib/gitlab/ci/pipeline/seed/pipeline.rb:16:in `errors'
lib/gitlab/ci/pipeline/chain/seed.rb:26:in `perform!'
lib/gitlab/ci/pipeline/chain/sequence.rb:20:in `block in build!'
lib/gitlab/ci/pipeline/chain/sequence.rb:16:in `each'
lib/gitlab/ci/pipeline/chain/sequence.rb:16:in `build!'
app/services/ci/create_pipeline_service.rb:85:in `execute'
app/controllers/projects/pipelines_controller.rb:69:in `create'
app/controllers/application_controller.rb:503:in `set_current_admin'
lib/gitlab/session.rb:11:in `with_session'
app/controllers/application_controller.rb:494:in `set_session_storage'
lib/gitlab/i18n.rb:105:in `with_locale'
lib/gitlab/i18n.rb:111:in `with_user_locale'
app/controllers/application_controller.rb:488:in `set_locale'
app/controllers/application_controller.rb:482:in `set_current_context'
lib/gitlab/middleware/speedscope.rb:13:in `call'
lib/gitlab/request_profiler/middleware.rb:17:in `call'
lib/gitlab/database/load_balancing/rack_middleware.rb:23:in `call'
lib/gitlab/jira/middleware.rb:19:in `call'
lib/gitlab/middleware/go.rb:20:in `call'
lib/gitlab/etag_caching/middleware.rb:21:in `call'
lib/gitlab/middleware/multipart.rb:173:in `call'
lib/gitlab/middleware/read_only/controller.rb:50:in `call'
lib/gitlab/middleware/read_only.rb:18:in `call'
lib/gitlab/middleware/same_site_cookies.rb:27:in `call'
lib/gitlab/middleware/handle_malformed_strings.rb:21:in `call'
lib/gitlab/middleware/basic_health_check.rb:25:in `call'
lib/gitlab/middleware/handle_ip_spoof_attack_error.rb:25:in `call'
lib/gitlab/middleware/request_context.rb:21:in `call'
config/initializers/fix_local_cache_middleware.rb:11:in `call'
lib/gitlab/middleware/rack_multipart_tempfile_factory.rb:19:in `call'
lib/gitlab/middleware/sidekiq_web_static.rb:20:in `call'
lib/gitlab/metrics/requests_rack_middleware.rb:75:in `call'
lib/gitlab/middleware/release_env.rb:12:in `call'
```

**Comment by baracoder** [comment]
@BertrandGouny  We hit a similar issue trying to updating to 14.2, did you have any luck solving that problem?

**Comment by BertrandGouny** [comment]
@baracoder unfortunately no, i ended up recreating the whole gitlab instance with a newer version of the image

**Comment by baracoder** [comment]
@BertrandGouny that is sad to hear. Thank you for the quick update anyway.
