### ISSUE TITLE
Assigning issues after upgrading to >= 14.4 raise an error (but it gets assigned)

### ISSUE THREAD

**Issue by paolomainardi** [sameersbn/docker-gitlab#2482]
As reported here: https://gitlab.com/gitlab-org/gitlab/-/issues/349481

Anyone is having the same issue ?

**Comment by paolomainardi** [comment]
What i've noticed now is that opening issues raise this error:

```
Finished "/-/cable/" [WebSocket] for 5.90.96.187 at 2022-01-02 23:09:26 +0100
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/actioncable-6.1.4.1/lib/action_cable/server/configuration.rb:27:in `pubsub_adapter'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/actioncable-6.1.4.1/lib/action_cable/server/base.rb:83:in `block in pubsub'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/actioncable-6.1.4.1/lib/action_cable/server/base.rb:83:in `synchronize'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/actioncable-6.1.4.1/lib/action_cable/server/base.rb:83:in `pubsub'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/actioncable-6.1.4.1/lib/action_cable/connection/base.rb:53:in `pubsub'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/actioncable-6.1.4.1/lib/action_cable/channel/streams.rb:140:in `pubsub'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/actioncable-6.1.4.1/lib/action_cable/channel/streams.rb:122:in `block in stop_all_streams'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/actioncable-6.1.4.1/lib/action_cable/channel/streams.rb:121:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/actioncable-6.1.4.1/lib/action_cable/channel/streams.rb:121:in `stop_all_streams'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/actioncable-6.1.4.1/lib/action_cable/engine.rb:68:in `block (3 levels) in <class:Engine>'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/lograge-0.11.2/lib/lograge/rails_ext/action_cable/channel/base.rb:17:in `block in unsubscribe_from_channel'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/lograge-0.11.2/lib/lograge/rails_ext/action_cable/channel/base.rb:16:in `unsubscribe_from_channel'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/actioncable-6.1.4.1/lib/action_cable/connection/subscriptions.rb:51:in `remove_subscription'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/actioncable-6.1.4.1/lib/action_cable/connection/subscriptions.rb:64:in `block in unsubscribe_from_all'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/actioncable-6.1.4.1/lib/action_cable/connection/subscriptions.rb:64:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/actioncable-6.1.4.1/lib/action_cable/connection/subscriptions.rb:64:in `unsubscribe_from_all'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/lograge-0.11.2/lib/lograge/rails_ext/action_cable/connection/base.rb:28:in `block in handle_close'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/lograge-0.11.2/lib/lograge/rails_ext/action_cable/connection/base.rb:23:in `handle_close'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/actioncable-6.1.4.1/lib/action_cable/server/worker.rb:60:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/actioncable-6.1.4.1/lib/action_cable/server/worker.rb:42:in `block in work'
/home/git/gitlab/lib/gitlab/database/load_balancing/action_cable_callbacks.rb:17:in `block in wrapper'
/home/git/gitlab/lib/gitlab/action_cable/request_store_callbacks.rb:15:in `block (2 levels) in wrapper'
/home/git/gitlab/lib/gitlab/action_cable/request_store_callbacks.rb:14:in `block in wrapper'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/actioncable-6.1.4.1/lib/action_cable/server/worker/active_record_connection_management.rb:16:in `block in with_database_connections'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/actioncable-6.1.4.1/lib/action_cable/connection/tagged_logger_proxy.rb:24:in `block in tag'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/actioncable-6.1.4.1/lib/action_cable/connection/tagged_logger_proxy.rb:24:in `tag'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/actioncable-6.1.4.1/lib/action_cable/server/worker/active_record_connection_management.rb:16:in `with_database_connections'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/actioncable-6.1.4.1/lib/action_cable/engine.rb:62:in `block (4 levels) in <class:Engine>'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/actioncable-6.1.4.1/lib/action_cable/engine.rb:57:in `block (3 levels) in <class:Engine>'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/actioncable-6.1.4.1/lib/action_cable/server/worker.rb:41:in `work'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/actioncable-6.1.4.1/lib/action_cable/server/worker.rb:59:in `invoke'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/actioncable-6.1.4.1/lib/action_cable/server/worker.rb:54:in `block in async_invoke'
Started GET "/-/cable" for 5.90.96.187 at 2022-01-02 23:09:26 +0100
Started GET "/-/cable/" [WebSocket] for 5.90.96.187 at 2022-01-02 23:09:26 +0100
```

cc @sachilles should this file be generated too https://gitlab.com/gitlab-org/gitlab/-/blob/master/scripts/prepare_build.sh#L35 ?

**Comment by paolomainardi** [comment]
Yes i confirm that this is the root cause, the file should be present because now ActionCable is always used, the files are quite recent too: https://gitlab.com/gitlab-org/gitlab/-/tree/master/lib/gitlab/action_cable

cc @sachilles how can this be fixed ? If you point me in the right direction i can try to make a PR

**Comment by achretien** [comment]
In omnibus they used this template file:

https://gitlab.com/gitlab-org/omnibus-gitlab/-/blob/master/files/gitlab-cookbooks/gitlab/templates/default/cable.yml.erb

**Comment by achretien** [comment]
@paolomainardi you have to check here: https://github.com/sameersbn/docker-gitlab/blob/b9cc7b4a33e031c18fb7119b3910366f898ffce4/assets/runtime/functions#L1745

Maybe adding a new `gitlab_configure_cable` function or something like that to copy a new template file from https://github.com/sameersbn/docker-gitlab/tree/master/assets/runtime/config/gitlabhq

**Comment by paolomainardi** [comment]
Here we are: https://github.com/sameersbn/docker-gitlab/pull/2483

**Comment by sachilles** [comment]
Thanks for your contribution!
