### ISSUE TITLE
rake aborted!

### ISSUE THREAD

**Issue by ytiaoa** [sameersbn/docker-gitlab#2524]
I deployed the sameersbn/gitlab in K8s.

gitlab failed to start, and I got the error log:

```
2022-03-15 13:47:41,207 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Missing Rails.application.secrets.openid_connect_signing_key for production environment. The secret will be generated and stored in config/secrets.yml.
rake aborted!
Psych::SyntaxError: (<unknown>): mapping values are not allowed in this context at line 482 column 22
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:103:in `initialize'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:60:in `new'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:60:in `instance'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:37:in `[]'
/home/git/gitlab/config/initializers/1_settings.rb:8:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.6/lib/rails/engine.rb:681:in `load'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.6/lib/rails/engine.rb:681:in `block in load_config_initializer'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/notifications.rb:205:in `instrument'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.6/lib/rails/engine.rb:680:in `load_config_initializer'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.6/lib/rails/engine.rb:634:in `block (2 levels) in <class:Engine>'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.6/lib/rails/engine.rb:633:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.6/lib/rails/engine.rb:633:in `block in <class:Engine>'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.6/lib/rails/initializable.rb:32:in `instance_exec'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.6/lib/rails/initializable.rb:32:in `run'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.6/lib/rails/initializable.rb:61:in `block in run_initializers'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.6/lib/rails/initializable.rb:50:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.6/lib/rails/initializable.rb:50:in `tsort_each_child'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.6/lib/rails/initializable.rb:60:in `run_initializers'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.6/lib/rails/application.rb:391:in `initialize!'
/home/git/gitlab/config/environment.rb:7:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:332:in `block in require'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:299:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:332:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.6/lib/rails/application.rb:367:in `require_environment!'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/railties-6.1.4.6/lib/rails/application.rb:533:in `block in run_tasks_blocks'
/home/git/gitlab/lib/tasks/gitlab/helpers.rake:7:in `block in <top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => environment
(See full trace by running task with --trace)
```

**Comment by zengqingfu1442** [comment]
@ytiaoa hi, I also came across this error, how did you resolve it? Can you share your resolution? thanks,
