### ISSUE TITLE
OpenSSL::Cipher::CipherError when showing project integrations

### ISSUE THREAD

**Issue by gazben** [sameersbn/docker-gitlab#2532]
After upgrading to 14.9, I cannot view the integrations for my project. I could not find relevant information in the gitlab bugtracker, so maybe this is an issue with this build.

I'm using a Mattermost and Sentry integration. The SSL cert is valid on both of them. 

`application.log`:

```
Processing by Projects::Settings::IntegrationsController#show as HTML
  Parameters: {"namespace_id"=>"REDACTED", "project_id"=>"REDACTED"}
Completed 500 Internal Server Error in 20ms (ActiveRecord: 2.0ms | Elasticsearch: 0.0ms | Allocations: 9901)
  
OpenSSL::Cipher::CipherError ():
  
app/models/integration.rb:405:in `copy_properties_to_encrypted_properties'
app/models/project.rb:2862:in `find_integration'
app/models/project.rb:1474:in `find_or_initialize_integration'
app/models/project.rb:1461:in `block in find_or_initialize_integrations'
app/models/project.rb:1461:in `map'
app/models/project.rb:1461:in `find_or_initialize_integrations'
app/controllers/projects/settings/integrations_controller.rb:12:in `show'
app/controllers/application_controller.rb:499:in `set_current_admin'
lib/gitlab/session.rb:11:in `with_session'
app/controllers/application_controller.rb:490:in `set_session_storage'
lib/gitlab/i18n.rb:105:in `with_locale'
lib/gitlab/i18n.rb:111:in `with_user_locale'
app/controllers/application_controller.rb:484:in `set_locale'
app/controllers/application_controller.rb:478:in `set_current_context'
lib/gitlab/metrics/elasticsearch_rack_middleware.rb:16:in `call'
lib/gitlab/middleware/rails_queue_duration.rb:33:in `call'
lib/gitlab/middleware/memory_report.rb:13:in `call'
lib/gitlab/middleware/speedscope.rb:13:in `call'
lib/gitlab/request_profiler/middleware.rb:17:in `call'
lib/gitlab/database/load_balancing/rack_middleware.rb:23:in `call'
lib/gitlab/metrics/rack_middleware.rb:16:in `block in call'
lib/gitlab/metrics/web_transaction.rb:46:in `run'
lib/gitlab/metrics/rack_middleware.rb:16:in `call'
lib/gitlab/jira/middleware.rb:19:in `call'
lib/gitlab/middleware/go.rb:20:in `call'
lib/gitlab/etag_caching/middleware.rb:21:in `call'
lib/gitlab/middleware/query_analyzer.rb:11:in `block in call'
lib/gitlab/database/query_analyzer.rb:46:in `within'
lib/gitlab/middleware/query_analyzer.rb:11:in `call'
lib/gitlab/middleware/multipart.rb:173:in `call'
lib/gitlab/middleware/read_only/controller.rb:50:in `call'
lib/gitlab/middleware/read_only.rb:18:in `call'
lib/gitlab/middleware/same_site_cookies.rb:27:in `call'
lib/gitlab/middleware/handle_malformed_strings.rb:21:in `call'
lib/gitlab/middleware/basic_health_check.rb:25:in `call'
lib/gitlab/middleware/handle_ip_spoof_attack_error.rb:25:in `call'
lib/gitlab/middleware/request_context.rb:21:in `call'
lib/gitlab/middleware/webhook_recursion_detection.rb:15:in `call'
config/initializers/fix_local_cache_middleware.rb:11:in `call'
lib/gitlab/middleware/compressed_json.rb:26:in `call'
lib/gitlab/middleware/rack_multipart_tempfile_factory.rb:19:in `call'
lib/gitlab/middleware/sidekiq_web_static.rb:20:in `call'
lib/gitlab/metrics/requests_rack_middleware.rb:77:in `call'
lib/gitlab/middleware/release_env.rb:13:in `call'
```
Anybody else got an error like this?

**Comment by omueller** [comment]
Not upgraded yet in production on  our side, waiting for 14.9.1 to be released.  But I also see nothing about integrations under https://about.gitlab.com/releases/2022/03/23/gitlab-14-9-1-released/, so not sure...

**Comment by gazben** [comment]
I've disabled the Mattermost from the railc console and now issue editing and review assignment works again but the integrations page still throws a 500.

This commit should be the one that introduces the problem. I've commented out the 
```
 after_initialize :copy_properties_to_encrypted_properties
  before_save :copy_properties_to_encrypted_properties
```
lines and only after that I was able to save the project object manually.

**Comment by gazben** [comment]
Running the integrity check fails with the same error.

https://docs.gitlab.com/ee/administration/raketasks/check.html#verify-database-values-can-be-decrypted-using-the-current-secrets

Output of `gitlab:doctor:secrets`:

```
git@1e7ee71d4c0b:~/gitlab$ bin/rake gitlab:doctor:secrets RAILS_ENV=production VERBOSE=1
I, [2022-03-27T12:36:12.934966 #22678]  INFO -- : Checking encrypted values in the database
I, [2022-03-27T12:36:18.252614 #22678]  INFO -- : - Ci::InstanceVariable failures: 0
I, [2022-03-27T12:36:18.266780 #22678]  INFO -- : - Ci::PipelineScheduleVariable failures: 0
I, [2022-03-27T12:36:19.846717 #22678]  INFO -- : - Ci::Variable failures: 0
I, [2022-03-27T12:36:19.868051 #22678]  INFO -- : - Ci::GroupVariable failures: 0
I, [2022-03-27T12:36:20.005785 #22678]  INFO -- : - Ci::PipelineVariable failures: 0
I, [2022-03-27T12:36:20.021374 #22678]  INFO -- : - Ci::JobVariable failures: 0
I, [2022-03-27T12:36:20.034778 #22678]  INFO -- : - ApplicationSetting failures: 0
I, [2022-03-27T12:36:20.913311 #22678]  INFO -- : - User failures: 0
I, [2022-03-27T12:36:20.925906 #22678]  INFO -- : - Clusters::Platforms::Kubernetes failures: 0
I, [2022-03-27T12:36:20.967336 #22678]  INFO -- : - Snippet failures: 0
I, [2022-03-27T12:36:20.969258 #22678]  INFO -- : - PersonalSnippet failures: 0
I, [2022-03-27T12:36:20.970558 #22678]  INFO -- : - ProjectSnippet failures: 0
I, [2022-03-27T12:36:20.984156 #22678]  INFO -- : - Clusters::Applications::Helm failures: 0
I, [2022-03-27T12:36:21.000923 #22678]  INFO -- : - Clusters::Applications::Prometheus failures: 0
rake aborted!
OpenSSL::Cipher::CipherError: 
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/encryptor-3.0.0/lib/encryptor.rb:98:in `final'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/encryptor-3.0.0/lib/encryptor.rb:98:in `crypt'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/encryptor-3.0.0/lib/encryptor.rb:49:in `decrypt'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/attr_encrypted-3.1.0/lib/attr_encrypted.rb:240:in `decrypt'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/attr_encrypted-3.1.0/lib/attr_encrypted.rb:329:in `decrypt'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/attr_encrypted-3.1.0/lib/attr_encrypted.rb:161:in `block (2 levels) in attr_encrypted'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/attr_encrypted-3.1.0/lib/attr_encrypted/adapters/active_record.rb:76:in `block in attr_encrypted'
/home/git/gitlab/app/models/integration.rb:405:in `copy_properties_to_encrypted_properties'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/callbacks.rb:427:in `block in make_lambda'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/callbacks.rb:235:in `block in halting_and_conditional'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/callbacks.rb:516:in `block in invoke_after'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/callbacks.rb:516:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/callbacks.rb:516:in `invoke_after'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/callbacks.rb:107:in `run_callbacks'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/callbacks.rb:824:in `_run_initialize_callbacks'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4.6/lib/active_record/core.rb:549:in `init_with_attributes'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4.6/lib/active_record/persistence.rb:403:in `instantiate_instance_of'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4.6/lib/active_record/persistence.rb:258:in `instantiate'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4.6/lib/active_record/querying.rb:63:in `block (2 levels) in find_by_sql'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4.6/lib/active_record/result.rb:62:in `block in each'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4.6/lib/active_record/result.rb:62:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4.6/lib/active_record/result.rb:62:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4.6/lib/active_record/querying.rb:63:in `map'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4.6/lib/active_record/querying.rb:63:in `block in find_by_sql'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.4.6/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4.6/lib/active_record/querying.rb:61:in `find_by_sql'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4.6/lib/active_record/relation.rb:843:in `block in exec_queries'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4.6/lib/active_record/relation.rb:858:in `block in skip_query_cache_if_necessary'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4.6/lib/active_record/connection_adapters/abstract/query_cache.rb:79:in `uncached'
/home/git/gitlab/lib/gitlab/database/load_balancing/connection_proxy.rb:126:in `block in write_using_load_balancer'
/home/git/gitlab/lib/gitlab/database/load_balancing/load_balancer.rb:112:in `block in read_write'
/home/git/gitlab/lib/gitlab/database/load_balancing/load_balancer.rb:172:in `retry_with_backoff'
/home/git/gitlab/lib/gitlab/database/load_balancing/load_balancer.rb:110:in `read_write'
/home/git/gitlab/lib/gitlab/database/load_balancing/connection_proxy.rb:125:in `write_using_load_balancer'
/home/git/gitlab/lib/gitlab/database/load_balancing/connection_proxy.rb:95:in `method_missing'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4.6/lib/active_record/query_cache.rb:21:in `uncached'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4.6/lib/active_record/relation/delegation.rb:108:in `public_send'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4.6/lib/active_record/relation/delegation.rb:108:in `block in method_missing'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4.6/lib/active_record/relation.rb:406:in `block in scoping'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4.6/lib/active_record/relation.rb:804:in `_scoping'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4.6/lib/active_record/relation.rb:406:in `scoping'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4.6/lib/active_record/relation/delegation.rb:108:in `method_missing'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4.6/lib/active_record/relation.rb:857:in `skip_query_cache_if_necessary'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4.6/lib/active_record/relation.rb:828:in `exec_queries'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4.6/lib/active_record/relation.rb:631:in `load'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4.6/lib/active_record/relation.rb:249:in `records'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4.6/lib/active_record/relation/batches.rb:231:in `block in in_batches'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4.6/lib/active_record/relation/batches.rb:229:in `loop'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4.6/lib/active_record/relation/batches.rb:229:in `in_batches'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4.6/lib/active_record/relation/batches.rb:137:in `find_in_batches'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4.6/lib/active_record/relation/batches.rb:70:in `find_each'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activerecord-6.1.4.6/lib/active_record/querying.rb:22:in `find_each'
/home/git/gitlab/lib/gitlab/doctor/secrets.rb:38:in `block in check_model_attributes'
/home/git/gitlab/lib/gitlab/doctor/secrets.rb:36:in `each'
/home/git/gitlab/lib/gitlab/doctor/secrets.rb:36:in `check_model_attributes'
/home/git/gitlab/lib/gitlab/doctor/secrets.rb:26:in `run!'
/home/git/gitlab/lib/tasks/gitlab/doctor/secrets.rake:11:in `block (3 levels) in <top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/sentry-ruby-core-5.1.1/lib/sentry/rake.rb:26:in `execute'
Tasks: TOP => gitlab:doctor:secrets
(See full trace by running task with --trace)
```

**Comment by gazben** [comment]
@omueller The 14.9.1 upgrade did not fix the issue

**Comment by sachilles** [comment]
The error is apparently only visible through active/activated integrations. In my case (with no integrations), no error appears.

```
# bin/rake gitlab:doctor:secrets RAILS_ENV=production VERBOSE=1
I, [2022-03-28T08:03:27.949042 #86359]  INFO -- : Checking encrypted values in the database
I, [2022-03-28T08:03:43.787950 #86359]  INFO -- : - Ci::InstanceVariable failures: 0
I, [2022-03-28T08:03:43.821032 #86359]  INFO -- : - Ci::PipelineScheduleVariable failures: 0
I, [2022-03-28T08:03:43.902597 #86359]  INFO -- : - Ci::Variable failures: 0
I, [2022-03-28T08:03:43.937017 #86359]  INFO -- : - Ci::GroupVariable failures: 0
I, [2022-03-28T08:03:43.970156 #86359]  INFO -- : - Ci::PipelineVariable failures: 0
I, [2022-03-28T08:03:44.003074 #86359]  INFO -- : - Ci::JobVariable failures: 0
I, [2022-03-28T08:03:44.034570 #86359]  INFO -- : - ApplicationSetting failures: 0
I, [2022-03-28T08:03:44.721096 #86359]  INFO -- : - User failures: 0
I, [2022-03-28T08:03:44.758773 #86359]  INFO -- : - Clusters::Platforms::Kubernetes failures: 0
I, [2022-03-28T08:03:44.882881 #86359]  INFO -- : - Snippet failures: 0
I, [2022-03-28T08:03:44.887482 #86359]  INFO -- : - PersonalSnippet failures: 0
I, [2022-03-28T08:03:44.891377 #86359]  INFO -- : - ProjectSnippet failures: 0
I, [2022-03-28T08:03:44.926265 #86359]  INFO -- : - Clusters::Applications::Helm failures: 0
I, [2022-03-28T08:03:44.961546 #86359]  INFO -- : - Clusters::Applications::Prometheus failures: 0
I, [2022-03-28T08:03:45.141499 #86359]  INFO -- : - Integration failures: 0
I, [2022-03-28T08:03:45.148330 #86359]  INFO -- : - Integrations::Asana failures: 0
I, [2022-03-28T08:03:45.154831 #86359]  INFO -- : - Integrations::Assembla failures: 0
I, [2022-03-28T08:03:45.161578 #86359]  INFO -- : - Integrations::BaseCi failures: 0
I, [2022-03-28T08:03:45.168127 #86359]  INFO -- : - Integrations::Bamboo failures: 0
I, [2022-03-28T08:03:45.174562 #86359]  INFO -- : - Integrations::Buildkite failures: 0
I, [2022-03-28T08:03:45.180946 #86359]  INFO -- : - Integrations::DroneCi failures: 0
I, [2022-03-28T08:03:45.187497 #86359]  INFO -- : - Integrations::Jenkins failures: 0
I, [2022-03-28T08:03:45.193961 #86359]  INFO -- : - Integrations::Teamcity failures: 0
I, [2022-03-28T08:03:45.200450 #86359]  INFO -- : - Integrations::MockCi failures: 0
I, [2022-03-28T08:03:45.205691 #86359]  INFO -- : - Integrations::BaseIssueTracker failures: 0
I, [2022-03-28T08:03:45.212292 #86359]  INFO -- : - Integrations::Bugzilla failures: 0
I, [2022-03-28T08:03:45.218772 #86359]  INFO -- : - Integrations::CustomIssueTracker failures: 0
I, [2022-03-28T08:03:45.225358 #86359]  INFO -- : - Integrations::Ewm failures: 0
I, [2022-03-28T08:03:45.232006 #86359]  INFO -- : - Integrations::Jira failures: 0
I, [2022-03-28T08:03:45.236707 #86359]  INFO -- : - Integrations::Redmine failures: 0
I, [2022-03-28T08:03:45.243463 #86359]  INFO -- : - Integrations::Youtrack failures: 0
I, [2022-03-28T08:03:45.249911 #86359]  INFO -- : - Integrations::Campfire failures: 0
I, [2022-03-28T08:03:45.256232 #86359]  INFO -- : - Integrations::Confluence failures: 0
I, [2022-03-28T08:03:45.262469 #86359]  INFO -- : - Integrations::Datadog failures: 0
I, [2022-03-28T08:03:45.269044 #86359]  INFO -- : - Integrations::BaseChatNotification failures: 0
I, [2022-03-28T08:03:45.275594 #86359]  INFO -- : - Integrations::Discord failures: 0
I, [2022-03-28T08:03:45.282002 #86359]  INFO -- : - Integrations::HangoutsChat failures: 0
I, [2022-03-28T08:03:45.288396 #86359]  INFO -- : - Integrations::Mattermost failures: 0
I, [2022-03-28T08:03:45.294903 #86359]  INFO -- : - Integrations::MicrosoftTeams failures: 0
I, [2022-03-28T08:03:45.301431 #86359]  INFO -- : - Integrations::Slack failures: 0
I, [2022-03-28T08:03:45.307933 #86359]  INFO -- : - Integrations::WebexTeams failures: 0
I, [2022-03-28T08:03:45.314468 #86359]  INFO -- : - Integrations::UnifyCircuit failures: 0
I, [2022-03-28T08:03:45.321127 #86359]  INFO -- : - Integrations::EmailsOnPush failures: 0
I, [2022-03-28T08:03:45.327774 #86359]  INFO -- : - Integrations::ExternalWiki failures: 0
I, [2022-03-28T08:03:45.334309 #86359]  INFO -- : - Integrations::Flowdock failures: 0
I, [2022-03-28T08:03:45.340753 #86359]  INFO -- : - Integrations::Harbor failures: 0
I, [2022-03-28T08:03:45.347528 #86359]  INFO -- : - Integrations::Irker failures: 0
I, [2022-03-28T08:03:45.354055 #86359]  INFO -- : - Integrations::BaseSlashCommands failures: 0
I, [2022-03-28T08:03:45.360437 #86359]  INFO -- : - Integrations::MattermostSlashCommands failures: 0
I, [2022-03-28T08:03:45.366874 #86359]  INFO -- : - Integrations::SlackSlashCommands failures: 0
I, [2022-03-28T08:03:45.373006 #86359]  INFO -- : - Integrations::Packagist failures: 0
I, [2022-03-28T08:03:45.379117 #86359]  INFO -- : - Integrations::PipelinesEmail failures: 0
I, [2022-03-28T08:03:45.385038 #86359]  INFO -- : - Integrations::Pivotaltracker failures: 0
I, [2022-03-28T08:03:45.390973 #86359]  INFO -- : - Integrations::BaseMonitoring failures: 0
I, [2022-03-28T08:03:45.396970 #86359]  INFO -- : - Integrations::Prometheus failures: 0
I, [2022-03-28T08:03:45.403038 #86359]  INFO -- : - Integrations::MockMonitoring failures: 0
I, [2022-03-28T08:03:45.408950 #86359]  INFO -- : - Integrations::Pushover failures: 0
I, [2022-03-28T08:03:45.414884 #86359]  INFO -- : - Integrations::Zentao failures: 0
I, [2022-03-28T08:03:45.420937 #86359]  INFO -- : - Integrations::Shimo failures: 0
I, [2022-03-28T08:03:45.460730 #86359]  INFO -- : - AlertManagement::HttpIntegration failures: 0
I, [2022-03-28T08:03:45.493449 #86359]  INFO -- : - PagesDomain failures: 0
I, [2022-03-28T08:03:45.529486 #86359]  INFO -- : - PagesDomainAcmeOrder failures: 0
I, [2022-03-28T08:03:45.587503 #86359]  INFO -- : - RemoteMirror failures: 0
I, [2022-03-28T08:03:45.622753 #86359]  INFO -- : - JiraConnectInstallation failures: 0
I, [2022-03-28T08:03:45.654082 #86359]  INFO -- : - ProjectImportData failures: 0
I, [2022-03-28T08:03:45.685330 #86359]  INFO -- : - GrafanaIntegration failures: 0
I, [2022-03-28T08:03:45.719155 #86359]  INFO -- : - WebHook failures: 0
I, [2022-03-28T08:03:45.724949 #86359]  INFO -- : - ServiceHook failures: 0
I, [2022-03-28T08:03:45.730596 #86359]  INFO -- : - ProjectHook failures: 0
I, [2022-03-28T08:03:45.736254 #86359]  INFO -- : - SystemHook failures: 0
I, [2022-03-28T08:03:45.774375 #86359]  INFO -- : - Clusters::KubernetesNamespace failures: 0
I, [2022-03-28T08:03:45.809077 #86359]  INFO -- : - Atlassian::Identity failures: 0
I, [2022-03-28T08:03:45.843073 #86359]  INFO -- : - Serverless::DomainCluster failures: 0
I, [2022-03-28T08:03:45.875583 #86359]  INFO -- : - BulkImports::Configuration failures: 0
I, [2022-03-28T08:03:45.907599 #86359]  INFO -- : - IncidentManagement::ProjectIncidentManagementSetting failures: 0
I, [2022-03-28T08:03:45.939455 #86359]  INFO -- : - Alerting::ProjectAlertingSetting failures: 0
I, [2022-03-28T08:03:45.975367 #86359]  INFO -- : - Integrations::JiraTrackerData failures: 0
I, [2022-03-28T08:03:46.009810 #86359]  INFO -- : - Integrations::ZentaoTrackerData failures: 0
I, [2022-03-28T08:03:46.073267 #86359]  INFO -- : - Integrations::IssueTrackerData failures: 0
I, [2022-03-28T08:03:46.106075 #86359]  INFO -- : - ErrorTracking::ProjectErrorTrackingSetting failures: 0
I, [2022-03-28T08:03:46.116360 #86359]  INFO -- : - Clusters::Integrations::Prometheus failures: 0
I, [2022-03-28T08:03:46.150884 #86359]  INFO -- : - Clusters::Providers::Gcp failures: 0
I, [2022-03-28T08:03:46.186676 #86359]  INFO -- : - Clusters::Providers::Aws failures: 0
I, [2022-03-28T08:03:46.227308 #86359]  INFO -- : - Packages::Debian::ProjectDistributionKey failures: 0
I, [2022-03-28T08:03:46.261487 #86359]  INFO -- : - Packages::Debian::GroupDistributionKey failures: 0
I, [2022-03-28T08:03:46.266071 #86359]  INFO -- : - Gitlab::BackgroundMigration::BackfillJiraTrackerDeploymentType2::JiraTrackerDataTemp failures: 0
I, [2022-03-28T08:03:46.344947 #86359]  INFO -- : - Ci::Runner failures: 0
I, [2022-03-28T08:03:46.684576 #86359]  INFO -- : - Ci::Build failures: 0
I, [2022-03-28T08:03:48.570733 #86359]  INFO -- : - Group failures: 0
I, [2022-03-28T08:04:07.837403 #86359]  INFO -- : - Project failures: 0
I, [2022-03-28T08:04:07.893755 #86359]  INFO -- : - DeployToken failures: 0
I, [2022-03-28T08:04:07.934650 #86359]  INFO -- : - Clusters::AgentToken failures: 0
I, [2022-03-28T08:04:07.974315 #86359]  INFO -- : - Operations::FeatureFlagsClient failures: 0
I, [2022-03-28T08:04:07.974442 #86359]  INFO -- : Total: 0 row(s) affected
I, [2022-03-28T08:04:07.974489 #86359]  INFO -- : Done!
```

**Comment by gazben** [comment]
Created an issue about this: https://gitlab.com/gitlab-org/gitlab/-/issues/356943
