### ISSUE TITLE
Sidekiq email delivery jobs failures

### ISSUE THREAD

**Issue by gkostyanikov** [sameersbn/docker-gitlab#254]
Tried several ways starting gitlab container with linked redis and postgres instances.
So, started redis:
`
docker run --name=redis -d sameersbn/redis:latest
`
then postgres
```
  docker run --name=postgresql -d \
  -e 'DB_NAME=gitlabhq_production' -e 'DB_USER=gitlab' -e 'DB_PASS=c8AsHg8KYCjTo' \
  -v /opt/postgresql/data:/var/lib/postgresql \
  sameersbn/postgresql:latest
```
and finally:
```
docker run --name=gitlab -d \
  -v /opt/gitlab/data:/home/git/data \
  --link redis:redisio \
  --link postgresql:postgresql \
  -e 'GITLAB_PORT=10080' \
  -e 'GITLAB_SSH_PORT=10022' \
  -e 'GITLAB_HOST=git.domain.com' \
  -e 'GITLAB_EMAIL=gitlab@domain.com' \
  -e 'GITLAB_SUPPORT=gitlab@domain.com' \
  -e 'SMTP_USER=domain@gmail.com' \
  -e 'SMTP_PASS=[screened]' \
  -e 'GITLAB_BACKUPS=daily' \
  -e 'GITLAB_BACKUP_EXPIRY=604800' \
  -p 10022:22 -p 10080:80 sameersbn/gitlab:latest
```

Then created new user and got this in sidekiq.log:
```
2015-02-06T16:36:21Z 303 TID-5rn64 INFO: Starting processing, hit Ctrl-C to stop
2015-02-06T16:44:47Z 303 TID-8kuac Sidekiq::Extensions::DelayedMailer JID-cf023822088cdeba1d6db781 INFO: start
2015-02-06T16:44:47Z 303 TID-8kuac Sidekiq::Extensions::DelayedMailer JID-cf023822088cdeba1d6db781 INFO: fail: 0.238 sec
2015-02-06T16:44:47Z 303 TID-8kuac WARN: {"retry"=>true, "queue"=>"default", "class"=>"Sidekiq::Extensions::DelayedMailer", "args"=>["---\n- !ruby/class 'Notify'\n- :new_user_email\n- - 2\n - Fsy8kMxDrEAgjoFPsBBh\n"], "jid"=>"cf023822088cdeba1d6db781", "enqueued_at"=>1423241084.138529, "error_message"=>"getaddrinfo: Name or service not known", "error_class"=>"SocketError", "failed_at"=>1423241087.3542118, "retry_count"=>0}
2015-02-06T16:44:47Z 303 TID-8kuac WARN: getaddrinfo: Name or service not known
2015-02-06T16:44:47Z 303 TID-8kuac WARN: /usr/lib/ruby/2.1.0/net/smtp.rb:541:in `initialize'
/usr/lib/ruby/2.1.0/net/smtp.rb:541:in `open'
/usr/lib/ruby/2.1.0/net/smtp.rb:541:in `tcp_socket'
/usr/lib/ruby/2.1.0/net/smtp.rb:551:in `block in do_start'
/usr/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
/usr/lib/ruby/2.1.0/timeout.rb:101:in `call'
/usr/lib/ruby/2.1.0/timeout.rb:101:in `timeout'
/usr/lib/ruby/2.1.0/net/smtp.rb:550:in `do_start'
/usr/lib/ruby/2.1.0/net/smtp.rb:520:in `start'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail-2.5.4/lib/mail/network/delivery_methods/smtp.rb:112:in `deliver!'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail-2.5.4/lib/mail/message.rb:2129:in `do_delivery'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/mail-2.5.4/lib/mail/message.rb:232:in `block in deliver'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionmailer-4.1.1/lib/action_mailer/base.rb:527:in `block in deliver_mail'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/notifications.rb:159:in `block in instrument'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/notifications.rb:159:in `instrument'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionmailer-4.1.1/lib/action_mailer/base.rb:525:in `deliver_mail'
```
pop and smtp enabled for all addresses and using standard pass for gmail account if it's important)

**Comment by sameersbn** [comment]
Looks like a DNS resolution error.

**Comment by sameersbn** [comment]
@gkostyanikov any update on this? Please close the issue if you got the issue resolved.

**Comment by gkostyanikov** [comment]
Solved it by pulling today latest gitlab image and following all previous steps in exact order. Seems like the problem was with previous image.
