### ISSUE TITLE
Issue starting Unicorn due to git /tmp folder

### ISSUE THREAD

**Issue by pkallberg** [sameersbn/docker-gitlab#255]
I had an issue whereby Unicorn couldn't start - exiting with this error message:

```
root@6e07b7873b27:/home/git/gitlab# sudo -u git -H bundle exec unicorn_rails -c /home/git/gitlab/config/unicorn.rb -E production
/usr/lib/ruby/2.1.0/fileutils.rb:250:in `mkdir': File exists @ dir_s_mkdir - tmp/cache (Errno::EEXIST)
	from /usr/lib/ruby/2.1.0/fileutils.rb:250:in `fu_mkdir'
	from /usr/lib/ruby/2.1.0/fileutils.rb:224:in `block (2 levels) in mkdir_p'
	from /usr/lib/ruby/2.1.0/fileutils.rb:222:in `reverse_each'
	from /usr/lib/ruby/2.1.0/fileutils.rb:222:in `block in mkdir_p'
	from /usr/lib/ruby/2.1.0/fileutils.rb:208:in `each'
	from /usr/lib/ruby/2.1.0/fileutils.rb:208:in `mkdir_p'
	from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/unicorn-4.6.3/bin/unicorn_rails:202:in `block in <top (required)>'
	from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/unicorn-4.6.3/lib/unicorn/configurator.rb:83:in `call'
	from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/unicorn-4.6.3/lib/unicorn/configurator.rb:83:in `reload'
	from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/unicorn-4.6.3/lib/unicorn/configurator.rb:68:in `initialize'
	from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/unicorn-4.6.3/lib/unicorn/http_server.rb:108:in `new'
	from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/unicorn-4.6.3/lib/unicorn/http_server.rb:108:in `initialize'
	from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/unicorn-4.6.3/bin/unicorn_rails:209:in `new'
	from /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/unicorn-4.6.3/bin/unicorn_rails:209:in `<top (required)>'
	from /home/git/gitlab/vendor/bundle/ruby/2.1.0/bin/unicorn_rails:23:in `load'
	from /home/git/gitlab/vendor/bundle/ruby/2.1.0/bin/unicorn_rails:23:in `<main>'
```

Here is the Supervisord output:
```
root@766f78278237:/home/git/gitlab# /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf
2015-02-08 16:58:34,494 CRIT Supervisor running as root (no user in config file)
2015-02-08 16:58:34,495 WARN Included extra file "/etc/supervisor/conf.d/sidekiq.conf" during parsing
2015-02-08 16:58:34,495 WARN Included extra file "/etc/supervisor/conf.d/sshd.conf" during parsing
2015-02-08 16:58:34,496 WARN Included extra file "/etc/supervisor/conf.d/nginx.conf" during parsing
2015-02-08 16:58:34,496 WARN Included extra file "/etc/supervisor/conf.d/unicorn.conf" during parsing
2015-02-08 16:58:34,496 WARN Included extra file "/etc/supervisor/conf.d/cron.conf" during parsing
2015-02-08 16:58:34,524 INFO RPC interface 'supervisor' initialized
2015-02-08 16:58:34,524 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2015-02-08 16:58:34,525 INFO supervisord started with pid 348
2015-02-08 16:58:35,530 INFO spawned: 'sidekiq' with pid 351
2015-02-08 16:58:35,535 INFO spawned: 'unicorn' with pid 352
2015-02-08 16:58:35,541 INFO spawned: 'cron' with pid 353
2015-02-08 16:58:35,553 INFO spawned: 'nginx' with pid 354
2015-02-08 16:58:35,566 INFO spawned: 'sshd' with pid 356
2015-02-08 16:58:36,605 INFO success: sidekiq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-02-08 16:58:36,606 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-02-08 16:58:36,606 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-02-08 16:58:36,606 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-02-08 16:58:36,607 INFO success: sshd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2015-02-08 16:58:36,901 INFO exited: unicorn (exit status 1; not expected)
2015-02-08 16:58:37,905 INFO spawned: 'unicorn' with pid 365
2015-02-08 16:58:38,871 INFO exited: unicorn (exit status 1; not expected)
2015-02-08 16:58:39,875 INFO spawned: 'unicorn' with pid 368
2015-02-08 16:58:40,814 INFO exited: unicorn (exit status 1; not expected)
```

My solution has been to run this: `sudo mv /home/git/gitlab/tmp /home/git/gitlab/tmp_backup`. That folder gets created once Unicorn comes up. Has anyone else seen this?

**Comment by sameersbn** [comment]
@pkallberg This is probably because the permissions of the `tmp` directory were changed. Normally nothing like this will happen unless you manually change the ownership/permissions of the `tmp` directory or the `data` directory for that matter.

I recommend you run the container again in interactive mode with the `app:sanitize` command to make sure all files and folders have the correct permissions to avoid any problems

**Comment by pkallberg** [comment]
Thanks for your recommendation @sameersbn. This is the result of that command on a fresh container (no changes) running on 7.7.2:

```
root@8de59d0097c2:/app# ./init app:sanitize
Checking repository directories permissions...
Checking satellites directories permissions...
Checking uploads directory permissions...
Checking tmp directory permissions...
chmod: cannot access '/home/git/data/tmp/': No such file or directory
```

When I run the container it outputs the following, not sure if that may be related:

```
invoke-rc.d: policy-rc.d denied execution of restart.
```

Do you have any idea what may be going wrong? I'm surprised if no one else has seen this.

**Comment by sameersbn** [comment]
@pkallberg dude! you do not run this command on a fresh container. You run it only when you want to fix ownership/permissions issues on existing installation when something goes wrong. What you are doing here is asking the `init` script to fix permissions on a unpopulated `data` volume.

P.S. the recommended way of launching the `app:sanitize` command is:

```bash
docker run -it --rm [OPTIONS] sameersbn/gitlab:7.7.2 app:sanitize
```

**Comment by pkallberg** [comment]
Thanks @sameersbn, sorry if I'm not following recommended practices. I ran it the way you specified, but am getting the same result:

```
$ docker run -it --rm -e DB_HOST='xxx.xxx.xx.xxx' -e DB_NAME='xxx' -e DB_PASS='xxx' -e DB_TYPE='mysql' -e DB_USER='xxx' -e REDIS_HOST='xxx' -e REDIS_PORT='xxx' -e GITLAB_PORT='10080' -e GITLAB_SSH_PORT='10022' sameersbn/gitlab:7.7.2 app:sanitize
Creating SSH2 RSA key; this may take some time ...
Creating SSH2 DSA key; this may take some time ...
Creating SSH2 ECDSA key; this may take some time ...
Creating SSH2 ED25519 key; this may take some time ...
invoke-rc.d: policy-rc.d denied execution of restart.
Checking repository directories permissions...
Checking satellites directories permissions...
Checking uploads directory permissions...
Checking tmp directory permissions...
chmod: cannot access '/home/git/data/tmp/': No such file or directory
```

Apologies for the back and forth on this. Unless you can think of another solution, do you know if the command that I specified earlier (`sudo mv /home/git/gitlab/tmp /home/git/gitlab/tmp_backup`) would have any negative implications on the app?

**Comment by sameersbn** [comment]
@pkallberg the log indicates that you are running the container for the first time. In this case you do not need to use the `app:sanitize` option. Launch simply using 

```bash
docker run -it --rm -e DB_HOST='xxx.xxx.xx.xxx' -e DB_NAME='xxx' -e DB_PASS='xxx' -e DB_TYPE='mysql' -e DB_USER='xxx' -e REDIS_HOST='xxx' -e REDIS_PORT='xxx' -e GITLAB_PORT='10080' -e GITLAB_SSH_PORT='10022' sameersbn/gitlab:7.7.2
```

If you still have issue, please check if the following works

```bash
# start mysql container
docker run -it --rm --name=mysql \
-e 'DB_USER=gitlab' -e 'DB_PASS=secretpass' \
-e 'DB_NAME=gitlabhq_production' sameersbn/mysql

# start redis container
docker run -it --rm --name=redis sameersbn/redis

# start gitlab
docker run -it --rm \
--link mysql:mysql --link redis:redisio \
--publish 10080:80 --publish 10022:22 \
-e GITLAB_PORT='10080' -e GITLAB_SSH_PORT='10022' \
sameersbn/gitlab:7.2.2
```

If this does not work, then please state the host os and docker version in use.

**Comment by sameersbn** [comment]
@pkallberg Was your issue resolved?
