### ISSUE TITLE
Missing Rails.application.secrets.openid_connect_signing_key for production environment. rake aborted!

### ISSUE THREAD

**Issue by zengqingfu1442** [sameersbn/docker-gitlab#2561]
I have my own LDAP server, and I need to integrate LDAP with my new setup gitlab 14.10.1. How can I integrate my ldap server with gitlab? thanks.

**Comment by zengqingfu1442** [comment]
I use docker-compose to start gitlab 14.10.1, but came across this error,

> 2022-05-09 12:52:06,472 INFO success: gitaly entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-05-09 12:52:06,472 INFO success: puma entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-05-09 12:52:06,472 INFO success: gitlab-workhorse entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-05-09 12:52:06,472 INFO success: sidekiq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-05-09 12:52:06,472 INFO success: sshd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-05-09 12:52:06,472 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-05-09 12:52:06,472 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Missing Rails.application.secrets.openid_connect_signing_key for production environment. The secret will be generated and stored in config/secrets.yml.
rake aborted!
Psych::SyntaxError: (<unknown>): did not find expected key while parsing a block mapping at line 517 column 9
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:103:in `initialize'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:60:in `new'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:60:in `instance'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/settingslogic-2.0.9/lib/settingslogic.rb:37:in `[]'
/home/git/gitlab/config/initializers/1_settings.rb:8:in `<top (required)>'

**Comment by zengqingfu1442** [comment]
I have resolved, dont mind me...
