### ISSUE TITLE
Update documentation: for memory_constrained_envs

### ISSUE THREAD

**Issue by KES777** [sameersbn/docker-gitlab#2652]
https://docs.gitlab.com/omnibus/settings/memory_constrained_envs.html

```
Deprecations:
* gitaly['cgroups_count'] has been deprecated since 15.1 and will be removed in 16.0. Use `gitaly['cgroups_repositories_count']` instead.
* gitaly['cgroups_memory_enabled'] has been deprecated since 15.1 and will be removed in 16.0. Use `gitaly['cgroups_memory_bytes'] or gitaly['cgroups_repositories_memory_bytes'] instead.
* gitaly['cgroups_memory_limit'] has been deprecated since 15.1 and will be removed in 16.0. Use `gitaly['cgroups_memory_bytes'] or gitaly['cgroups_repositories_memory_bytes'] instead.
* gitaly['cgroups_cpu_enabled'] has been deprecated since 15.1 and will be removed in 16.0. Use `gitaly['cgroups_cpu_shares'] or gitaly['cgroups_repositories_cpu_shares'] instead.

```

**Comment by KES777** [comment]
Also after these changes:

`mkdir: cannot create directory '/sys/fs/cgroup/cpu': Read-only file system`

```
lib/gitlab/middleware/memory_report.rb:13:in `call'

lib/gitlab/middleware/speedscope.rb:13:in `call'

lib/gitlab/database/load_balancing/rack_middleware.rb:23:in `call'

lib/gitlab/jira/middleware.rb:19:in `call'

lib/gitlab/middleware/go.rb:20:in `call'

lib/gitlab/etag_caching/middleware.rb:21:in `call'

lib/gitlab/middleware/query_analyzer.rb:11:in `block in call'

lib/gitlab/database/query_analyzer.rb:37:in `within'

lib/gitlab/middleware/query_analyzer.rb:11:in `call'

lib/gitlab/middleware/multipart.rb:173:in `call'

lib/gitlab/middleware/read_only/controller.rb:50:in `call'

lib/gitlab/middleware/read_only.rb:18:in `call'

lib/gitlab/middleware/same_site_cookies.rb:27:in `call'

lib/gitlab/middleware/handle_malformed_strings.rb:21:in `call'

lib/gitlab/middleware/basic_health_check.rb:25:in `call'

lib/gitlab/middleware/handle_ip_spoof_attack_error.rb:25:in `call'

lib/gitlab/middleware/request_context.rb:21:in `call'

lib/gitlab/middleware/webhook_recursion_detection.rb:15:in `call'

config/initializers/fix_local_cache_middleware.rb:11:in `call'

lib/gitlab/middleware/compressed_json.rb:26:in `call'

lib/gitlab/middleware/rack_multipart_tempfile_factory.rb:19:in `call'

lib/gitlab/middleware/sidekiq_web_static.rb:20:in `call'

lib/gitlab/metrics/requests_rack_middleware.rb:77:in `call'

lib/gitlab/middleware/release_env.rb:13:in `call'

==> /var/log/gitlab/gitlab-workhorse/current <==

{"content_type":"text/html; charset=utf-8","correlation_id":"01GGCTXKFHM1MMX6B1HBQYDS34","duration_ms":178,"host":"office.black-list.info","level":"info","method":"GET","msg":"access","proto":"HTTP/1.1","referrer":"","remote_addr":"127.0.0.1:0","remote_ip":"127.0.0.1","route":"","status":500,"system":"http","time":"2022-10-27T13:43:17Z","ttfb_ms":178,"uri":"/gitlab","user_agent":"Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0","written_bytes":3049}

==> /var/log/gitlab/nginx/gitlab_access.log <==

172.22.22.103 - - [27/Oct/2022:13:43:17 +0000] "GET /gitlab HTTP/1.1" 500 3049 "" "Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0" -

==> /var/log/gitlab/nginx/gitlab_error.log <==

2022/10/27 13:43:17 [error] 865#0: *29 open() "/var/opt/gitlab/nginx/html/favicon.ico" failed (2: No such file or directory), client: 172.22.22.103, server: office.black-list.info, request: "GET /favicon.ico HTTP/1.1", host: "office.black-list.info", referrer: "http://office.black-list.info/gitlab"

==> /var/log/gitlab/nginx/gitlab_access.log <==

172.22.22.103 - - [27/Oct/2022:13:43:17 +0000] "GET /favicon.ico HTTP/1.1" 404 1625 "http://office.black-list.info/gitlab" "Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0" 1.99

==> /var/log/gitlab/gitaly/current <==

mkdir: cannot create directory '/sys/fs/cgroup/cpu': Read-only file system

==> /var/log/gitlab/gitlab-rails/production.log <==

[ActionDispatch::HostAuthorization::DefaultResponseApp] Blocked host: localhost

==> /var/log/gitlab/gitaly/current <==

mkdir: cannot create directory '/sys/fs/cgroup/cpu': Read-only file system

mkdir: cannot create directory '/sys/fs/cgroup/cpu': Read-only file system

mkdir: cannot create directory '/sys/fs/cgroup/cpu': Read-only file system

mkdir: cannot create directory '/sys/fs/cgroup/cpu': Read-only file system

mkdir: cannot create directory '/sys/fs/cgroup/cpu': Read-only file system

mkdir: cannot create directory '/sys/fs/cgroup/cpu': Read-only file system

mkdir: cannot create directory '/sys/fs/cgroup/cpu': Read-only file system

mkdir: cannot create directory '/sys/fs/cgroup/cpu': Read-only file system

mkdir: cannot create directory '/sys/fs/cgroup/cpu': Read-only file system

mkdir: cannot create directory '/sys/fs/cgroup/cpu': Read-only file system

==> /var/log/gitlab/gitlab-rails/production.log <==

[ActionDispatch::HostAuthorization::DefaultResponseApp] Blocked host: localhost

==> /var/log/gitlab/gitaly/current <==

mkdir: cannot create directory '/sys/fs/cgroup/cpu': Read-only file system

mkdir: cannot create directory '/sys/fs/cgroup/cpu': Read-only file system

mkdir: cannot create directory '/sys/fs/cgroup/cpu': Read-only file system

mkdir: cannot create directory '/sys/fs/cgroup/cpu': Read-only file system

mkdir: cannot create directory '/sys/fs/cgroup/cpu': Read-only file system

mkdir: cannot create directory '/sys/fs/cgroup/cpu': Read-only file system

mkdir: cannot create directory '/sys/fs/cgroup/cpu': Read-only file system

mkdir: cannot create directory '/sys/fs/cgroup/cpu': Read-only file system

mkdir: cannot create directory '/sys/fs/cgroup/cpu': Read-only file system

mkdir: cannot create directory '/sys/fs/cgroup/cpu': Read-only file system

==> /var/log/gitlab/gitlab-rails/production.log <==

[ActionDispatch::HostAuthorization::DefaultResponseApp] Blocked host: localhost

==> /var/log/gitlab/gitaly/current <==

mkdir: cannot create directory '/sys/fs/cgroup/cpu': Read-only file system

mkdir: cannot create directory '/sys/fs/cgroup/cpu': Read-only file system

==> /var/log/gitlab/gitlab-workhorse/current <==

{"error":"keywatcher: pubsub receive: EOF","level":"error","msg":"","time":"2022-10-27T13:43:40Z"}

{"address":"/var/opt/gitlab/redis/redis.socket","level":"info","msg":"redis: dialing","network":"unix","time":"2022-10-27T13:43:40Z"}

==> /var/log/gitlab/gitaly/current <==

mkdir: cannot create directory '/sys/fs/cgroup/cpu': Read-only file system

mkdir: cannot create directory '/sys/fs/cgroup/cpu': Read-only file system

mkdir: cannot create directory '/sys/fs/cgroup/cpu': Read-only file system

mkdir: cannot create directory '/sys/fs/cgroup/cpu': Read-only file system

mkdir: cannot create directory '/sys/fs/cgroup/cpu': Read-only file system

mkdir: cannot create directory '/sys/fs/cgroup/cpu': Read-only file system

mkdir: cannot create directory '/sys/fs/cgroup/cpu': Read-only file system

mkdir: cannot create directory '/sys/fs/cgroup/cpu': Read-only file system

==> /var/log/gitlab/gitlab-rails/production.log <==

[ActionDispatch::HostAuthorization::DefaultResponseApp] Blocked host: localhost

==> /var/log/gitlab/gitaly/current <==

mkdir: cannot create directory '/sys/fs/cgroup/cpu': Read-only file system

mkdir: cannot create directory '/sys/fs/cgroup/cpu': Read-only file system

mkdir: cannot create directory '/sys/fs/cgroup/cpu': Read-only file system

mkdir: cannot create directory '/sys/fs/cgroup/cpu': Read-only file system

mkdir: cannot create directory '/sys/fs/cgroup/cpu': Read-only file system
```

Commenting out next lines, helps:
```
# gitaly['cgroups_repositories_count'] = 2
# gitaly['cgroups_mountpoint'] = '/sys/fs/cgroup'
# gitaly['cgroups_hierarchy_root'] = 'gitaly'
# gitaly['cgroups_repositories_memory_bytes'] = 500000
# gitaly['cgroups_repositories_cpu_shares'] = 512
```

**Comment by kkimurak** [comment]
You are posting issue to wrong place. You may be using `gitlab/gitlab-ce` or `gitlab/gitlab-ee`, not `sameersbn/gitlab` that is developped here.  
The documentation is managed on https://gitlab.com/gitlab-org/omnibus-gitlab (file : doc/settings/memory_constrained_envs.md) , so please submit a request to update document there.

You may want to refer those issues / merge requests.

- The issue that deprecates those configurations  
  https://gitlab.com/gitlab-org/omnibus-gitlab/-/issues/6828 
- A merge request to update document to use `cgroups_repositories_memory_bytes` instead of deprecated `cgroups_repositories_memory_limit`
  https://gitlab.com/gitlab-org/omnibus-gitlab/-/merge_requests/6388

**Comment by KES777** [comment]
Ok, thank you
