### ISSUE TITLE
sameersbn/gitlab:15.5.2 NoMethodError: undefined method `prometheus_metrics_enabled' for #<ApplicationSetting:0x0000559794882990>

### ISSUE THREAD

**Issue by djl-kara** [sameersbn/docker-gitlab#2660]
[root@gitlab-new gitlab]# docker run --name gitlab2 -d     --link gitlab-postgresql:postgresql --link gitlab-redis_2:redisio     --publish 10022:22 --publish 80:80 --env 'GITLAB_PORT=80' --env 'GITLAB_SSH_PORT=10022' --env 'GITLAB_BACKUP_SCHEDULE=daily' --env 'GITLAB_BACKUP_TIME=15:00' --env 'GITLAB_BACKUP_EXPIRY=259200' --env 'GITLAB_HOST=100.86.17.13'  --env 'GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alpha-numeric-string'     --env 'GITLAB_SECRETS_SECRET_KEY_BASE=long-and-random-alpha-numeric-string'     --env 'GITLAB_SECRETS_OTP_KEY_BASE=long-and-random-alpha-numeric-string'   --env 'GITLAB_MONITORING_SIDEKIQ_EXPORTER_ENABLED=false'   --volume /data/srv/docker/gitlab/gitlab:/home/git/data     sameersbn/gitlab:15.5.2
1c83df56d3af5075098f94457589fadefa54d7fc72aa14f9ebbc1ad622d07b94
[root@gitlab-new gitlab]#
[root@gitlab-new gitlab]# docker ps -a
CONTAINER ID   IMAGE                              COMMAND                  CREATED          STATUS          PORTS                                                                                 NAMES
1c83df56d3af   sameersbn/gitlab:15.5.2            "/sbin/entrypoint.sh…"   4 seconds ago    Up 2 seconds    0.0.0.0:80->80/tcp, :::80->80/tcp, 443/tcp, 0.0.0.0:10022->22/tcp, :::10022->22/tcp   gitlab2
6232bdc26b73   redis:6.2                          "docker-entrypoint.s…"   34 seconds ago   Up 33 seconds   6379/tcp                                                                              gitlab-redis_2
5a300efd7736   sameersbn/postgresql:12-20200524   "/sbin/entrypoint.sh"    4 hours ago      Up 4 hours      5432/tcp                                                                              gitlab-postgresql
235dd61694a4   sameersbn/postgresql:12-20200524   "/sbin/entrypoint.sh"    5 hours ago      Up 5 hours      0.0.0.0:15432->5432/tcp, :::15432->5432/tcp                                           gitlab-postgresql_3
f25d4ef4c67f   gitlab/gitlab-ce:8.16.3-ce.1       "/assets/wrapper"        23 hours ago     Created                                                                                               gitlab-test-8-16-3
[root@gitlab-new gitlab]# docker logs gitlab2 -f
Loading /etc/docker-gitlab/runtime/env-defaults
Initializing logdir...
Initializing datadir...
Container TimeZone -> UTC
Installing configuration templates...
Configuring gitlab...
Configuring gitlab::database
Configuring gitlab::redis
Configuring gitlab::actioncable
Configuring gitlab::secrets...
Configuring gitlab::sidekiq...
Configuring gitlab::gitaly...
Configuring gitlab::monitoring...
Configuring gitlab::gitlab-workhorse...
Configuring gitlab::puma...
Configuring gitlab::timezone...
Configuring gitlab::rack_attack...
Configuring gitlab::ci...
Configuring gitlab::artifacts...
Configuring gitlab::packages...
Configuring gitlab::terraform_state...
Configuring gitlab::lfs...
Configuring gitlab::uploads...
Configuring gitlab::mattermost...
Configuring gitlab::project_features...
Configuring gitlab::oauth...
Configuring gitlab::ldap...
Configuring gitlab::cron_jobs...
Configuring gitlab::backups...
Configuring gitlab::backups::schedule...
Configuring gitlab::registry...
Configuring gitlab::pages...
Configuring gitlab::sentry...
Configuring gitlab::content_security_policy...
Configuring gitlab-shell...
Configuring nginx...
Configuring nginx::gitlab...
Migrating database...
2022-11-11 07:42:35,692 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2022-11-11 07:42:35,693 INFO Included extra file "/etc/supervisor/conf.d/cron.conf" during parsing
2022-11-11 07:42:35,693 INFO Included extra file "/etc/supervisor/conf.d/gitaly.conf" during parsing
2022-11-11 07:42:35,693 INFO Included extra file "/etc/supervisor/conf.d/gitlab-workhorse.conf" during parsing
2022-11-11 07:42:35,693 INFO Included extra file "/etc/supervisor/conf.d/groups.conf" during parsing
2022-11-11 07:42:35,693 INFO Included extra file "/etc/supervisor/conf.d/mail_room.conf" during parsing
2022-11-11 07:42:35,693 INFO Included extra file "/etc/supervisor/conf.d/nginx.conf" during parsing
2022-11-11 07:42:35,693 INFO Included extra file "/etc/supervisor/conf.d/puma.conf" during parsing
2022-11-11 07:42:35,693 INFO Included extra file "/etc/supervisor/conf.d/sidekiq.conf" during parsing
2022-11-11 07:42:35,693 INFO Included extra file "/etc/supervisor/conf.d/sshd.conf" during parsing
2022-11-11 07:42:35,698 INFO RPC interface 'supervisor' initialized
2022-11-11 07:42:35,698 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2022-11-11 07:42:35,699 INFO supervisord started with pid 731
2022-11-11 07:42:36,702 INFO spawned: 'gitaly' with pid 751
2022-11-11 07:42:36,705 INFO spawned: 'puma' with pid 752
2022-11-11 07:42:36,708 INFO spawned: 'gitlab-workhorse' with pid 753
2022-11-11 07:42:36,712 INFO spawned: 'sidekiq' with pid 754
2022-11-11 07:42:36,716 INFO spawned: 'sshd' with pid 755
2022-11-11 07:42:36,735 INFO spawned: 'nginx' with pid 762
2022-11-11 07:42:36,740 INFO spawned: 'cron' with pid 765
2022-11-11 07:42:38,145 INFO success: gitaly entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-11-11 07:42:38,145 INFO success: puma entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-11-11 07:42:38,146 INFO success: gitlab-workhorse entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-11-11 07:42:38,146 INFO success: sidekiq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-11-11 07:42:38,146 INFO success: sshd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-11-11 07:42:38,146 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-11-11 07:42:38,146 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
 2022-11-11 07:43:12,898 INFO exited: puma (exit status 1; not expected)
2022-11-11 07:43:13,107 INFO spawned: 'puma' with pid 865
2022-11-11 07:43:13,197 INFO exited: sidekiq (exit status 1; not expected)
/home/git/gitlab/lib/gitlab/instrumentation/redis.rb:9: warning: already initialized constant Gitlab::Instrumentation::Redis::ActionCable
/home/git/gitlab/lib/gitlab/instrumentation/redis.rb:9: warning: previous definition of ActionCable was here
2022-11-11 07:43:14,198 INFO success: puma entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2022-11-11 07:43:14,201 INFO spawned: 'sidekiq' with pid 866
rake aborted!
NoMethodError: undefined method `prometheus_metrics_enabled' for #<ApplicationSetting:0x0000556131c87a20>
Did you mean?  prometheus_metrics_dir
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activemodel-6.1.6.1/lib/active_model/attribute_methods.rb:469:in `method_missing'
/home/git/gitlab/lib/gitlab/current_settings.rb:32:in `method_missing'
/home/git/gitlab/lib/gitlab/metrics/prometheus.rb:99:in `prometheus_metrics_enabled_unmemoized'
/home/git/gitlab/lib/gitlab/metrics/prometheus.rb:24:in `block in prometheus_metrics_enabled?'
/home/git/gitlab/lib/gitlab/utils/strong_memoize.rb:44:in `strong_memoize'
/home/git/gitlab/lib/gitlab/metrics/prometheus.rb:23:in `prometheus_metrics_enabled?'
/home/git/gitlab/lib/gitlab/metrics/prometheus.rb:91:in `provide_metric'
/home/git/gitlab/lib/gitlab/metrics/prometheus.rb:82:in `safe_provide_metric'
/home/git/gitlab/lib/gitlab/metrics/prometheus.rb:56:in `gauge'
/home/git/gitlab/lib/gitlab/database/load_balancing/host_list.rb:13:in `initialize'
/home/git/gitlab/lib/gitlab/database/load_balancing/load_balancer.rb:25:in `new'
/home/git/gitlab/lib/gitlab/database/load_balancing/load_balancer.rb:25:in `initialize'
/home/git/gitlab/lib/gitlab/database/load_balancing/setup.rb:64:in `new'
/home/git/gitlab/lib/gitlab/database/load_balancing/setup.rb:64:in `load_balancer'
/home/git/gitlab/lib/gitlab/database/load_balancing/setup.rb:48:in `setup_connection_proxy'
/home/git/gitlab/lib/gitlab/database/load_balancing/setup.rb:18:in `setup'
/home/git/gitlab/config/initializers/load_balancing.rb:24:in `block in <top (required)>'
/home/git/gitlab/config/initializers/load_balancing.rb:16:in `each'
/home/git/gitlab/config/initializers/load_balancing.rb:16:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/railties-6.1.6.1/lib/rails/engine.rb:681:in `load'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/railties-6.1.6.1/lib/rails/engine.rb:681:in `block in load_config_initializer'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/notifications.rb:205:in `instrument'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/railties-6.1.6.1/lib/rails/engine.rb:680:in `load_config_initializer'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/railties-6.1.6.1/lib/rails/engine.rb:634:in `block (2 levels) in <class:Engine>'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/railties-6.1.6.1/lib/rails/engine.rb:633:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/railties-6.1.6.1/lib/rails/engine.rb:633:in `block in <class:Engine>'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/railties-6.1.6.1/lib/rails/initializable.rb:32:in `instance_exec'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/railties-6.1.6.1/lib/rails/initializable.rb:32:in `run'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/railties-6.1.6.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/railties-6.1.6.1/lib/rails/initializable.rb:50:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/railties-6.1.6.1/lib/rails/initializable.rb:50:in `tsort_each_child'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/railties-6.1.6.1/lib/rails/initializable.rb:60:in `run_initializers'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/railties-6.1.6.1/lib/rails/application.rb:391:in `initialize!'
/home/git/gitlab/config/environment.rb:7:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/dependencies.rb:332:in `block in require'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/dependencies.rb:299:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.6.1/lib/active_support/dependencies.rb:332:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/railties-6.1.6.1/lib/rails/application.rb:367:in `require_environment!'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/railties-6.1.6.1/lib/rails/application.rb:533:in `block in run_tasks_blocks'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/sentry-ruby-core-5.1.1/lib/sentry/rake.rb:24:in `execute'
/home/git/gitlab/vendor/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => db:migrate => db:load_config => environment
(See full trace by running task with --trace)

How to solve?

**Comment by frenchbeard** [comment]
If you really attempted a direct upgrade from 8.X to 15.5.2, the error is expected. You should follow the upgrade paths presented in the Gitlab documentation [here](https://docs.gitlab.com/ee/update/#upgrade-paths).
Since the error seems to have happened before actually migrating the db, you should be able to follow the upgrade path directly without issue.
