### ISSUE TITLE
where are the automated backup files ?

### ISSUE THREAD

**Issue by gillbates** [sameersbn/docker-gitlab#2799]
Hi,

I've setup these env variables ...

```
      GITLAB_BACKUP_SCHEDULE: daily
      GITLAB_BACKUP_TIME: 11:50
      GITLAB_BACKUP_EXPIRY: 86400
```
and it seemed the backup process is executed when I checked from process list using ps aux.
during the process, there are directories db and repositories generated in backup folder.
But nothing left after a while in backup folder,

any logs I could check where are wrong?

thx in advance!

**Comment by kkimurak** [comment]
You can see the backup log file is placed on `/var/log/gitlab/gitlab/gitlab/gitlab-backup.log` (and unzipped old log files `.log.1` or gzipped one like `~.log.2.gz`).  
You can also check `/home/git/gitlab/log`, this is symlink for `/var/log/gitlab/gitlab`.

**Comment by kkimurak** [comment]
You may also refer to #2790 .

**Comment by gillbates** [comment]
> /var/log/gitlab/gitlab/gitlab/

```
rake aborted!
Errno::ENOENT: No such file or directory @ rb_check_realpath_internal - /home/git/data/shared/ci_secure_files
/home/git/gitlab/lib/backup/files.rb:156:in `realpath'
/home/git/gitlab/lib/backup/files.rb:156:in `app_files_realpath'
/home/git/gitlab/lib/backup/files.rb:46:in `dump'
/home/git/gitlab/lib/backup/manager.rb:71:in `run_create_task'
/home/git/gitlab/lib/backup/manager.rb:222:in `block in run_all_create_tasks'
/home/git/gitlab/lib/backup/manager.rb:221:in `each_key'
/home/git/gitlab/lib/backup/manager.rb:221:in `run_all_create_tasks'
/home/git/gitlab/lib/backup/manager.rb:47:in `create'
/home/git/gitlab/lib/tasks/gitlab/backup.rake:13:in `block in create_backup'
/home/git/gitlab/lib/tasks/gitlab/backup.rake:62:in `lock_backup'
/home/git/gitlab/lib/tasks/gitlab/backup.rake:10:in `create_backup'
/home/git/gitlab/lib/tasks/gitlab/backup.rake:101:in `block (3 levels) in <top (required)>'
/home/git/gitlab/vendor/bundle/ruby/3.0.0/gems/sentry-ruby-5.8.0/lib/sentry/rake.rb:26:in `execute'
/home/git/gitlab/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
Tasks: TOP => gitlab:backup:create
(See full trace by running task with --trace)
2023-07-09 12:06:48 +0800 -- Deleting tar staging files ...
2023-07-09 12:06:48 +0800 -- Cleaning up /home/git/data/backups/db
2023-07-09 12:06:48 +0800 -- Cleaning up /home/git/data/backups/repositories
2023-07-09 12:06:51 +0800 -- Cleaning up /home/git/data/backups/uploads.tar.gz
2023-07-09 12:06:51 +0800 -- Cleaning up /home/git/data/backups/builds.tar.gz
2023-07-09 12:06:51 +0800 -- Cleaning up /home/git/data/backups/artifacts.tar.gz
2023-07-09 12:06:51 +0800 -- Cleaning up /home/git/data/backups/pages.tar.gz
2023-07-09 12:06:51 +0800 -- Cleaning up /home/git/data/backups/lfs.tar.gz
2023-07-09 12:06:51 +0800 -- Cleaning up /home/git/data/backups/terraform_state.tar.gz
2023-07-09 12:06:51 +0800 -- Cleaning up /home/git/data/backups/packages.tar.gz
2023-07-09 12:06:51 +0800 -- Deleting tar staging files ... done
2023-07-09 12:06:51 +0800 -- Deleting backups/tmp ...
2023-07-09 12:06:51 +0800 -- Deleting backups/tmp ... done
2023-07-09 12:06:51 +0800 -- Deleting backup and restore PID file ... done
```

@kkimurak its fresh installed sameersbn/gitlab:16.1.0 with just a few repos, anywhere I could fix this?

**Comment by kkimurak** [comment]
@gillbates Then its the case https://github.com/sameersbn/docker-gitlab/issues/2790#issuecomment-1612370904 works for you - add environment variable `GITLAB_BACKUP_SKIP=ci_secure_files`.

**Comment by gillbates** [comment]
> 

done, thx man!!!
