### ISSUE TITLE
Backups not functioning in v16.8.1

### ISSUE THREAD

**Issue by danyill** [sameersbn/docker-gitlab#2900]
I recently migrated my instance to v16.8.1 from v14.9.2 which appears to have gone quite well.

However I have noticed that daily backups no longer function (no backups, nothing uploaded to the GCS bucket) which I'm quite keen to remediate. 
There have not been any changes in my docker-compose file which are relevant to this (database upgrades to PostgreSQL 14, otherwise just Gitlab container upgrades, all configuration parameters have remained the same).

My configuration is something like this (taken from the running container with `env | grep BACKUP`):

```
GITLAB_BACKUP_SCHEDULE=daily
GCS_BACKUP_BUCKET=gitlab-docker-backups
GCS_BACKUP_SECRET_ACCESS_KEY=<redacted>
GCS_BACKUP_ACCESS_KEY_ID=<redacted>
GITLAB_BACKUP_TIME=01:00
GCS_BACKUPS=true
```

AFAICT we do backups using a rake command (as per the [docs](https://github.com/sameersbn/docker-gitlab?tab=readme-ov-file#creating-backups))

I log in to the container and attempt to run this manually:

    $ docker-compose exec gitlab bash
    $ sudo -u git rake gitlab:backup:create

Which provides me with the following:

```bash
root@7d80927e75ad:/home/git/gitlab/bin# sudo -u git rake gitlab:backup:create
(in /home/git/gitlab)
rake aborted!
LoadError: cannot load such file -- sigdump/setup
/home/git/gitlab/config/application.rb:17:in `<top (required)>'
<internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/home/git/gitlab/Rakefile:9:in `<top (required)>'
(See full trace by running task with --trace)
```

With the trace flag:

```bash
root@7d80927e75ad:/home/git/gitlab/bin# sudo -u git rake gitlab:backup:create --trace
(in /home/git/gitlab)
rake aborted!
LoadError: cannot load such file -- sigdump/setup
/usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.5.4/lib/bundler/runtime.rb:60:in `require'
/usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.5.4/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
/usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.5.4/lib/bundler/runtime.rb:55:in `each'
/usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.5.4/lib/bundler/runtime.rb:55:in `block in require'
/usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.5.4/lib/bundler/runtime.rb:44:in `each'
/usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.5.4/lib/bundler/runtime.rb:44:in `require'
/usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.5.4/lib/bundler.rb:187:in `require'
/home/git/gitlab/config/application.rb:17:in `<top (required)>'
<internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
<internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
/home/git/gitlab/Rakefile:9:in `<top (required)>'
/usr/local/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load'
/usr/local/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load_rakefile'
/usr/local/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:710:in `raw_load_rakefile'
/usr/local/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:104:in `block in load_rakefile'
/usr/local/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:103:in `load_rakefile'
/usr/local/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:82:in `block in run'
/usr/local/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
/usr/local/lib/ruby/gems/3.1.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/bin/rake:25:in `load'
/usr/local/bin/rake:25:in `<main>'
```

I'm a little out of practice with Ruby so I'm not sure whether this is a good sign or not:

```bash
root@7d80927e75ad:/home/git/gitlab# cat Gemfile | grep sigdump
  gem 'sigdump', '~> 0.2.4', require: 'sigdump/setup' # rubocop:todo Gemfile/MissingFeatureCategory
```

Running this suggests this gem is not installed:

```
root@7d80927e75ad:/home/git/gitlab# gem list -i "^sigdump$"
false
root@7d80927e75ad:/home/git/gitlab# gem list -i "^sigdump/setup$"
false
```

I'd be grateful for any advice/suggestions.

It is somewhat tempting to do a `gem install` or `bundle install` inside the container, however it seems this is part of the build process (as it must be) and I'm reluctant to hack it too much.

For reference:

https://github.com/sameersbn/docker-gitlab/blob/cfad6e95c4c601f6930d5e58c0ceda02600553e6/assets/build/install.sh#L180-L192

**Comment by danyill** [comment]
After more carefully examining the crontab for the git user, the command run is:

    cd /home/git/gitlab && bundle exec rake gitlab:backup:create SKIP= RAILS_ENV=production

This runs fine up until the end and then I get:

```
2024-02-10 15:47:32 +1300 -- Cleaning up /home/git/data/backups/packages.tar.gz
2024-02-10 15:47:32 +1300 -- Deleting tar staging files ... done
2024-02-10 15:47:32 +1300 -- Deleting backups/tmp ... 
2024-02-10 15:47:32 +1300 -- Deleting backups/tmp ... done
2024-02-10 15:47:32 +1300 -- Deleting backup and restore PID file ... done
rake aborted!
Errno::ENOENT: No such file or directory @ rb_check_realpath_internal - /home/git/data/shared/ci_secure_files
/home/git/gitlab/lib/backup/files.rb:156:in `realpath'
/home/git/gitlab/lib/backup/files.rb:156:in `app_files_realpath'
/home/git/gitlab/lib/backup/files.rb:46:in `dump'
/home/git/gitlab/lib/backup/manager.rb:71:in `run_create_task'
/home/git/gitlab/lib/backup/manager.rb:227:in `block in run_all_create_tasks'
/home/git/gitlab/lib/backup/manager.rb:226:in `each_key'
/home/git/gitlab/lib/backup/manager.rb:226:in `run_all_create_tasks'
/home/git/gitlab/lib/backup/manager.rb:47:in `create'
/home/git/gitlab/lib/tasks/gitlab/backup.rake:13:in `block in create_backup'
/home/git/gitlab/lib/tasks/gitlab/backup.rake:62:in `lock_backup'
/home/git/gitlab/lib/tasks/gitlab/backup.rake:10:in `create_backup'
/home/git/gitlab/lib/tasks/gitlab/backup.rake:101:in `block (3 levels) in <top (required)>'
/home/git/gitlab/vendor/bundle/ruby/3.1.0/gems/sentry-ruby-5.10.0/lib/sentry/rake.rb:26:in `execute'
/home/git/gitlab/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:25:in `load'
/usr/local/bin/bundle:25:in `<main>'
Tasks: TOP => gitlab:backup:create
(See full trace by running task with --trace)
git@7d80927e75ad:~/gitlab$ 
```

It seemed possible that making this directory would help so I did, and the backup functioned normally.

Happy for this issue to be closed unless there is some value in having the container automatically create this directory if it doesn't exist.

**Comment by kkimurak** [comment]
Thank you for your report but duplicate of #2790 for braked backup because of non existing directory `ci_secure_files`.

**Comment by danyill** [comment]
Oh quite right, thanks for the response, closing.
