### ISSUE TITLE
docker-composer not working

### ISSUE THREAD

**Issue by ninja-** [sameersbn/docker-gitlab#359]
I am having a problem running gitlab from docker-compose.
I am not lacking free ram for assets precompiling.

```
# docker-compose up          
Recreating gitlab3_postgresql_1...
Recreating 3cd6bb2d94_3cd6bb2d94_3cd6bb2d94_3cd6bb2d94_3cd6bb2d94_gitlab3_redis_1...
Recreating gitlab3_gitlab_1...
Attaching to gitlab3_postgresql_1, gitlab3_redis_1, gitlab3_gitlab_1
postgresql_1 | |------------------------------------------------------------------|
postgresql_1 | | PostgreSQL User: postgres, Password: phohm0eeXouqua              |
postgresql_1 | |                                                                  |
postgresql_1 | | To remove the PostgreSQL login credentials from the logs, please |
postgresql_1 | | make a note of password and then delete the file pwfile          |
postgresql_1 | | from the data store.                                             |
postgresql_1 | |------------------------------------------------------------------|
postgresql_1 | Creating user "gitlab"...
postgresql_1 | Creating database "gitlabhq_production"...
postgresql_1 | Granting access to database "gitlabhq_production" for user "gitlab"...
postgresql_1 | Starting PostgreSQL server...
postgresql_1 | 2015-06-25 02:21:30 UTC [29-1] LOG:  database system was shut down at 2015-06-25 02:21:30 UTC
postgresql_1 | 2015-06-25 02:21:30 UTC [28-1] LOG:  database system is ready to accept connections
postgresql_1 | 2015-06-25 02:21:30 UTC [33-1] LOG:  autovacuum launcher started
redis_1      |                 _._                                                  
redis_1      |            _.-``__ ''-._                                             
redis_1      |       _.-``    `.  `_.  ''-._           Redis 2.8.4 (00000000/0) 64 bit
redis_1      |   .-`` .-```.  ```\/    _.,_ ''-._                                   
redis_1      |  (    '      ,       .-`  | `,    )     Running in stand alone mode
redis_1      |  |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
redis_1      |  |    `-._   `._    /     _.-'    |     PID: 13
redis_1      |   `-._    `-._  `-./  _.-'    _.-'                                   
redis_1      |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
redis_1      |  |    `-._`-._        _.-'_.-'    |           http://redis.io        
redis_1      |   `-._    `-._`-.__.-'_.-'    _.-'                                   
redis_1      |  |`-._`-._    `-.__.-'    _.-'_.-'|                                  
redis_1      |  |    `-._`-._        _.-'_.-'    |                                  
redis_1      |   `-._    `-._`-.__.-'_.-'    _.-'                                   
redis_1      |       `-._    `-.__.-'    _.-'                                       
redis_1      |           `-._        _.-'                                           
redis_1      |               `-.__.-'                                               
redis_1      | 
gitlab_1     | SSL keys and certificates were not found.
gitlab_1     | Assuming that the container is running behind a HTTPS enabled load balancer.
redis_1      | [13] 25 Jun 02:21:30.188 # Server started, Redis version 2.8.4
redis_1      | [13] 25 Jun 02:21:30.189 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1      | [13] 25 Jun 02:21:30.189 * DB loaded from disk: 0.000 seconds
redis_1      | [13] 25 Jun 02:21:30.189 * The server is now ready to accept connections on port 6379
redis_1      | [13] 25 Jun 02:21:30.189 * The server is now ready to accept connections at /var/run/redis/redis.sock
gitlab_1     | Waiting for database server to accept connections
gitlab_1     | Migrating database...
gitlab_1     | Compiling assets. Please be patient, this could take a while...

gitlab3_gitlab_1 exited with code 1
Gracefully stopping... (press Ctrl+C again to force)
Stopping gitlab3_redis_1...
Stopping gitlab3_postgresql_1...

```

**Comment by ninja-** [comment]
gitlab_1     | I, [2015-06-25T04:41:37.996512 #294]  INFO -- : Writing /home/git/gitlab/public/assets/white-scheme-preview-a483b8ac27efa3b1969ef0f20b9a5aa1.png
gitlab_1     | I, [2015-06-25T04:41:58.154373 #294]  INFO -- : Writing /home/git/gitlab/public/assets/application-1ce55d9deac8430f385ec7b4c70a6ba6.js
gitlab_1     | rake aborted!
gitlab_1     | Sass::SyntaxError: Invalid CSS after "...140ed079e1f75b1": expected ")", was ".eot?v=4.2.0');"
gitlab_1     |   (in /home/git/gitlab/app/assets/stylesheets/application.scss:13)
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/font-awesome-rails-4.2.0.0/app/assets/stylesheets/font-awesome.css.erb:13
gitlab_1     | /home/git/gitlab/app/assets/stylesheets/application.scss:37
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sass-3.2.19/lib/sass/scss/parser.rb:1147:in `expected'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sass-3.2.19/lib/sass/script/lexer.rb:206:in `expected!'

**Comment by sameersbn** [comment]
@ninja- If you are sure that this is not a RAM issue, then try deleting the `tmp` directory in the data volume before relaunching. Also make sure that the container can connect to the internet (i think it is required for the assets compilation, i am not sure though)

**Comment by ninja-** [comment]
@sameersbn I started from a clean container and it's the same error. The error I pasted is after deleting >/dev/null from the scripts.

**Comment by ninja-** [comment]
The problem was a leftover ' in gitlab relative url...such a stupid mistake. Sorry.

**Comment by ninja-** [comment]
If you could help with one more issue that would be great. After copying the old database it was migrated from 9.1 to 9.4 but the gitlab instance works like the database is empty (no accounts).
