### ISSUE TITLE
Stop and restart gitlab sometimes failed

### ISSUE THREAD

**Issue by linlinlinlin** [sameersbn/docker-gitlab#381]
Using *docker-compose stop* and *docker-compose start* gitlab.
Sometimes gitlab container have these logs:

gitlab image version: sameersbn/gitlab:7.11.4

```
gitlab_1     | Waiting for database server to accept connections...
gitlab_1     | Migrating database...
gitlab_1     | rake aborted!
gitlab_1     | StandardError: An error has occurred, this and all later migrations canceled:
gitlab_1     | 
gitlab_1     | PG::Error: ERROR:  relation "forked_project_links" already exists


.........
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/transactions.rb:208:in `transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/migration.rb:1044:in `ddl_transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/migration.rb:959:in `block in migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/migration.rb:955:in `each'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/migration.rb:955:in `migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/migration.rb:814:in `up'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/migration.rb:792:in `migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.9/lib/active_record/railties/databases.rake:34:in `block (2 levels) in <top (required)>'
gitlab_1     | Tasks: TOP => db:migrate
gitlab_1     | (See full trace by running task with --trace)
gitlab1_gitlab_1 exited with code 1

```

**Comment by sameersbn** [comment]
sorry for not replying earlier. did you manage to resolve the issue?
