### ISSUE TITLE
cannot enable incoming email feature

### ISSUE THREAD

**Issue by thewilli** [sameersbn/docker-gitlab#474]
I'm trying to enable the incoming email feature in the Gitlab 8.0.5 container, and set the *IMAP_USER, IMAP_PASS, IMAP_HOST, and GITLAB_INCOMING_MAIL* properties. Unfortunately I get the following apparently related errors in the sidekiq.log log file.

Do you have any idea what the problem might be?

```
2015-10-19T15:43:13.861Z 504 TID-gq9uo PostReceive JID- INFO: done: 0.141 sec
2015-10-19T15:43:13.977Z 504 TID-g7kjs ProjectCacheWorker JID-a8d4aa14c28e55277bcd8f26 INFO: done: 0.124 sec
2015-10-19T22:53:39.940Z 504 TID-g7kjs Sidekiq::Extensions::DelayedMailer JID-cd8d9fb19181311a7107e9c0 INFO: start
2015-10-19T22:53:39.941Z 504 TID-g7kjs Sidekiq::Extensions::DelayedMailer JID-cd8d9fb19181311a7107e9c0 INFO: Adding dead Sidekiq::Extensions::DelayedMailer job cd8d9fb19181311a7107e9c0
2015-10-19T22:53:39.945Z 504 TID-g7kjs Sidekiq::Extensions::DelayedMailer JID-cd8d9fb19181311a7107e9c0 INFO: fail: 0.004 sec
2015-10-19T22:53:39.947Z 504 TID-g7kjs WARN: {"retry"=>true, "queue"=>"default", "class"=>"Sidekiq::Extensions::DelayedMailer", "args"=>["---\n- !ruby/class 'Notify'\n- :send\n- - :note_snippet_email\n - 2\n - 694\n"], "jid"=>"cd8d9fb19181311a7107e9c0", "enqueued_at"=>1443527048.209832, "error_message"=>"undefined method `note_snippet_email' for Notify:Class", "error_class"=>"NoMethodError", "failed_at"=>1443527060.322258, "retry_count"=>25, "retried_at"=>1445295219.9411435}
2015-10-19T22:53:39.947Z 504 TID-g7kjs WARN: undefined method `note_snippet_email' for Notify:Class
2015-10-19T22:53:39.947Z 504 TID-g7kjs WARN: /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/attr_encrypted-1.3.4/lib/attr_encrypted.rb:259:in `method_missing'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/actionmailer-4.1.12/lib/action_mailer/base.rb:553:in `method_missing'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/extensions/action_mailer.rb:17:in `public_send'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/extensions/action_mailer.rb:17:in `perform'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:75:in `execute_job'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:52:in `block (2 levels) in process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:127:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
/home/git/gitlab/lib/gitlab/sidekiq_middleware/memory_killer.rb:17:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidetiq-0.6.3/lib/sidetiq/middleware/history.rb:8:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/logging.rb:22:in `with_context'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:132:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:132:in `invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:51:in `block in process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:98:in `stats'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:50:in `process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
2015-10-20T07:10:03.812Z 504 TID-g7kjs PostReceive JID- INFO: start
```

**Comment by sameersbn** [comment]
No idea. Tested it locally and seems to work. Are you using the latest version `8.0.5-1`?

**Comment by sameersbn** [comment]
ps. please try with newer versions of the image to see if it resolves the issue.
