### ISSUE TITLE
Self Signed Certificates web hook isn't working

### ISSUE THREAD

**Issue by junxy** [sameersbn/docker-gitlab#475]
Version: `sameersbn/gitlab:8.0.0` - `quay.io/sameersbn/gitlab:8.0.5-1`
 (The same environment configuration. version: `sameersbn/gitlab:7.14.3` is working )

curl test is passed,
```
$ docker exec -it gitlab bash
root@225aa:/home/git/gitlab# curl -I https://ci.self-signed-cert.com/
HTTP/1.1 200 OK
```

Gitlab Log:
```
OpenSSL::SSL::SSLError (SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read server certificate B: certificate verify failed):
app/models/hooks/web_hook.rb:39:in `execute'
app/services/test_hook_service.rb:4:in `execute'
app/controllers/projects/hooks_controller.rb:28:in `test'
```

**Comment by sameersbn** [comment]
did you add the certificate key to ca.crt? see https://github.com/sameersbn/docker-gitlab#installing-trusted-ssl-server-certificates

**Comment by junxy** [comment]
Yes

```
$ ls gitlab/certs/
ca.crt  dhparam.pem  gitlab.crt  gitlab.key
```

```
root@222c1cd17368:/home/git/gitlab# curl -v https://ci.self-signed-cert.com/gitlab/ping
* Hostname was NOT found in DNS cache
*   Trying 192.168.1.199...
* Connected to ci.self-signed-cert.com (192.168.1.199) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using ECDHE-RSA-AES256-GCM-SHA384
* Server certificate:
* 	 subject: C=CN; ST=HuNan; O=self-signed-cert; OU=Oc; CN=ci.self-signed-cert.com
* 	 start date: 2015-07-14 08:50:50 GMT
* 	 expire date: 2016-07-13 08:50:50 GMT
* 	 common name: ci.self-signed-cert.com (matched)
* 	 issuer: C=CN; ST=HuNan; L=ChangSha; O=self-signed-cert; OU=self-signed-cert Root CA
* 	 SSL certificate verify ok.
> GET /gitlab/ping HTTP/1.1
> User-Agent: curl/7.35.0
> Host: ci.self-signed-cert.com
> Accept: */*
>
< HTTP/1.1 200 OK
* Server nginx is not blacklisted
< Server: nginx
< Date: Thu, 22 Oct 2015 01:50:26 GMT
< Content-Type: text/html;charset=UTF-8
< Content-Length: 37
< Connection: keep-alive
< X-Content-Type-Options: nosniff
< Set-Cookie: JSESSIONID.6ca14ef5=1omhkpbuwstwb1em1r3wlfnubk;Path=/;Secure;HttpOnly
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< X-Frame-Options: sameorigin
< X-XSS-Protection: 1; mode=block
< X-Frame-Options: DENY
<
* Connection #0 to host ci.self-signed-cert.com left intact
Gitlab Web Hook is up and running :-)
```

**Comment by junxy** [comment]
GitLab bug reported at  https://github.com/gitlabhq/gitlabhq/issues/9304
