### ISSUE TITLE
SSH operations don't work

### ISSUE THREAD

**Issue by blufor** [sameersbn/docker-gitlab#497]
Hello, the problem from #363 might be presenting itself again, however, it's different this time.

Main issue:
```
λ bell git clone -v ssh://git@git.prz:10022/orchestration/puppet.git
```
```
Cloning into 'puppet'...
Connection closed by 172.17.1.69
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

real	2m0.100s
user	0m0.000s
sys	    0m0.004s
cmd	    git clone -v ssh://git@git.prz:10022/orchestration/puppet.git
code	128
```
as you can see, SSH closes the connection after 120s. After inspecting the SSH log, nothing serious seems to stand out (maybe that is the problem):

```
Set /proc/self/oom_score_adj to 0
Connection from 10.4.0.1 port 42683 on 192.168.168.4 port 22
```

that's it from server-side...

client in DEBUG1 says just this:
```
OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /home/blufor/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Connecting to git.prz [172.17.1.69] port 10022.
debug1: Connection established.
debug1: identity file /home/blufor/.ssh/id_rsa type -1
debug1: identity file /home/blufor/.ssh/id_rsa-cert type -1
debug1: identity file /home/blufor/.ssh/id_dsa type -1
debug1: identity file /home/blufor/.ssh/id_dsa-cert type -1
debug1: identity file /home/blufor/.ssh/id_ecdsa type -1
debug1: identity file /home/blufor/.ssh/id_ecdsa-cert type -1
debug1: identity file /home/blufor/.ssh/id_ed25519 type -1
debug1: identity file /home/blufor/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.3
debug1: Remote protocol version 2.0, remote software version OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.3
debug1: match: OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.3 pat OpenSSH_6.6.1* compat 0x04000000
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: server->client aes128-ctr hmac-md5-etm@openssh.com zlib@openssh.com
debug1: kex: client->server aes128-ctr hmac-md5-etm@openssh.com zlib@openssh.com
debug1: sending SSH2_MSG_KEX_ECDH_INIT
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
### 120s of nothingness ###
Connection closed by 172.17.1.69
```

Some more-or-less important notes:
- I'm admin + owner of the repository I'm trying to clone
- My public key is imported (my private key is on YubiKey though, but ssh-agent should handle that)
- Docker version is 1.9.0
- Docker-Gitlab is 8.1.4
- The problematic keyfile permissions from #363 are OK in this case.
- The containers are provisioned by Puppet
- NGINX on the Docker host is doing the SSL part as a proxy
- Repositories have been brought in their bare state from previous (and quite old Gitlab installation, non-dockerized). I took care for all the namespaces (users+groups) to exist before moving the repo sources into the proper place and running (from within the running container) ```bundle exec rake gitlab:import:repos``` - which worked seamlessly.
- Gitlab is ran like this:
```
λ docker inspect gitlab
```
```
[
{
    "Id": "0477a1b2ab375f34ede2b70557046a5ab4e9fd11d061eb1529fc2c42fe5b4d0d",
    "Created": "2015-11-16T23:39:19.35215111Z",
    "Path": "/sbin/entrypoint.sh",
    "Args": [
        "app:start"
    ],
    "State": {
        "Status": "running",
        "Running": true,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 23695,
        "ExitCode": 0,
        "Error": "",
        "StartedAt": "2015-11-16T23:39:19.721271267Z",
        "FinishedAt": "0001-01-01T00:00:00Z"
    },
    "Image": "f819f70c97f312fc5ed1a61bec37c552bce3ddf85e0a4bdb74410f7a7c030160",
    "ResolvConfPath": "/var/lib/docker/containers/0477a1b2ab375f34ede2b70557046a5ab4e9fd11d061eb1529fc2c42fe5b4d0d/resolv.conf",
    "HostnamePath": "/var/lib/docker/containers/0477a1b2ab375f34ede2b70557046a5ab4e9fd11d061eb1529fc2c42fe5b4d0d/hostname",
    "HostsPath": "/var/lib/docker/containers/0477a1b2ab375f34ede2b70557046a5ab4e9fd11d061eb1529fc2c42fe5b4d0d/hosts",
    "LogPath": "/var/lib/docker/containers/0477a1b2ab375f34ede2b70557046a5ab4e9fd11d061eb1529fc2c42fe5b4d0d/0477a1b2ab375f34ede2b70557046a5ab4e9fd11d061eb1529fc2c42fe5b4d0d-json.log",
    "Name": "/gitlab",
    "RestartCount": 0,
    "Driver": "aufs",
    "ExecDriver": "native-0.2",
    "MountLabel": "",
    "ProcessLabel": "",
    "AppArmorProfile": "",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": [
            "/srv/gitlab:/home/git/data"
        ],
        "ContainerIDFile": "",
        "LxcConf": [],
        "Memory": 0,
        "MemoryReservation": 0,
        "MemorySwap": 0,
        "KernelMemory": 0,
        "CpuShares": 0,
        "CpuPeriod": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "CpuQuota": 0,
        "BlkioWeight": 0,
        "OomKillDisable": false,
        "MemorySwappiness": -1,
        "Privileged": false,
        "PortBindings": {
            "22/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "10022"
                }
            ],
            "80/tcp": [
                {
                    "HostIp": "",
                    "HostPort": "10080"
                }
            ]
        },
        "Links": [
            "/postgres:/gitlab/postgresql",
            "/redis:/gitlab/redisio"
        ],
        "PublishAllPorts": false,
        "Dns": null,
        "DnsOptions": null,
        "DnsSearch": null,
        "ExtraHosts": null,
        "VolumesFrom": null,
        "Devices": [],
        "NetworkMode": "bridge",
        "IpcMode": "",
        "PidMode": "",
        "UTSMode": "",
        "CapAdd": null,
        "CapDrop": null,
        "GroupAdd": null,
        "RestartPolicy": {
            "Name": "no",
            "MaximumRetryCount": 0
        },
        "SecurityOpt": null,
        "ReadonlyRootfs": false,
        "Ulimits": null,
        "LogConfig": {
            "Type": "json-file",
            "Config": {}
        },
        "CgroupParent": "",
        "ConsoleSize": [
            0,
            0
        ],
        "VolumeDriver": ""
    },
    "GraphDriver": {
        "Name": "aufs",
        "Data": null
    },
    "Mounts": [
        {
            "Source": "/srv/gitlab",
            "Destination": "/home/git/data",
            "Mode": "",
            "RW": true
        },
        {
            "Name": "7cf674ce3aa79b3857a26a27f9683036efa9a90eb4d37b5c36233ddd5b801b73",
            "Source": "/var/lib/docker/volumes/7cf674ce3aa79b3857a26a27f9683036efa9a90eb4d37b5c36233ddd5b801b73/_data",
            "Destination": "/var/log/gitlab",
            "Driver": "local",
            "Mode": "",
            "RW": true
        }
    ],
    "Config": {
        "Hostname": "0477a1b2ab37",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "ExposedPorts": {
            "22/tcp": {},
            "443/tcp": {},
            "80/tcp": {}
        },
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "USERMAP_UID=600",
            "USERMAP_GID=600",
            "SMTP_ENABLED=true",
            "SMTP_STARTTLS=false",
            "SMTP_HOST=mother.prz",
            "SMTP_PORT=25",
            "GITLAB_HOST=git.prz",
            "GITLAB_PORT=443",
            "GITLAB_SSH_PORT=10022",
            "GITLAB_HTTPS=true",
            "GITLAB_ROOT_PASSWORD=XXXXXXXXXXXXXXXX",
            "GITLAB_EMAIL=repo@xxxxxxxx",
            "GITLAB_EMAIL_DISPLAY_NAME=GitLab",
            "GITLAB_BACKUPS=daily",
            "UNICORN_WORKERS=4",
            "GITLAB_SECRETS_DB_KEY_BASE=XXXXXXXXXXXXXXXXXXXXXXX",
            "SSL_SELF_SIGNED=true",
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
            "GITLAB_VERSION=8.1.4",
            "GITLAB_SHELL_VERSION=2.6.5",
            "GITLAB_GIT_HTTP_SERVER_VERSION=0.3.0",
            "GITLAB_USER=git",
            "GITLAB_HOME=/home/git",
            "GITLAB_LOG_DIR=/var/log/gitlab",
            "SETUP_DIR=/var/cache/gitlab",
            "RAILS_ENV=production",
            "GITLAB_INSTALL_DIR=/home/git/gitlab",
            "GITLAB_SHELL_INSTALL_DIR=/home/git/gitlab-shell",
            "GITLAB_GIT_HTTP_SERVER_INSTALL_DIR=/home/git/gitlab-git-http-server",
            "GITLAB_DATA_DIR=/home/git/data"
        ],
        "Cmd": [
            "app:start"
        ],
        "Image": "sameersbn/gitlab:8.1.4",
        "Volumes": {
            "/home/git/data": {},
            "/var/log/gitlab": {}
        },
        "WorkingDir": "/home/git/gitlab",
        "Entrypoint": [
            "/sbin/entrypoint.sh"
        ],
        "OnBuild": null,
        "Labels": {},
        "StopSignal": "SIGTERM"
    },
    "NetworkSettings": {
        "Bridge": "",
        "SandboxID": "415f86118e8695a657f1f3853951bbf782b1d582ef4dea3a3b210889bea8dd6d",
        "HairpinMode": false,
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "Ports": {
            "22/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "10022"
                }
            ],
            "443/tcp": null,
            "80/tcp": [
                {
                    "HostIp": "0.0.0.0",
                    "HostPort": "10080"
                }
            ]
        },
        "SandboxKey": "/var/run/docker/netns/415f86118e86",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null,
        "EndpointID": "749d367d236bd20014371acc96a2eae661a67c0340d571f6838966d6447642bb",
        "Gateway": "192.168.168.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "IPAddress": "192.168.168.4",
        "IPPrefixLen": 24,
        "IPv6Gateway": "",
        "MacAddress": "02:42:c0:a8:a8:04",
        "Networks": {
            "bridge": {
                "EndpointID": "749d367d236bd20014371acc96a2eae661a67c0340d571f6838966d6447642bb",
                "Gateway": "192.168.168.1",
                "IPAddress": "192.168.168.4",
                "IPPrefixLen": 24,
                "IPv6Gateway": "",
                "GlobalIPv6Address": "",
                "GlobalIPv6PrefixLen": 0,
                "MacAddress": "02:42:c0:a8:a8:04"
            }
        }
    }
}
]
```

**Comment by sameersbn** [comment]
I am not sure what the problem could be. But can you try running the container with the `app:sanitize` command to make sure that are no permission issues at play?

**Comment by sameersbn** [comment]
also can you take a look at this issue in case there are some similarities with your environment https://bugs.launchpad.net/ubuntu/+source/openssh/+bug/1254085

**Comment by blufor** [comment]
Thank you, I've probably found where the problem is - ```su git -c "bundle exec rake gitlab:check"``` says something interesting:

```
/usr/lib/ruby/2.1.0/logger.rb:592:in `initialize': Permission denied @ rb_sysopen - /var/log/gitlab/gitlab-shell/gitlab-shell.log (Errno::EACCES)
	from /usr/lib/ruby/2.1.0/logger.rb:592:in `open'
	from /usr/lib/ruby/2.1.0/logger.rb:592:in `open_logfile'
	from /usr/lib/ruby/2.1.0/logger.rb:549:in `initialize'
	from /usr/lib/ruby/2.1.0/logger.rb:318:in `new'
	from /usr/lib/ruby/2.1.0/logger.rb:318:in `initialize'
	from /home/git/gitlab-shell/lib/gitlab_logger.rb:15:in `new'
	from /home/git/gitlab-shell/lib/gitlab_logger.rb:15:in `<top (required)>'
	from /home/git/gitlab-shell/lib/gitlab_net.rb:6:in `require_relative'
	from /home/git/gitlab-shell/lib/gitlab_net.rb:6:in `<top (required)>'
	from /home/git/gitlab-shell/bin/check:4:in `require_relative'
	from /home/git/gitlab-shell/bin/check:4:in `<main>'
gitlab-shell self-check failed
  Try fixing it:
  Make sure GitLab is running;
  Check the gitlab-shell configuration file:
  sudo -u git -H editor /home/git/gitlab-shell/config.yml
  Please fix the error above and rerun the checks.
```

i fixed the ownership manually (it was root's instead of git's) but didn't help. So tried your solution:

```
Adapting uid and gid for git:git to 600:600
SSL keys and certificates were not found.
Assuming that the container is running behind a HTTPS enabled load balancer.
Checking repository directories permissions...
Checking builds directories permissions...
Checking uploads directory permissions...
Creating gitlab-shell hooks...
Executing gitlab:env:info raketask...

System information
System:		Ubuntu 14.04
Current User:	git
Using RVM:	no
Ruby Version:	2.1.7p400
Gem Version:	2.2.5
Bundler Version:1.10.6
Rake Version:	10.4.2
Sidekiq Version:3.3.0

GitLab information
Version:	8.1.4
Revision:	295b1f0
Directory:	/home/git/gitlab
DB Adapter:	postgresql
URL:		https://git.prz
HTTP Clone URL:	https://git.prz/some-group/some-project.git
SSH Clone URL:	ssh://git@git.prz:10022/some-group/some-project.git
Using LDAP:	no
Using Omniauth:	no

GitLab Shell
Version:	2.6.5
Repositories:	/home/git/data/repositories/
Hooks:		/home/git/gitlab-shell/hooks/
Git:		/usr/bin/git
```
Unfortunately, no change :(

I'll try to make SSHd a bit more verbose and update on progress...

**Comment by blufor** [comment]
ok, so here's DEBUG2:

```
debug1: Forked child 466.
Set /proc/self/oom_score_adj to 0
debug1: rexec start in 6 out 6 newsock 6 pipe 8 sock 9
debug1: inetd sockets after dupping: 5, 5
Connection from 10.4.0.1 port 43805 on 192.168.168.4 port 22
debug1: Client protocol version 2.0; client software version OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.3
debug1: match: OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.3 pat OpenSSH_6.6.1* compat 0x04000000
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.3
debug2: fd 5 setting O_NONBLOCK
debug1: list_hostkey_types: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ssh-ed25519
debug1: SSH2_MSG_KEXINIT sent
### connection close happens here after 120s
```
one interesting thing i've found - /home/git/.ssh/authorized_keys has only one key (a deploy key). there are no traces of my key... wtf? :)

**Comment by blufor** [comment]
ok, I've rebuild the authorized_keys file, which looks OK now, but the problem still persists. honestly, according to SSH logs from both sides it looks more like and issue with the network... Not sure if there's anything wrong, I'll do some dumping. Here's the full command used to start the container:

```
docker run \
  --net bridge \
  -m 0b \
  --detach=true \
  --link postgres:postgresql \
  --link redis:redisio \
  -e USERMAP_UID=600 \
  -e USERMAP_GID=600 \
  -e SMTP_ENABLED=true \
  -e SMTP_STARTTLS=false \
  -e SMTP_HOST=mother.prz \
  -e SMTP_PORT=25 \
  -e GITLAB_HOST=git.prz \
  -e GITLAB_PORT=443 \
  -e GITLAB_SSH_PORT=10022 \
  -e GITLAB_HTTPS=true \
  -e GITLAB_ROOT_PASSWORD=XXXXXXXXXXX \
  -e GITLAB_EMAIL=repo@xxxxxxxx \
  -e GITLAB_EMAIL_DISPLAY_NAME='GitLab' \
  -e GITLAB_BACKUPS=daily \
  -e UNICORN_WORKERS=4 \
  -e GITLAB_SECRETS_DB_KEY_BASE=XXXXXXXXXXXXXXXXXXXXX \
  -e SSL_SELF_SIGNED=true \
  -p 10080:80 \
  -p 10022:22 \
  -v /srv/gitlab:/home/git/data  \
  --name gitlab \
  sameersbn/gitlab:8.1.4
```

and the iptables-save:

```
# Generated by iptables-save v1.4.21 on Tue Nov 17 16:19:59 2015
*nat
:PREROUTING ACCEPT [62:3720]
:INPUT ACCEPT [40:2400]
:OUTPUT ACCEPT [379:22460]
:POSTROUTING ACCEPT [410:24320]
:DOCKER - [0:0]
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A POSTROUTING -s 192.168.168.0/24 ! -o docker0 -j MASQUERADE
-A POSTROUTING -s 192.168.168.5/32 -d 192.168.168.5/32 -p tcp -m tcp --dport 5000 -j MASQUERADE
-A POSTROUTING -s 192.168.168.4/32 -d 192.168.168.4/32 -p tcp -m tcp --dport 80 -j MASQUERADE
-A POSTROUTING -s 192.168.168.4/32 -d 192.168.168.4/32 -p tcp -m tcp --dport 22 -j MASQUERADE
-A DOCKER ! -i docker0 -p tcp -m tcp --dport 5000 -j DNAT --to-destination 192.168.168.5:5000
-A DOCKER ! -i docker0 -p tcp -m tcp --dport 10080 -j DNAT --to-destination 192.168.168.4:80
-A DOCKER ! -i docker0 -p tcp -m tcp --dport 10022 -j DNAT --to-destination 192.168.168.4:22
COMMIT
# Completed on Tue Nov 17 16:19:59 2015
# Generated by iptables-save v1.4.21 on Tue Nov 17 16:19:59 2015
*filter
:INPUT ACCEPT [16915:15572864]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [14753:14943998]
:DOCKER - [0:0]
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A DOCKER -d 192.168.168.5/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 5000 -j ACCEPT
-A DOCKER -d 192.168.168.4/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 80 -j ACCEPT
-A DOCKER -d 192.168.168.4/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 22 -j ACCEPT
COMMIT
# Completed on Tue Nov 17 16:19:59 2015
```

**Comment by sameersbn** [comment]
will try out your command.

**Comment by sameersbn** [comment]
noticed `--net bridge` in the docker run. did you intend to use this option?

**Comment by sameersbn** [comment]
for testing I used the following docker-compose.yml file

```yaml
postgresql:
  image: sameersbn/postgresql:latest
  environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
  volumes:
    - /tmp/gitlab/postgresql:/var/lib/postgresql
gitlab:
  image: sameersbn/gitlab:8.1.4
  links:
    - redis:redisio
    - postgresql:postgresql
  ports:
    - "10080:80"
    - "10022:22"
  environment:
    - DEBUG=1
    - USERMAP_UID=600
    - USERMAP_GID=600

    - GITLAB_SECRETS_DB_KEY_BASE=qK9nvsxks7hfqzCgbxqq7fWxJRhMNfthPfXRvhtdWwzXXpVzWdJMqMjck9dsadSad

    - GITLAB_HOST=git.example.com
    - GITLAB_PORT=10080
    - GITLAB_SSH_PORT=10022
  volumes:
    - /tmp/gitlab/gitlab:/home/git/data
redis:
  image: sameersbn/redis:latest
  volumes:
    - /tmp/gitlab/redis:/var/lib/redis
```

I had no problems using git over ssh. Can you try using the default docker0 network instead of the bridge network. I too believe this could be a networking issue.

**Comment by blufor** [comment]
What puppet does is just use of vanilla docker. It's basically a wrapper library which generates init script for each container you define in puppet DSL. The command I sent you is what actually gets executed.

Also ```--net bridge``` is default, and means use of docker's bridge (whatever you name it, docker0 by default)

I've had another idea that's always a good choice, when weird stuff happens and shouldn't - look into kernlog - and it proved itself :)

```
[110296.985717] ------------[ cut here ]------------
[110296.985737] WARNING: CPU: 1 PID: 0 at /build/buildd/linux-3.13.0/net/core/dev.c:2222 skb_warn_bad_offload+0xcd/0xda()
[110296.985739] : caps=(0x0000000207db78e9, 0x0000000000000000) len=1354 data_len=1226 gso_size=1288 gso_type=5 ip_summed=1
[110296.985740] Modules linked in: xt_nat xt_tcpudp veth xt_conntrack ipt_MASQUERADE iptable_nat nf_conntrack_ipv4 nf_defrag_ipv4 nf_nat_ipv4 xt_addrtype iptable_filter ip_tables x_tables nf_nat nf_conntrack bridge stp llc aufs joydev hid_generic kvm_intel kvm usbhid cirrus ttm hid serio_raw drm_kms_helper drm syscopyarea sysfillrect sysimgblt mac_hid i2c_piix4 lp parport psmouse floppy pata_acpi
[110296.985770] CPU: 1 PID: 0 Comm: swapper/1 Tainted: G        W    3.13.0-24-generic #47-Ubuntu
[110296.985771] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS Bochs 01/01/2011
[110296.985773]  0000000000000009 ffff88023fd03a60 ffffffff81715ac4 ffff88023fd03aa8
[110296.985775]  ffff88023fd03a98 ffffffff810676bd ffff8800a10d7300 ffff88023096e000
[110296.985777]  0000000000000005 0000000000000001 ffff8800a10d7300 ffff88023fd03af8
[110296.985785] Call Trace:
[110296.985786]  <IRQ>  [<ffffffff81715ac4>] dump_stack+0x45/0x56
[110296.985794]  [<ffffffff810676bd>] warn_slowpath_common+0x7d/0xa0
[110296.985796]  [<ffffffff8106772c>] warn_slowpath_fmt+0x4c/0x50
[110296.985801]  [<ffffffff81362e63>] ? ___ratelimit+0x93/0x100
[110296.985802]  [<ffffffff817189d2>] skb_warn_bad_offload+0xcd/0xda
[110296.985806]  [<ffffffff8161be59>] __skb_gso_segment+0x79/0xb0
[110296.985808]  [<ffffffff8161c14a>] dev_hard_start_xmit+0x18a/0x560
[110296.985810]  [<ffffffff8161c838>] __dev_queue_xmit+0x318/0x500
[110296.985814]  [<ffffffff816244ca>] ? neigh_add_timer+0x1a/0x40
[110296.985815]  [<ffffffff8161ca30>] dev_queue_xmit+0x10/0x20
[110296.985817]  [<ffffffff81624f0b>] neigh_resolve_output+0x11b/0x220
[110296.985820]  [<ffffffff81654dc0>] ip_finish_output+0x1b0/0x3b0
[110296.985822]  [<ffffffff81656328>] ip_output+0x58/0x90
[110296.985823]  [<ffffffff816522ab>] ip_forward_finish+0x8b/0x170
[110296.985825]  [<ffffffff816526e5>] ip_forward+0x355/0x410
[110296.985829]  [<ffffffff816503fd>] ip_rcv_finish+0x7d/0x350
[110296.985831]  [<ffffffff81650d48>] ip_rcv+0x298/0x3d0
[110296.985833]  [<ffffffff8161a906>] __netif_receive_skb_core+0x666/0x840
[110296.985835]  [<ffffffff8161aaf8>] __netif_receive_skb+0x18/0x60
[110296.985836]  [<ffffffff8161ab63>] netif_receive_skb+0x23/0x90
[110296.985840]  [<ffffffff815216e4>] virtnet_poll+0x4d4/0x850
[110296.985842]  [<ffffffff8161aee2>] net_rx_action+0x152/0x250
[110296.985845]  [<ffffffff8106caec>] __do_softirq+0xec/0x2c0
[110296.985847]  [<ffffffff8106d035>] irq_exit+0x105/0x110
[110296.985851]  [<ffffffff817287d6>] do_IRQ+0x56/0xc0
[110296.985855]  [<ffffffff8171df6d>] common_interrupt+0x6d/0x6d
[110296.985856]  <EOI>  [<ffffffff8104f596>] ? native_safe_halt+0x6/0x10
[110296.985863]  [<ffffffff8101c5ff>] default_idle+0x1f/0xc0
[110296.985865]  [<ffffffff8101cec6>] arch_cpu_idle+0x26/0x30
[110296.985867]  [<ffffffff810beb85>] cpu_startup_entry+0xc5/0x290
[110296.985872]  [<ffffffff81040fc8>] start_secondary+0x218/0x2c0
[110296.985873] ---[ end trace 811e30919579a412 ]---
```

And that sadly points me here https://bugzilla.kernel.org/show_bug.cgi?id=82471

Needless to say, it is outside the scope of this project. Thank you for your help.

**Comment by blufor** [comment]
Solved by ```ethtool -K <ixgbe_card_name> lro off``` ;)
