### ISSUE TITLE
500 Please contact your GitLab administrator if this problem persists.

### ISSUE THREAD

**Issue by xigang** [sameersbn/docker-gitlab#501]
redis:
~~~
docker run \
	--name=gitlab_redis \
	-tid \
	sameersbn/redis:latest
~~~

mysql:
~~~
docker run \
	--name=gitlab_mysql \
	-tid \
	-e 'DB_NAME=gitlabhq_production' \
	-e 'DB_USER=gitlab' \
	-e 'DB_PASS=password' \
	-v /opt/gitlab/mysql:/var/lib/mysql \
	sameersbn/mysql:latest
~~~

gitlab:

~~~
docker run \
	--name='gitlab' \
	-itd \
	--link gitlab_mysql:mysql \
	--link gitlab_redis:redisio \
	--publish 10022:22 --publish 10080:80 \
    --env 'GITLAB_PORT=10080' --env 'GITLAB_SSH_PORT=10022' \
	-e 'GITLAB_PORT=80' \
	-e 'GITLAB_SSH_PORT=22' \
	-e 'LDAP_ENABLED=true' \
	-e 'LDAP_HOST=192.168.1.1' \
	-e 'LDAP_PORT=389' \
	-e 'LDAP_UID=sAMAccountName' \
	-e 'LDAP_METHOD=plain' \
	-e 'LDAP_BIND_DN=test@example.com' \
	-e 'LDAP_PASS=passwd' \
	-e 'LDAP_BASE=OU=example_users,DC=example-family,DC=com' \
	-e 'LDAP_ACTIVE_DIRECTORY=true' \
	-e 'LDAP_ALLOW_USERNAME_OR_EMAIL_LOGIN=false' \
	-e 'GITLAB_HOST=gitlab.example.com' \
	-e 'SMTP_ENABLED=true' \
	-e 'SMTP_DOMAIN=example.com' \
	-e 'SMTP_HOST=192.168.1.2' \
	-e 'SMTP_PORT=25' \
	-e 'SMTP_STARTTLS=false' \
	-v /var/run/docker.sock:/run/docker.sock \
	-v $(which docker):/bin/docker \
	-v /opt/gitlab/data:/home/git/data \
	-v /opt/gitlab/log:/var/log/gitlab \
	sameersbn/gitlab:7.14.3
~~~
after point my  browser(chrome) to http://boot2docker:10080 and login using the default username and password:

username: root
password: 5iveL!fe

this is my  production.log content:
~~~~
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"xEDXeCvgNxOALR2UobS40s772NE49qTpGv4tDOMT8JY=", "user"=>{"login"=>"root", "password"=>"[FILTERED]", "remember_me"=>"0"}}
Completed 500 Internal Server Error in 92ms

NameError (undefined local variable or method `extern_uid' for #<User:0x00000006288128>):
  app/models/user.rb:409:in `ldap_user?'
  app/controllers/application_controller.rb:197:in `check_password_expiration'

~~~

After I deploy to log in, show 500, which is the content of the log, I should be how to solve? thx.

**Comment by sameersbn** [comment]
can you drop the LDAP parameters and try again. Maybe LDAP config is not right.
You may also try removing the docker images and repulling it.

**Comment by xigang** [comment]
thx.I have solved this problem：）

**Comment by sameersbn** [comment]
for the benefit of other users can you please mention what was the resolution?

**Comment by xigang** [comment]
Because I use MySQL no perfect solution to my problem, I chose postgresql.

postgresql:
~~~

docker run --name gitlab-postgresql -d \
    --env 'DB_NAME=gitlabhq_production' \
    --env 'DB_USER=gitlab' --env 'DB_PASS=password' \
    --volume /srv/docker/gitlab/postgresql:/var/lib/postgresql \
    sameersbn/postgresql:9.4-8

~~~

redis:

~~~
docker run --name gitlab-redis -d \
    --volume /srv/docker/gitlab/redis:/var/lib/redis \
    sameersbn/redis:latest
~~~


gitlab:

~~~
docker run --name gitlab -d \
    --link gitlab-postgresql:postgresql --link gitlab-redis:redisio \
    --publish 10022:22 --publish 10080:80 \
    --env 'GITLAB_PORT=10080' --env 'GITLAB_SSH_PORT=10022' \
    --env 'GITLAB_SECRETS_DB_KEY_BASE=long-and-random-alpha-numeric-string' \
    --volume /srv/docker/gitlab/gitlab:/home/git/data \
    sameersbn/gitlab:7.14.3

~~~

After that, gitlab will work. I'll try Mysql again. =='

**Comment by sameersbn** [comment]
PostgreSQL recommended for GitLab http://doc.gitlab.com/ce/install/database_mysql.html. Please consider using postgresql to avoid problems in the future.
