### ISSUE TITLE
Upgrade fails from 8.1.4 to 8.2.2 

### ISSUE THREAD

**Issue by jessy1092** [sameersbn/docker-gitlab#529]
First time, I upgrade failed from `8.0.4` to `8.2.1-1`. (postgresql: `9.4-3` to `9.4-8`) But I forgot to store log.

Secound time, I upgrade success from `8.0.4` to `8.1.4` (postgresql: `9.4-3` to `9.4-7`)

Third time, I upgrade failed from `8.1.4` to `8.2.2`  (postgresql: `9.4-7` to `9.4-8`)

Here is docker-compose logs.
```
gitlab_1     | Migrating database...
postgresql_1 | ERROR:  relation "lfs_objects" already exists
postgresql_1 | STATEMENT:  CREATE TABLE "lfs_objects" ("id" serial primary key, "oid" character varying(255) NOT NULL, "size" integer NOT NULL, "created_at" timestamp, "updated_at" timestamp)
gitlab_1     | rake aborted!
gitlab_1     | StandardError: An error has occurred, this and all later migrations canceled:
gitlab_1     |
gitlab_1     | PG::DuplicateTable: ERROR:  relation "lfs_objects" already exists
gitlab_1     | : CREATE TABLE "lfs_objects" ("id" serial primary key, "oid" character varying(255) NOT NULL, "size" integer NOT NULL, "created_at" timestamp, "updated_at" timestamp) /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/postgresql/database_statements.rb:128:in `async_exec'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/postgresql/database_statements.rb:128:in `block in execute'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract_adapter.rb:378:in `block in log'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract_adapter.rb:372:in `log'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/postgresql/database_statements.rb:127:in `execute'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/schema_statements.rb:205:in `create_table'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:656:in `block in method_missing'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:628:in `block in say_with_time'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:628:in `say_with_time'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:648:in `method_missing'
gitlab_1     | /home/git/gitlab/db/migrate/20151103134857_create_lfs_objects.rb:3:in `change'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:602:in `exec_migration'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:586:in `block (2 levels) in migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:585:in `block in migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:584:in `migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:759:in `migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/transactions.rb:208:in `transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:1044:in `ddl_transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:959:in `block in migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:955:in `each'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:955:in `migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:814:in `up'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:792:in `migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/railties/databases.rake:34:in `block (2 levels) in <top (required)>'
gitlab_1     | ActiveRecord::StatementInvalid: PG::DuplicateTable: ERROR:  relation "lfs_objects" already exists
gitlab_1     | : CREATE TABLE "lfs_objects" ("id" serial primary key, "oid" character varying(255) NOT NULL, "size" integer NOT NULL, "created_at" timestamp, "updated_at" timestamp)
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/postgresql/database_statements.rb:128:in `async_exec'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/postgresql/database_statements.rb:128:in `block in execute'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract_adapter.rb:378:in `block in log'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract_adapter.rb:372:in `log'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/postgresql/database_statements.rb:127:in `execute'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/schema_statements.rb:205:in `create_table'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:656:in `block in method_missing'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:628:in `block in say_with_time'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:628:in `say_with_time'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:648:in `method_missing'
gitlab_1     | /home/git/gitlab/db/migrate/20151103134857_create_lfs_objects.rb:3:in `change'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:602:in `exec_migration'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:586:in `block (2 levels) in migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:585:in `block in migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:584:in `migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:759:in `migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/transactions.rb:208:in `transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:1044:in `ddl_transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:959:in `block in migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:955:in `each'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:955:in `migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:814:in `up'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:792:in `migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/railties/databases.rake:34:in `block (2 levels) in <top (required)>'
gitlab_1     | PG::DuplicateTable: ERROR:  relation "lfs_objects" already exists
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/postgresql/database_statements.rb:128:in `async_exec'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/postgresql/database_statements.rb:128:in `block in execute'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract_adapter.rb:378:in `block in log'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.12/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract_adapter.rb:372:in `log'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/postgresql/database_statements.rb:127:in `execute'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/schema_statements.rb:205:in `create_table'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:656:in `block in method_missing'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:628:in `block in say_with_time'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:628:in `say_with_time'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:648:in `method_missing'
gitlab_1     | /home/git/gitlab/db/migrate/20151103134857_create_lfs_objects.rb:3:in `change'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:602:in `exec_migration'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:586:in `block (2 levels) in migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:585:in `block in migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:294:in `with_connection'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:584:in `migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:759:in `migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:1044:in `block in ddl_transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/transactions.rb:208:in `transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:1044:in `ddl_transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:959:in `block in migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:955:in `each'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:955:in `migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:814:in `up'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/migration.rb:792:in `migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.12/lib/active_record/railties/databases.rake:34:in `block (2 levels) in <top (required)>'
gitlab_1     | Tasks: TOP => db:migrate
gitlab_1     | (See full trace by running task with --trace)
gitlab_gitlab_1 exited with code 0

```

**Comment by sameersbn** [comment]
@jessy1092 I was not able to reproduce this issue. I was also able to go straight from 8.0.4 to 8.2.2. Here are commands i used:

Create 8.0.4 container:

```bash
wget https://raw.githubusercontent.com/sameersbn/docker-gitlab/v8.0.4/docker-compose.yml -O docker-compose.yml
docker-compose up -d
```

Stop and upgrade to 8.2.2

```bash
docker-compose stop
docker-compose rm -fv

wget https://raw.githubusercontent.com/sameersbn/docker-gitlab/8.2.2/docker-compose.yml -O docker-compose.yml
docker-compose up -d
```

**Comment by ariault-blanchard** [comment]
I would like to ask a question on the upgrade process.

How can we upgrade our gitlab while using docker-compose.yml file ?

Actually i have three docker process (a process for each group in docker-compose i guess) : 

- gitlab_gitlab_1
- gitlab_postgresql_1
- gitlab_redis_1

How do i backup first ? Is it automatically if i just change 

'image: sameersbn/gitlab:8.2.2' to 'image: sameersbn/gitlab:8.2.3' in my docker-compose file ?

**Comment by sameersbn** [comment]
@ariault-blanchard there are two options.

OPTION 1:

Bring down all the containers, create the backup and delete all containers.

```bash
docker-compose stop
docker-compose run --rm gitlab app:rake gitlab:backup:create
docker-compose stop
docker-compose rm -fv
```

Update image version in docker-compose.yml and start again. You can also update versions of other images mentioned in `docker-compose.yml`

```bash
docker-compose up -d
```

OPTION 2:

Bring down only the gitlab container and create a backup

```bash
docker-compose stop gitlab
docker-compose rm -fv gitlab
docker-compose run --rm gitlab app:rake gitlab:backup:create
```

Update only gitlab image version in docker-compose.yml and start again

```bash
docker-compose up -d
```

**Comment by ariault-blanchard** [comment]
Ok. I'll try it then tell the result.

I think i'll do a custom script to do theses commands.

Thanks :)

**Comment by jessy1092** [comment]
@sameersbn 

I guess the problem is DB still create the table after I upgrade `8.0.4` to `8.2.2` failed. (This failed may the hardware issue, my machine has recorded the shutdown information.)
Let upgrade `8.1.4` to `8.2.2` process would find out the exist table.

Any idea about clean pgsql database and restore backup? I am not familiar with pg.

Could I restore the backup on new container without old data? ex. Start the new container on the new machine and just restore the gitlab backup tar.

Thank you for your help a lot.

**Comment by sameersbn** [comment]
you can try restoring an older backup and then try upgrading again.

**Comment by jshridha** [comment]
I'm having this same issue upgrading from 8.2.1 to anything above it. I restored last night's backup and I'm still having the issue

**Comment by jshridha** [comment]
After posting on the gitlab site, I found my problem. It wasn't at all docker-related. The issue was I had some migrations that were performed an some that weren't. I had to manually go though and apply migrations one by one until I came across one that was already applied. I then added this migration to the schema_migrations table so it would skip it on the next db:migrate run. Interestingly it was the lfs-related migrations that were somehow applied while the others weren't. I'm not sure how this happened but all seems to be up and running again!

**Comment by jessy1092** [comment]
Hi all,

Thanks for everyone's discussion. Finally, I resolve this problem. :)
Following is my solution. I drop my table and re-upgrade.

```console
root@ift-System-Product-Name:~/gitlab# docker ps
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS                                                                  NAMES
5d6da7749dd1        sameersbn/gitlab:8.1.4        "/sbin/entrypoint.sh "   9 hours ago         Up About a minute   0.0.0.0:10022->22/tcp, 0.0.0.0:10080->80/tcp, 0.0.0.0:10443->443/tcp   gitlab_gitlab_1
f8dfc74f8448        sameersbn/redis:latest        "/sbin/entrypoint.sh"    9 hours ago         Up 17 minutes       6379/tcp                                                               gitlab_redis_1
01f15016a564        sameersbn/postgresql:9.4-18   "/sbin/entrypoint.sh"    9 hours ago         Up 17 minutes       5432/tcp                                                               gitlab_postgresql_1

root@ift-System-Product-Name:~/gitlab# docker exec -it 5d6da7749dd1 bash

root@5d6da7749dd1:/home/git/gitlab# bundle exec rails dbconsole

Password: 

psql (9.4.5, server 9.4.6)

Type "help" for help.
gitlabhq_production=> DROP TABLE "lfs_objects";
DROP TABLE

gitlabhq_production=> DROP TABLE "lfs_objects_projects";
DROP TABLE

gitlabhq_production=> DROP TABLE "releases";
DROP TABLE

gitlabhq_production=> \q

root@5d6da7749dd1:/home/git/gitlab#
```

Then following @sameersbn [step](https://github.com/sameersbn/docker-gitlab/issues/529#issuecomment-163904715) and upgrade success.
