### ISSUE TITLE
[docker-compose] gitlab not start

### ISSUE THREAD

**Issue by oema** [sameersbn/docker-gitlab#556]
Hi,

I have try to start gitlab with docker compose and I have some trouble:

My docker compose : 
```
postgresql:
  image: sameersbn/postgresql:9.4-11
  environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
  volumes:
    - /home/romain/gitlab/postgresql:/var/lib/postgresql
gitlab:
  image: sameersbn/gitlab:8.3.0-1
  links:
    - redis:redisio
    - postgresql:postgresql
  ports:
    - "8081:80"
    - "8082:22"
  environment:
    - DEBUG=true
    - TZ=Europe/Paris
    - GITLAB_TIMEZONE=Paris

    - GITLAB_SECRETS_DB_KEY_BASE=HqBjPDJVNrcyOS4UJL0L

    - GITLAB_HOST=localhost
    - GITLAB_PORT=8081
    - GITLAB_SSH_PORT=8082
    - GITLAB_RELATIVE_URL_ROOT=

    - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
    - GITLAB_NOTIFY_PUSHER=false

    - GITLAB_EMAIL=notifications@example.com
    - GITLAB_EMAIL_REPLY_TO=noreply@example.com
    - GITLAB_INCOMING_EMAIL_ADDRESS=reply@example.com

    - GITLAB_BACKUP_SCHEDULE=daily
    - GITLAB_BACKUP_TIME=01:00

    - SMTP_ENABLED=false
    - SMTP_DOMAIN=www.example.com
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=mailer@example.com
    - SMTP_PASS=password
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=login

    - IMAP_ENABLED=false
    - IMAP_HOST=imap.gmail.com
    - IMAP_PORT=993
    - IMAP_USER=mailer@example.com
    - IMAP_PASS=password
    - IMAP_SSL=true
    - IMAP_STARTTLS=false
  volumes:
    - /home/romain/gitlab/gitlab:/home/git/data
redis:
  image: sameersbn/redis:latest
  volumes:
    - /home/romain/gitlab/redis:/var/lib/redis
```
And when I go see logs I have : 
```
postgresql_1 | ERROR:  column "help_page_text" of relation "application_settings" already exists
postgresql_1 | STATEMENT:  ALTER TABLE "application_settings" ADD "help_page_text" text
gitlab_1     | rake aborted!
gitlab_1     | StandardError: An error has occurred, this and all later migrations canceled:
gitlab_1     | 
gitlab_1     | PG::DuplicateColumn: ERROR:  column "help_page_text" of relation "application_settings" already exists
gitlab_1     | : ALTER TABLE "application_settings" ADD "help_page_text" text/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `block in execute'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:154:in `execute'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/schema_statements.rb:393:in `add_column'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql/schema_statements.rb:423:in `add_column'
gitlab_1     | /home/git/gitlab/config/initializers/postgresql_limit_fix.rb:15:in `add_column_with_limit_filter'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:662:in `block in method_missing'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:631:in `block in say_with_time'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:631:in `say_with_time'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:651:in `method_missing'
gitlab_1     | /home/git/gitlab/db/migrate/20150916114643_add_help_page_text_to_application_settings.rb:3:in `change'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:605:in `exec_migration'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:589:in `block (2 levels) in migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:588:in `block in migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:587:in `migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:765:in `migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:1041:in `block in ddl_transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:220:in `transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:1041:in `ddl_transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:956:in `block in migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:952:in `each'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:952:in `migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:820:in `up'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:798:in `migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
gitlab_1     | ActiveRecord::StatementInvalid: PG::DuplicateColumn: ERROR:  column "help_page_text" of relation "application_settings" already exists
gitlab_1     | : ALTER TABLE "application_settings" ADD "help_page_text" text
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `block in execute'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:154:in `execute'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/schema_statements.rb:393:in `add_column'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql/schema_statements.rb:423:in `add_column'
gitlab_1     | /home/git/gitlab/config/initializers/postgresql_limit_fix.rb:15:in `add_column_with_limit_filter'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:662:in `block in method_missing'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:631:in `block in say_with_time'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:631:in `say_with_time'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:651:in `method_missing'
gitlab_1     | /home/git/gitlab/db/migrate/20150916114643_add_help_page_text_to_application_settings.rb:3:in `change'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:605:in `exec_migration'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:589:in `block (2 levels) in migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:588:in `block in migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:587:in `migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:765:in `migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:1041:in `block in ddl_transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:220:in `transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:1041:in `ddl_transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:956:in `block in migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:952:in `each'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:952:in `migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:820:in `up'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:798:in `migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
gitlab_1     | PG::DuplicateColumn: ERROR:  column "help_page_text" of relation "application_settings" already exists
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `block in execute'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:154:in `execute'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/schema_statements.rb:393:in `add_column'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql/schema_statements.rb:423:in `add_column'
gitlab_1     | /home/git/gitlab/config/initializers/postgresql_limit_fix.rb:15:in `add_column_with_limit_filter'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:662:in `block in method_missing'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:631:in `block in say_with_time'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:631:in `say_with_time'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:651:in `method_missing'
gitlab_1     | /home/git/gitlab/db/migrate/20150916114643_add_help_page_text_to_application_settings.rb:3:in `change'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:605:in `exec_migration'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:589:in `block (2 levels) in migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:588:in `block in migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:587:in `migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:765:in `migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:1041:in `block in ddl_transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:220:in `transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:1041:in `ddl_transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:956:in `block in migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:952:in `each'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:952:in `migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:820:in `up'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:798:in `migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.4/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
gitlab_1     | Tasks: TOP => db:migrate
gitlab_1     | (See full trace by running task with --trace)
```
Have you got some issue ?

**Comment by gimler** [comment]
i have created a similar setup it works for me only difference.

Version:
* sameersbn/postgresql:9.4-12
* sameersbn/gitlab:8.4.2

`restart: always` to all containers

**HINT**: you can use `"$PWD/gitlab:/home/git/data"` instate of `/home/romain/gitlab/gitlab:/home/git/data`
`$PWD` is the current folder where you run the `docker-compose.yml` file

**Comment by sameersbn** [comment]
It could also be possible that your host may be running out of memory

**Comment by veggiemonk** [comment]
@oema I think you need to clean the postgresql data to restart fresh.
The first line says it all: 
>   ERROR:  column "help_page_text" of relation "application_settings" already exists

maybe try stopping the containers and delete the postgresql folder: 
```
docker-compose stop
rm -rf /home/romain/gitlab/postgresql
docker-compose up -d
docker-compose logs #check the logs after gitlab is started
```
