### ISSUE TITLE
Upgrade failed: You must enable the pg_trgm extension

### ISSUE THREAD

**Issue by ecrazor1911** [sameersbn/docker-gitlab#644]
# Postgre extension

```sh
root@****:/opt/gitlab# docker exec -it gitlab_postgresql_1 /bin/bash
root@postgresql:/# su postgres
postgres@postgresql:/$ psql -d template1 -c 'create extension pg_trgm;'
ERROR:  could not open extension control file "/usr/share/postgresql/9.4/extension/pg_trgm.control": No such file or directory
```

# Gitlab Log

```sh
gitlab_1     | Migrating database...
gitlab_1     | rake aborted!
gitlab_1     | StandardError: An error has occurred, all later migrations canceled:
gitlab_1     |
gitlab_1     | You must enable the pg_trgm extension. You can do so by running "CREATE EXTENSION pg_trgm;" as a PostgreSQL super user, this must be done for every GitLab database. For more information see http://www.postgresql.org/docs/current/static/sql-createextension.html/home/git/gitlab/db/migrate/20160226114608_add_trigram_indexes_for_searching.rb:8:in `up'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:611:in `exec_migration'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:591:in `block in migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:590:in `migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:768:in `migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:1046:in `ddl_transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:959:in `block in migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:955:in `each'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:955:in `migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:823:in `up'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:801:in `migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
gitlab_1     | You must enable the pg_trgm extension. You can do so by running "CREATE EXTENSION pg_trgm;" as a PostgreSQL super user, this must be done for every GitLab database. For more information see http://www.postgresql.org/docs/current/static/sql-createextension.html
gitlab_1     | /home/git/gitlab/db/migrate/20160226114608_add_trigram_indexes_for_searching.rb:8:in `up'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:611:in `exec_migration'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:591:in `block in migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:590:in `migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:768:in `migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:1046:in `ddl_transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:959:in `block in migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:955:in `each'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:955:in `migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:823:in `up'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/migration.rb:801:in `migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
gitlab_1     | /home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'

```

**Comment by ecrazor1911** [comment]
I'm sorry! I use bad version of postgresql (9.4).
