### ISSUE TITLE
Using the docker-compose.yml results in panic

### ISSUE THREAD

**Issue by cloudlady911** [sameersbn/docker-gitlab#702]
I customized it with my info and passwords, etc.  But when I do rancher-compose -p gitlab up, this is the result.

```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/docker/libcompose/project.parseInterpolationExpression(0xc2080a4dc0, 0x12, 0x12, 0xc20812c9e8, 0x0, 0x0, 0x10, 0x460be0)
	/source/Godeps/_workspace/src/github.com/docker/libcompose/project/interpolation.go:66 +0x197
github.com/docker/libcompose/project.parseLine(0xc2080a4dc0, 0x12, 0xc20812c9e8, 0x0, 0x0, 0x5aae01)
	/source/Godeps/_workspace/src/github.com/docker/libcompose/project/interpolation.go:91 +0xce
github.com/docker/libcompose/project.parseConfig(0xc2080c52c0, 0xa, 0xc2080c51d0, 0x8, 0xc20812c590, 0xc20812c9e8, 0x0, 0x0)
	/source/Godeps/_workspace/src/github.com/docker/libcompose/project/interpolation.go:111 +0x513
github.com/docker/libcompose/project.parseConfig(0xc2080c52c0, 0xa, 0xc2080c51d0, 0x8, 0xc20812c790, 0xc20812c9e8, 0x0, 0x0)
	/source/Godeps/_workspace/src/github.com/docker/libcompose/project/interpolation.go:128 +0x1ad
github.com/docker/libcompose/project.parseConfig(0xc2080c52c0, 0xa, 0xc2080c51d0, 0x8, 0xc20806ac60, 0xc20812c9e8, 0x0, 0x0)
	/source/Godeps/_workspace/src/github.com/docker/libcompose/project/interpolation.go:138 +0x3ba
github.com/docker/libcompose/project.Interpolate(0xa8de48, 0xc2080a4340, 0xc208056060, 0x0, 0x0)
	/source/Godeps/_workspace/src/github.com/docker/libcompose/project/interpolation.go:169 +0x1eb
github.com/docker/libcompose/project.mergeProject(0xc208060000, 0xc2080f8000, 0xf5e, 0x115e, 0xd4506, 0x0, 0x0)
	/source/Godeps/_workspace/src/github.com/docker/libcompose/project/merge.go:45 +0x199
github.com/docker/libcompose/project.(*Project).Load(0xc208060000, 0xc2080f8000, 0xf5e, 0x115e, 0x0, 0x0)
	/source/Godeps/_workspace/src/github.com/docker/libcompose/project/project.go:127 +0x90
github.com/docker/libcompose/project.(*Project).Parse(0xc208060000, 0x0, 0x0)
	/source/Godeps/_workspace/src/github.com/docker/libcompose/project/project.go:73 +0x14f
github.com/rancher/rancher-compose/rancher.NewProject(0xc20805c000, 0x65fdc0, 0x0, 0x0)
	/source/gopath/src/github.com/rancher/rancher-compose/rancher/project.go:16 +0xfa
github.com/rancher/rancher-compose/app.(*ProjectFactory).Create(0x9a6bd8, 0xc20811c0c0, 0x65be80, 0x0, 0x0)
	/source/gopath/src/github.com/rancher/rancher-compose/app/app.go:62 +0x957
github.com/docker/libcompose/cli/app.func·001(0xc20811c0c0)
	/source/Godeps/_workspace/src/github.com/docker/libcompose/cli/app/app.go:36 +0x57
github.com/codegangsta/cli.Command.Run(0x662dc0, 0x2, 0x0, 0x0, 0x69c490, 0x15, 0x0, 0x0, 0x0, 0x0, ...)
	/source/Godeps/_workspace/src/github.com/codegangsta/cli/command.go:113 +0x1038
github.com/codegangsta/cli.(*App).Run(0xc20803edd0, 0xc20800a000, 0x4, 0x4, 0x0, 0x0)
	/source/Godeps/_workspace/src/github.com/codegangsta/cli/app.go:156 +0xcf7
main.cliMain()
	/source/main.go:85 +0x1054
main.main()
	/source/main.go:27 +0x95

goroutine 5 [syscall]:
os/signal.loop()
	/usr/src/go/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/usr/src/go/src/os/signal/signal_unix.go:27 +0x35

goroutine 6 [runnable]:
github.com/rancher/go-machine-service/locks.locker()
	/source/Godeps/_workspace/src/github.com/rancher/go-machine-service/locks/locks.go:57
created by github.com/rancher/go-machine-service/locks.init·1
	/source/Godeps/_workspace/src/github.com/rancher/go-machine-service/locks/locks.go:7 +0x5c

goroutine 7 [runnable]:
github.com/docker/libcompose/cli/logger.generateColors()
	/source/Godeps/_workspace/src/github.com/docker/libcompose/cli/logger/colors.go:9
created by github.com/docker/libcompose/cli/logger.init·1
	/source/Godeps/_workspace/src/github.com/docker/libcompose/cli/logger/colors.go:33 +0x25

goroutine 8 [runnable]:
github.com/docker/libcompose/project.(*defaultListener).start(0xc2080a43c0)
	/source/Godeps/_workspace/src/github.com/docker/libcompose/project/listener.go:46
created by github.com/docker/libcompose/project.NewDefaultListener
	/source/Godeps/_workspace/src/github.com/docker/libcompose/project/listener.go:42 +0xa6
```

**Comment by SolidNerd** [comment]
If you using this [docker-compose.yml](https://github.com/sameersbn/docker-gitlab/blob/master/docker-compose.yml) with version: '2' key. It will currently not working, because so far as i know rancher-compose doesn't support docker-compose v2 yml's. Here is the related [Issue](https://github.com/rancher/rancher/issues/3973) that i found for it. 

But I could try to help you to convert the your current `docker-compose.yml` in the old format.

**Comment by cloudlady911** [comment]
Ah, thanks for that insight!  I converted it myself and I am up and running!

**Comment by cloudlady911** [comment]
I have this behind a load balancer so that my users can access the GUI over port 80.  How do I change the settings so that the signup emails don't have the 10080 port listed.

**Comment by SolidNerd** [comment]
Remove the `GITLAB_PORT ` env variable. So point defaults to `80` and if https is enabled to `443 ` .

**Comment by SolidNerd** [comment]
Okay for me it seems to fixed so in that case I will close this now.
