### ISSUE TITLE
Entrypoint not found

### ISSUE THREAD

**Issue by sklemmer** [sameersbn/docker-gitlab#733]
This error appears to happen in all newly pushed images
```
Status: Downloaded newer image for sameersbn/gitlab:latest-container-registry
Creating citool_gitlab_1

ERROR: for gitlab  Container command '/sbin/entrypoint.sh' not found or does not exist.
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 63, in main
AttributeError: 'ProjectError' object has no attribute 'msg'
```

**Comment by SolidNerd** [comment]
I can't reproduce it. Did you try to pull it manually with `docker pull sameersbn/gitlab:latest-container-registry` .

**Comment by sklemmer** [comment]
It seems i messed up my VM. When i tried with a new clean one it worked.
Sorry for my mistake
