### ISSUE TITLE
Version 8.8.5 fails to build

### ISSUE THREAD

**Issue by M0E-lnx** [sameersbn/docker-gitlab#739]
Just tried building your latest version (8.8.5) and it failed.  Looks like assets/build/install.sh is producing an error somewhere.

Here is the output from the command line

```
Bundle complete! 175 Gemfile dependencies, 269 gems now installed.
Gems in the groups development, test and aws were not installed.
Bundled gems are installed into ./vendor/bundle.
Post-install message from browser:

#################### WARNING ##############################
#                                                         #
#   Internet Explorer detection has changed on v1.0.0+.   #
#   If this is important for you, please read             #
#   https://github.com/fnando/browser#internet-explorer   #
#                                                         #
###########################################################

Post-install message from mousetrap-rails:

Remember to run generator to generate sample file and include mousetrap-rails with Rails Asset Pipeline

    $ rails generate mousetrap:install 

Post-install message from rdoc:
Depending on your version of ruby, you may need to install ruby rdoc/ri data:

<= 1.8.6 : unsupported
 = 1.8.7 : gem install rdoc-data; rdoc-data --install
 = 1.9.1 : gem install rdoc-data; rdoc-data --install
>= 1.9.2 : nothing to do! Yay!
Post-install message from httparty:
When you HTTParty, you must party hard!
Post-install message from haml:

HEADS UP! Haml 4.0 has many improvements, but also has changes that may break
your application:

* Support for Ruby 1.8.6 dropped
* Support for Rails 2 dropped
* Sass filter now always outputs <style> tags
* Data attributes are now hyphenated, not underscored
* html2haml utility moved to the html2haml gem
* Textile and Maruku filters moved to the haml-contrib gem

For more info see:

http://rubydoc.info/github/haml/haml/file/CHANGELOG.md

Post-install message from html-pipeline:
-------------------------------------------------
Thank you for installing html-pipeline!
You must bundle Filter gem dependencies.
See html-pipeline README.md for more details.
https://github.com/jch/html-pipeline#dependencies
-------------------------------------------------
Post-install message from acts-as-taggable-on:
When upgrading

Re-run the migrations generator

    rake acts_as_taggable_on_engine:install:migrations

This will create any new migrations and skip existing ones
Version 3.5.0 has a migration for mysql adapter
Compiling assets. Please be patient, this could take a while...
The command '/bin/sh -c bash ${GITLAB_BUILD_DIR}/install.sh' returned a non-zero code: 1

```

And a more verbose output prints this:

```
Post-install message from browser:

#################### WARNING ##############################
#                                                         #
#   Internet Explorer detection has changed on v1.0.0+.   #
#   If this is important for you, please read             #
#   https://github.com/fnando/browser#internet-explorer   #
#                                                         #
###########################################################

Post-install message from mousetrap-rails:

Remember to run generator to generate sample file and include mousetrap-rails with Rails Asset Pipeline

    $ rails generate mousetrap:install 

Post-install message from rdoc:
Depending on your version of ruby, you may need to install ruby rdoc/ri data:

<= 1.8.6 : unsupported
 = 1.8.7 : gem install rdoc-data; rdoc-data --install
 = 1.9.1 : gem install rdoc-data; rdoc-data --install
>= 1.9.2 : nothing to do! Yay!
Post-install message from httparty:
When you HTTParty, you must party hard!
Post-install message from haml:

HEADS UP! Haml 4.0 has many improvements, but also has changes that may break
your application:

* Support for Ruby 1.8.6 dropped
* Support for Rails 2 dropped
* Sass filter now always outputs <style> tags
* Data attributes are now hyphenated, not underscored
* html2haml utility moved to the html2haml gem
* Textile and Maruku filters moved to the haml-contrib gem

For more info see:

http://rubydoc.info/github/haml/haml/file/CHANGELOG.md

Post-install message from html-pipeline:
-------------------------------------------------
Thank you for installing html-pipeline!
You must bundle Filter gem dependencies.
See html-pipeline README.md for more details.
https://github.com/jch/html-pipeline#dependencies
-------------------------------------------------
Post-install message from acts-as-taggable-on:
When upgrading

Re-run the migrations generator

    rake acts_as_taggable_on_engine:install:migrations

This will create any new migrations and skip existing ones
Version 3.5.0 has a migration for mysql adapter
Compiling assets. Please be patient, this could take a while...
rake aborted!
Errno::EAFNOSUPPORT: Address family not supported by protocol - socket(2)
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.3.0/lib/redis/connection/ruby.rb:24:in `initialize'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.3.0/lib/redis/connection/ruby.rb:24:in `initialize'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.3.0/lib/redis/connection/ruby.rb:143:in `new'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.3.0/lib/redis/connection/ruby.rb:143:in `connect_addrinfo'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.3.0/lib/redis/connection/ruby.rb:187:in `block in connect'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.3.0/lib/redis/connection/ruby.rb:185:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.3.0/lib/redis/connection/ruby.rb:185:in `each_with_index'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.3.0/lib/redis/connection/ruby.rb:185:in `connect'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.3.0/lib/redis/connection/ruby.rb:260:in `connect'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.3.0/lib/redis/client.rb:336:in `establish_connection'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.3.0/lib/redis/client.rb:101:in `block in connect'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.3.0/lib/redis/client.rb:293:in `with_reconnect'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.3.0/lib/redis/client.rb:100:in `connect'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.3.0/lib/redis/client.rb:364:in `ensure_connected'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.3.0/lib/redis/client.rb:221:in `block in process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.3.0/lib/redis/client.rb:306:in `logging'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.3.0/lib/redis/client.rb:220:in `process'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.3.0/lib/redis/client.rb:120:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.3.0/lib/redis.rb:862:in `block in get'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.3.0/lib/redis.rb:58:in `block in synchronize'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.3.0/lib/redis.rb:58:in `synchronize'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.3.0/lib/redis.rb:861:in `get'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-store-1.1.7/lib/redis/store/interface.rb:5:in `get'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-store-1.1.7/lib/redis/store/marshalling.rb:17:in `get'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-store-1.1.7/lib/redis/store/namespace.rb:21:in `block in get'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-store-1.1.7/lib/redis/store/namespace.rb:74:in `namespace'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-store-1.1.7/lib/redis/store/namespace.rb:21:in `get'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-activesupport-4.1.5/lib/active_support/cache/redis_store.rb:230:in `block in read_entry'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-activesupport-4.1.5/lib/active_support/cache/redis_store.rb:212:in `call'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-activesupport-4.1.5/lib/active_support/cache/redis_store.rb:212:in `with'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-activesupport-4.1.5/lib/active_support/cache/redis_store.rb:230:in `read_entry'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/cache.rb:315:in `block in read'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/cache.rb:547:in `block in instrument'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/cache.rb:547:in `instrument'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/cache.rb:314:in `read'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/cache.rb:302:in `fetch'
/home/git/gitlab/app/models/application_setting.rb:106:in `cached'
/home/git/gitlab/lib/gitlab/current_settings.rb:12:in `ensure_application_settings!'
/home/git/gitlab/lib/gitlab/current_settings.rb:7:in `current_application_settings'
/home/git/gitlab/lib/gitlab/metrics.rb:11:in `settings'
/home/git/gitlab/lib/gitlab/metrics.rb:23:in `enabled?'
/home/git/gitlab/lib/gitlab/metrics.rb:129:in `<module:Metrics>'
/home/git/gitlab/lib/gitlab/metrics.rb:2:in `<module:Gitlab>'
/home/git/gitlab/lib/gitlab/metrics.rb:1:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:360:in `require_or_load'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:494:in `load_missing_constant'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:184:in `const_missing'
/home/git/gitlab/config/initializers/metrics.rb:1:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/engine.rb:652:in `block in load_config_initializer'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/engine.rb:651:in `load_config_initializer'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/engine.rb:615:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/engine.rb:615:in `block in <class:Engine>'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `instance_exec'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `tsort_each_child'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!'
/home/git/gitlab/config/environment.rb:5:in `<top (required)>'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/application.rb:328:in `require_environment!'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/sprockets-rails-3.0.4/lib/sprockets/rails/task.rb:62:in `block (2 levels) in define'
Tasks: TOP => environment
(See full trace by running task with --trace)
The command '/bin/sh -c bash ${GITLAB_BUILD_DIR}/install.sh' returned a non-zero code: 1


```

I'm building this as published with no modifications.  My docker version is 1.10.2
Any help on this would be great.

Thanks

**Comment by SolidNerd** [comment]
This seems to be a dns problem or a general internet problem on your side.

**Comment by M0E-lnx** [comment]
I'm connected to the internet... any idea where to start looking?

**Comment by SolidNerd** [comment]
I'm currently a little bit confused on my machine it's working like excepted. 
My docker version is **1.11.2**

**Comment by M0E-lnx** [comment]
I just upgraded my docker to 1.11.2 and I get the exact same error as before.

**Comment by SolidNerd** [comment]
You could try to run the building without a cache. `docker build --no-cache -t "imagename" .`

**Comment by SolidNerd** [comment]
Any updates on this @M0E-lnx  ?

**Comment by M0E-lnx** [comment]
@SolidNerd I get the exact same results builiding with ``docker build --no-cache``

**Comment by SolidNerd** [comment]
Could you try to ping rubygems.org with `docker run -it --rm busybox ping rubygems.org` .

**Comment by M0E-lnx** [comment]
Seems I cannot ping it.  It hangs for a while, then after I ``CTRL+C`` it prints

```
PING rubygems.org (54.186.104.15): 56 data bytes
^C
--- rubygems.org ping statistics ---
4 packets transmitted, 0 packets received, 100% packet loss

```

**Comment by SolidNerd** [comment]
And when you ping rubygems directly with `docker run -it --rm busybox ping 54.186.104.15` ?

**Comment by M0E-lnx** [comment]
Same result... hangs and I have to ``CTRL+C``.  100% packet loss

**Comment by SolidNerd** [comment]
Could you provide me more infos with `docker info` ?

**Comment by splattael** [comment]
BTW, I don't think that `rubygems.org` is pingable.

Fetching data however should work via e.g. `curl https://rubygems.org/api/v1/gems/activity`.

**Comment by M0E-lnx** [comment]
Here is my printout from ``docker info``

```
Containers: 10
 Running: 4
 Paused: 0
 Stopped: 6
Images: 156
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 145
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.18.20
Operating System: <unknown>
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.936 GiB
Name: vlocity.linux.vnet
ID: YAX2:2YKM:NSSF:E2LJ:5EGD:C4EY:2KJE:ZN3X:TEET:6O2I:NXND:7IAP
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Username: m0elnx
Registry: https://index.docker.io/v1/


```

**Comment by splattael** [comment]
Looking at the error output from above I see that you cannot connect to redis:

```
...
Compiling assets. Please be patient, this could take a while...
rake aborted!
Errno::EAFNOSUPPORT: Address family not supported by protocol - socket(2)
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.3.0/lib/redis/connection/ruby.rb:24:in `initialize'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.3.0/lib/redis/connection/ruby.rb:24:in `initialize'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.3.0/lib/redis/connection/ruby.rb:143:in `new'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.3.0/lib/redis/connection/ruby.rb:143:in `connect_addrinfo'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.3.0/lib/redis/connection/ruby.rb:187:in `block in connect'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.3.0/lib/redis/connection/ruby.rb:185:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.3.0/lib/redis/connection/ruby.rb:185:in `each_with_index'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.3.0/lib/redis/connection/ruby.rb:185:in `connect'
/home/git/gitlab/vendor/bundle/ruby/2.1.0/gems/redis-3.3.0/lib/redis/connection/ruby.rb:260:in `connect'
...
```

Mainly: `Errno::EAFNOSUPPORT: Address family not supported by protocol - socket(2)`

@SolidNerd I hope this helps for further investigations :-)

**Comment by M0E-lnx** [comment]
@splattael, does the docker build command expect me to have a running redis or is this something else?

**Comment by splattael** [comment]
@M0E-lnx I don't know. I just wanted to jump in helping decrypting the error message above so you don't search in the wrong direction :neckbeard: 

Possibly @SolidNerd might help you here :-)

**Comment by SolidNerd** [comment]
@splattael  Okay On my machine `docker run -it --rm busyboy rubygems.org` works and for the ip direct as well. 

@M0E-lnx  So far as I know you don't need any database running. Have a look at this line here will be the error produced. https://github.com/sameersbn/docker-gitlab/blob/master/assets/build/install.sh#L107
What is your command for building the container I'm still confused, because when i use `docker build -t "gitlab:testing" .` everything works as execepted. Could you post me your command ?

**Comment by M0E-lnx** [comment]
@SolidNerd 
Yes.  I spotted the line that raises the error and I just added a redirect there to have it log the output so I could post it here (initial post).

My build command is exactly like yours, except my tag is diff.

``docker build -t "gitlab:new" .`` is what I'm using.

That is at the root of the docker-gitlab directory where the ``Dockerfile`` exists.

**Comment by SolidNerd** [comment]
I don't know what could be the problem. Perhaps clone this repo and try to build again. 

Ping @sameersbn Do you have any clue for this here ?

**Comment by M0E-lnx** [comment]
I have tried a fresh clone of the repo... several times... that's what i'm working with

**Comment by M0E-lnx** [comment]
@SolidNerd and @sameersbn 

FWIW, if I edit the Dockerfile and change the gitlab version to 8.8.2 it builds fine... but anything newer than 8.8.2 gets me this error as described above.

**Comment by sameersbn** [comment]
@M0E-lnx I wonder if this has got something to go with the base image. Can you update the FROM line in the `Dockerfile` to `FROM sameersbn/ubuntu:14.04.20160504` and retry building?

**Comment by M0E-lnx** [comment]
@sameersbn I just tried that and got the exact same error.

**Comment by SolidNerd** [comment]
So in my opinion it's a problem with your docker daemon. You can try to restart docker daemon.

**Comment by M0E-lnx** [comment]
Restarted docker daemon... retried... same result
Stopped docker... rebooted box.....restarted docker ... retried ... same result.

:crying_cat_face:

**Comment by M0E-lnx** [comment]
Is there nothing else to try on this?  my docker works for everything else... why would this be the exception?

When I first read ``Errno::EAFNOSUPPORT: Address family not supported by protocol - socket(2)`` it made me think it's trying to connect to something.  But this is happening after all the gems are installed

**Comment by SolidNerd** [comment]
I don't know. You shoud have look at this [issue](https://gitlab.com/gitlab-org/omnibus-gitlab/issues/1329) in the upstream .

**Comment by M0E-lnx** [comment]
Thank you @SolidNerd and all who chimed in here.  It turns this is an upstream issue which should be getting resolved soon.

https://gitlab.com/gitlab-org/gitlab-ce/issues/17557#note_12724919

I patched the code with what they provided there and it fixed it for me.  I will now close this issue here.
