### ISSUE TITLE
Can't create project with 500 Error at 8.9.1

### ISSUE THREAD

**Issue by yknext** [sameersbn/docker-gitlab#766]
```
Started POST "/projects" for 127.0.0.1 at 2016-06-27 20:46:20 +0000
Processing by ProjectsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"[FILTERED]", "project"=>{"namespace_id"=>"1", "path"=>"my-test-project", "import_url"=>"[FILTERED]", "description"=>"my-test-project", "visibility_level"=>"0"}}
Unable to save project. Error: key must be 32 bytes or longer
Completed 500 Internal Server Error in 45ms (ActiveRecord: 0.7ms)

NoMethodError (undefined method `saved?' for nil:NilClass):
  app/controllers/projects_controller.rb:30:in `create'
  lib/gitlab/middleware/go.rb:16:in `call'
```

**Comment by SolidNerd** [comment]
This problem can occur if you `GITLAB_SECRETS_DB_KEY_BASE` is shorter than `32`. To fix this change your `GITLAB_SECRETS_DB_KEY_BASE` to a key that is longer than `32.` For example you could use `pwgen -Bsv1 64`

**Comment by SolidNerd** [comment]
But be careful you could lose data if you do that with an existing version of gitlab.

**Comment by yknext** [comment]
Thanks for help @SolidNerd
