### ISSUE TITLE
After restrict email domains, got 500 code, can't open home page

### ISSUE THREAD

**Issue by kanlidy** [sameersbn/docker-gitlab#814]
**docker-compose.yml file:**

    version: '2'

    services:
      redis:
        restart: always
        image: sameersbn/redis:latest
        command:
        - --loglevel warning
        volumes:
        - /srv/docker/gitlab/redis:/var/lib/redis:Z
        
      postgresql:
        restart: always
        image: sameersbn/postgresql:9.4-22
        volumes:
        - /srv/docker/gitlab/postgresql:/var/lib/postgresql:Z
        environment:
        - DB_USER=gitlab
        - DB_PASS=password
        - DB_NAME=gitlabhq_production
        - DB_EXTENSION=pg_trgm

      gitlab:
        restart: always
        image: sameersbn/gitlab:8.9.5
        depends_on:
        - redis
        - postgresql
        ports:
        - "12300:80"
        - "12299:22"
        volumes:
        - /srv/docker/gitlab/gitlab:/home/git/data:Z
        environment:
        - DEBUG=true

        - DB_ADAPTER=postgresql
        - DB_HOST=postgresql
        - DB_PORT=5432
        - DB_USER=gitlab
        - DB_PASS=password
        - DB_NAME=gitlabhq_production

        - REDIS_HOST=redis
        - REDIS_PORT=6379

        - TZ=Asia/Beijing
        - GITLAB_TIMEZONE=Beijing

        - GITLAB_HTTPS=false
        - SSL_SELF_SIGNED=false

        - GITLAB_HOST=public.oicp.net
        - GITLAB_PORT=12300
        - GITLAB_SSH_PORT=12299
        - GITLAB_RELATIVE_URL_ROOT=
        - GITLAB_SECRETS_DB_KEY_BASE=fdscpajDfdscsrO62cuJrS35213DuWr7

        - GITLAB_ROOT_PASSWORD=
        - GITLAB_ROOT_EMAIL=

        - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
        - GITLAB_NOTIFY_PUSHER=false

## enter the docker:

**gitlab-workhorse.log**

	root@260ebd0fc60a:/var/log/gitlab/gitlab# tail -f gitlab-workhorse.log
	publicamms.oicp.net:12300 @ - - [2016-07-28 02:17:29.734101786 +0000 UTC] "GET /assets/print-68eed6d8135d858318821e790e25da27b2b4b9b8dbb1993fa6765d8e2e3e16ee.css HTTP/1.1" 200 349 "http://publicamms.oicp.net:12300/fan/jeecg" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0" 0.000500
	2016/07/28 02:17:29 Send static file "/home/git/gitlab/public/assets/print-68eed6d8135d858318821e790e25da27b2b4b9b8dbb1993fa6765d8e2e3e16ee.css" ("gzip") for GET "/assets/print-68eed6d8135d858318821e790e25da27b2b4b9b8dbb1993fa6765d8e2e3e16ee.css"
	2016/07/28 02:18:41 ErrorPage: serving predefined error page: 500
	publicamms.oicp.net:12300 @ - - [2016-07-28 02:18:40.788313368 +0000 UTC] "GET / HTTP/1.1" 500 2205 "" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36" 0.216541
	publicamms.oicp.net:12300 @ - - [2016-07-28 02:18:41.211069314 +0000 UTC] "GET /favicon.ico HTTP/1.1" 200 5430 "http://publicamms.oicp.net:12300/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36" 0.000228
	2016/07/28 02:18:41 Send static file "/home/git/gitlab/public/favicon.ico" ("") for GET "/favicon.ico"
	2016/07/28 02:18:52 ErrorPage: serving predefined error page: 500
	publicamms.oicp.net:12300 @ - - [2016-07-28 02:18:51.843173883 +0000 UTC] "GET / HTTP/1.1" 500 2205 "" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36" 0.247128
	publicamms.oicp.net:12300 @ - - [2016-07-28 02:18:52.224693352 +0000 UTC] "GET /favicon.ico HTTP/1.1" 200 5430 "http://publicamms.oicp.net:12300/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36" 0.000335
	2016/07/28 02:18:52 Send static file "/home/git/gitlab/public/favicon.ico" ("") for GET "/favicon.ico"

**production.log**

	root@260ebd0fc60a:/var/log/gitlab/gitlab# tail -f production.log
	  app/views/shared/projects/_project.html.haml:10:in `_app_views_shared_projects__project_html_haml__3228925206238282988_32890160'
	  app/views/shared/projects/_list.html.haml:16:in `block in _app_views_shared_projects__list_html_haml___4488458288344446200_150534340'
	  app/views/shared/projects/_list.html.haml:14:in `_app_views_shared_projects__list_html_haml___4488458288344446200_150534340'
	  app/views/dashboard/projects/_projects.html.haml:1:in `_app_views_dashboard_projects__projects_html_haml__4062642519203199776_150485880'
	  app/views/dashboard/projects/index.html.haml:14:in `_app_views_dashboard_projects_index_html_haml___3789000844719634786_149614560'
	  app/controllers/dashboard/projects_controller.rb:15:in `index'
	  app/controllers/root_controller.rb:13:in `index'
	  lib/gitlab/middleware/go.rb:16:in `call'

	Started GET "/" for 59.172.136.109 at 2016-07-28 02:15:04 +0000
	Processing by RootController#index as HTML
	Read fragment views/namespaces/2-20160710112054232273000/projects/5-20160727132820727882000/root/index/application_settings/1-20160726125945544325000/v2.3/c5a8ab8a495d7588471f368562783c37 (0.3ms)
	Read fragment views/namespaces/1-20160718031734482226000/projects/16-20160727121603818875000/root/index/application_settings/1-20160726125945544325000/v2.3/c5a8ab8a495d7588471f368562783c37 (0.3ms)
	Completed 500 Internal Server Error in 94ms (ActiveRecord: 5.1ms)

	ActionView::Template::Error (no repository for such path):
	     7: - show_last_commit_as_description = false unless local_assigns[:show_last_commit_as_description] == true && project.commit
	     8: - css_class += " no-description" if project.description.blank? && !show_last_commit_as_description
	     9: - cache_key = [project.namespace, project, controller.controller_name, controller.action_name, current_application_settings, 'v2.3']
	    10: - cache_key.push(project.commit.status) if project.commit.try(:status)
	    11: 
	    12: %li.project-row{ class: css_class }
	    13:   = cache(cache_key) do
	  app/models/repository.rb:83:in `commit'
	  app/models/project.rb:414:in `commit'
	  app/views/shared/projects/_project.html.haml:10:in `_app_views_shared_projects__project_html_haml__3228925206238282988_32890160'
	  app/views/shared/projects/_list.html.haml:16:in `block in _app_views_shared_projects__list_html_haml___4488458288344446200_150534340'
	  app/views/shared/projects/_list.html.haml:14:in `_app_views_shared_projects__list_html_haml___4488458288344446200_150534340'
	  app/views/dashboard/projects/_projects.html.haml:1:in `_app_views_dashboard_projects__projects_html_haml__4062642519203199776_150485880'
	  app/views/dashboard/projects/index.html.haml:14:in `_app_views_dashboard_projects_index_html_haml___3789000844719634786_149614560'
	  app/controllers/dashboard/projects_controller.rb:15:in `index'
	  app/controllers/root_controller.rb:13:in `index'
	  lib/gitlab/middleware/go.rb:16:in `call'

**Comment by kanlidy** [comment]
everything is ok, after set restrict email domains. what's going on?

**Comment by kanlidy** [comment]
delete those projects which is import failure from github, all things settle.

**Comment by kanlidy** [comment]
After delete all projects which is import failure from github, the problem settled.
