### ISSUE TITLE
docker-compose fails with 'NoneType

### ISSUE THREAD

**Issue by rakesh-k** [sameersbn/docker-gitlab#863]

**Comment by rakesh-k** [comment]
trying the docker-compose with the compose file after editing for my environment. It spins up the redis, postgresql, and registry containers but then bails out with these errors:

```
compose.parallel.feed_queue: Pending: set([<Service: gitlab>, <Service: postgresql>, <Service: redis>, <Service: registry>])
compose.parallel.feed_queue: Starting producer thread for <Service: postgresql>
compose.service.start_container_if_stopped: Starting rakeshk_postgresql_1
compose.parallel.feed_queue: Starting producer thread for <Service: redis>
compose.cli.verbose_proxy.proxy_callable: docker attach <- (u'456eeaa2e6a54301583b9e8d0b99b74fbd2c248798d99a6acb8b2ff2e264652a', stderr=True, stream=True, stdout=True)
compose.service.start_container_if_stopped: Starting rakeshk_redis_1
compose.parallel.feed_queue: Starting producer thread for <Service: registry>
compose.service.start_container_if_stopped: Starting rakeshk_registry_1
compose.cli.verbose_proxy.proxy_callable: docker attach <- (u'7ce6397fa3dd617871b640780131db15dd9f5430306c416f2a2e93232cfe5337', stderr=True, stream=True, stdout=True)
compose.cli.verbose_proxy.proxy_callable: docker attach <- (u'b903630b2fd14c07d2e38a92425c3770e20a547863033a1abce80b13f859517d', stderr=True, stream=True, stdout=True)
compose.cli.verbose_proxy.proxy_callable: docker attach -> <generator object _multiplexed_response_stream_helper at 0x7fe1c7b70550>
compose.parallel.parallel_execute_iter: Failed: <Service: postgresql>
compose.parallel.feed_queue: Pending: set([<Service: gitlab>])
compose.parallel.feed_queue: <Service: gitlab> has upstream errors - not processing
compose.parallel.parallel_execute_iter: Failed: <Service: gitlab>
compose.parallel.feed_queue: Pending: set([])
compose.cli.verbose_proxy.proxy_callable: docker attach -> <generator object _multiplexed_response_stream_helper at 0x7fe1c7b45eb0>
compose.cli.verbose_proxy.proxy_callable: docker attach -> <generator object _multiplexed_response_stream_helper at 0x7fe1c7b70640>
compose.parallel.parallel_execute_iter: Failed: <Service: redis>
compose.parallel.feed_queue: Pending: set([])
compose.parallel.parallel_execute_iter: Failed: <Service: registry>
compose.parallel.feed_queue: Pending: set([])

ERROR: for redis  argument of type 'NoneType' is not iterable

ERROR: for postgresql  argument of type 'NoneType' is not iterable

ERROR: for registry  argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 61, in main
  File "compose/cli/main.py", line 113, in perform_command
  File "compose/cli/main.py", line 835, in up
  File "compose/project.py", line 400, in up
  File "compose/parallel.py", line 64, in parallel_execute
TypeError: argument of type 'NoneType' is not iterable
docker-compose returned -1

```

**Comment by SolidNerd** [comment]
Wich version of `docker-compose`do you use at the moment ?

**Comment by rakesh-k** [comment]
upgraded the server to 1.10 and now the error is gone.
