### ISSUE TITLE
Project Page 500 after upgrade to 8.11.2 292bf

### ISSUE THREAD

**Issue by datouxia** [sameersbn/docker-gitlab#879]
From Production Logs:

Completed 500 Internal Server Error in 69ms (ActiveRecord: 3.7ms)
OpenSSL::Cipher::CipherError (bad decrypt):
app/models/project.rb:489:in `import_url'
app/models/project.rb:525:in `external_import?'
app/models/project.rb:517:in `import?'
app/models/project.rb:533:in `import_in_progress?'
app/controllers/projects_controller.rb:94:in `show'
lib/gitlab/request_profiler/middleware.rb:15:in `call'
lib/gitlab/middleware/go.rb:16:in `call'

In this upgrade there are some mistake that I taken, I'm not sure it related or not.

At first I generated 64 byte characters & numbers for GITLAB_SECRETS_OTP_KEY_BASE、GITLAB_SECRETS_SECRET_KEY_BASE and GITLAB_SECRETS_DB_KEY_BASE.

Found 500 Erorr at project page.

Then I found that should setup GITLAB_SECRETS_OTP_KEY_BASE and GITLAB_SECRETS_SECRET_KEY_BASE from .secret  that already existed.

But still found 500 Erorr at project page.

Wait for your help, Thanks

**Comment by datouxia** [comment]
found this sql works
update `projects` set import_url = null WHERE import_url = ''
