### ISSUE TITLE
Gitlab + Registry random 500 and can't push

### ISSUE THREAD

**Issue by exreplay** [sameersbn/docker-gitlab#927]
I set up gitlab and everything is working fine, as expected. The second step was registry. So I first tried to just get a container working and it did. I was able to login and push. When i tried to connect the registry with gitlab i kept getting errors and can't push anymore.

I use "jwilder/nginx-proxy" and "jrcs/letsencrypt-nginx-proxy-companion" to also get lets encrypt working, which does fine without using registry.

First my docker-compose.yml:
```
version: '2'

services:
  redis:
    restart: always
    image: sameersbn/redis:latest
    command:
    - --loglevel warning
    volumes:
    - /srv/docker/gitlab/redis:/var/lib/redis:Z
    networks:
    - nginx-proxy

  postgresql:
    restart: always
    image: sameersbn/postgresql:9.5-1
    volumes:
    - /srv/docker/gitlab/postgresql:/var/lib/postgresql:Z
    environment:
    - DB_USER=user
    - DB_PASS=pass
    - DB_NAME=gitlabhq_production
    - DB_EXTENSION=pg_trgm
    networks:
    - nginx-proxy

  gitlab:
    restart: always
    image: sameersbn/gitlab:8.12.5
    depends_on:
    - redis
    - postgresql
    ports:
    - "10084:80"
    - "10024:22"
    volumes:
    - /srv/docker/gitlab/gitlab:/home/git/data:Z
    - .../certs:/certs
    environment:
    - VIRTUAL_HOST=git.example.com   
    - LETSENCRYPT_HOST=git.example.com  
    - LETSENCRYPT_EMAIL=git@example.com

    - DEBUG=false

    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=user
    - DB_PASS=pass
    - DB_NAME=gitlabhq_production

    - REDIS_HOST=redis
    - REDIS_PORT=6379

    - TZ=Europe/Berlin
    - GITLAB_TIMEZONE=Berlin

    - GITLAB_HTTPS=true
    - NGINX_X_FORWARDED_PROTO=https
    - SSL_SELF_SIGNED=false
    - SSL_CA_CERTIFICATES_PATH=/certs/git.example.com.crt
    - SSL_DHPARAM_PATH=/certs/git.example.com.pem

    - GITLAB_HOST=git.example.com
    - GITLAB_PORT=443
    - GITLAB_SSH_PORT=10024
    - GITLAB_RELATIVE_URL_ROOT=
    - GITLAB_SECRETS_DB_KEY_BASE=secret
    - GITLAB_SECRETS_SECRET_KEY_BASE=secret
    - GITLAB_SECRETS_OTP_KEY_BASE=secret

    - GITLAB_REGISTRY_ENABLED=true
    - GITLAB_REGISTRY_HOST=registry
    - GITLAB_REGISTRY_PORT=443
    - GITLAB_REGISTRY_API_URL=https://registry.example.com
    - GITLAB_REGISTRY_ISSUER=gitlab-issuer
    - GITLAB_REGISTRY_KEY_PATH=/certs/registry.example.com.key
    - SSL_REGISTRY_KEY_PATH=/certs/registry.example.com.key
    - SSL_REGISTRY_CERT_PATH=/certs/registry.example.com.crt
   ...
    networks:
    - nginx-proxy

  registry:
      restart: always
      image: registry:latest
      volumes:
      - /srv/docker/gitlab/gitlab/shared/registry:/registry
      - .../certs:/certs
      environment:
      - VIRTUAL_HOST=registry.example.com
      - LETSENCRYPT_HOST=registry.example.com
      - LETSENCRYPT_EMAIL=git@example.com

      - REGISTRY_LOG_LEVEL=info
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/registry
      - REGISTRY_AUTH_TOKEN_REALM=https://git.example.com/jwt/auth
      - REGISTRY_AUTH_TOKEN_SERVICE=container_registry
      - REGISTRY_AUTH_TOKEN_ISSUER=gitlab-issuer
      - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/certs/registry.example.com.crt
      - REGISTRY_STORAGE_DELETE_ENABLED=true
      networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
```

When i start my docker-compose.yml, i randomly get 500 in my gitlab installation. And it is always the same error. Also everytime i try to push an image into the registry it tells me "unauthorized: authentication required".

cat production.log
```
Completed 500 Internal Server Error in 1ms (ActiveRecord: 0.0ms)

Redis::CommandError (NOAUTH Authentication required.):
  lib/gitlab/request_profiler/middleware.rb:15:in `call'
  lib/gitlab/middleware/go.rb:16:in `call'
```

The weird thing is, everything works without the registry container.
I also tried expose ports "5000:5000" with the registry container but nothing changed.
What am i doing wrong?

**Comment by exreplay** [comment]
maybe duplicate of #775 . Do further testing.

**Comment by solidnerd** [comment]
@exreplay How did you resolve it ? A possible problem could `GITLAB_REGISTRY_API_URL=https://registry.example.com`this should be in your case `GITLAB_REGISTRY_API_URL=http://registry:5000`

**Comment by exreplay** [comment]
Thanks for the reply @solidnerd . I wasn't able to solve it by now. I still try to figure it out. 
You are right. I give it a shot right now and let you know if it works.

**Comment by solidnerd** [comment]
If you have more questions ping me. I hope I will recognize it 😂

**Comment by exreplay** [comment]
Sure, i'll do. Thanks a lot 👍

**Comment by exreplay** [comment]
I changed the `GITLAB_REGISTRY_API_URL` like you said, changed a few settings and now the error is something different.

```
ActionView::Template::Error (NOAUTH Authentication required.):
     7: - show_last_commit_as_description = false unless local_assigns[:show_last_commit_as_description] == true && project.commit
     8: - css_class += " no-description" if project.description.blank? && !show_last_commit_as_description
     9: - cache_key = [project.namespace, project, controller.controller_name, controller.action_name, current_application_settings, 'v2.3']
    10: - cache_key.push(project.commit.status) if project.commit.try(:status)
    11: 
    12: %li.project-row{ class: css_class }
    13:   = cache(cache_key) do
  lib/repository_cache.rb:20:in `fetch'
  app/models/repository.rb:39:in `exists?'
  app/models/repository.rb:72:in `commit'
  app/models/project.rb:442:in `commit'
  app/views/shared/projects/_project.html.haml:10:in `_app_views_shared_projects__project_html_haml__2734649610522125368_110776380'
  app/views/shared/projects/_list.html.haml:16:in `block in _app_views_shared_projects__list_html_haml__1058425630759857442_115423820'
  app/views/shared/projects/_list.html.haml:14:in `_app_views_shared_projects__list_html_haml__1058425630759857442_115423820'
  app/views/dashboard/projects/_projects.html.haml:1:in `_app_views_dashboard_projects__projects_html_haml__1407718910206001139_115659720'
  app/views/dashboard/projects/index.html.haml:15:in `_app_views_dashboard_projects_index_html_haml___2050299611344653284_54745500'
  app/controllers/dashboard/projects_controller.rb:15:in `index'
  app/controllers/root_controller.rb:13:in `index'
  lib/gitlab/request_profiler/middleware.rb:15:in `call'
  lib/gitlab/middleware/go.rb:16:in `call'
```

It still says NOAUTH but it is not related to Redis.

**Comment by exreplay** [comment]
I feel like it has something to do with my certificates because (when i'm right) gitlab and registry authenticate by the certificate from `REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE`. I also created a self signed certificate, like described, but nothing changed. Could it be that there is a problem with letsencrypt?
