### ISSUE TITLE
unicorn issue after upgrade

### ISSUE THREAD

**Issue by djskinner-sky** [sameersbn/docker-gitlab#957]
The container will no longer start with the following output continually repeating:

```
11/7/2016 12:26:11 AM2016-11-07 00:26:11,518 INFO success: sidekiq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
11/7/2016 12:26:11 AM2016-11-07 00:26:11,518 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
11/7/2016 12:26:11 AM2016-11-07 00:26:11,518 INFO success: gitlab-workhorse entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
11/7/2016 12:26:11 AM2016-11-07 00:26:11,518 INFO success: cron entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
11/7/2016 12:26:11 AM2016-11-07 00:26:11,518 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
11/7/2016 12:26:11 AM2016-11-07 00:26:11,518 INFO success: sshd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
11/7/2016 12:26:22 AM2016-11-07 00:26:22,257 INFO exited: unicorn (exit status 1; not expected)
11/7/2016 12:26:22 AM2016-11-07 00:26:22,312 INFO spawned: 'unicorn' with pid 519
11/7/2016 12:26:22 AM2016-11-07 00:26:22,314 INFO exited: sidekiq (exit status 1; not expected)
11/7/2016 12:26:23 AM2016-11-07 00:26:23,148 INFO spawned: 'sidekiq' with pid 522
11/7/2016 12:26:24 AM2016-11-07 00:26:24,150 INFO success: sidekiq entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
11/7/2016 12:26:24 AM2016-11-07 00:26:24,151 INFO success: unicorn entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
11/7/2016 12:26:32 AM2016-11-07 00:26:32,131 INFO exited: unicorn (exit status 1; not expected)
11/7/2016 12:26:32 AM2016-11-07 00:26:32,975 INFO spawned: 'unicorn' with pid 529
11/7/2016 12:26:33 AM2016-11-07 00:26:33,317 INFO exited: sidekiq (exit status 1; not expected)
11/7/2016 12:26:33 AM2016-11-07 00:26:33,841 INFO spawned: 'sidekiq' with pid 532
```

It's on a 4GB VM with plenty of memory available. I've had this stack working for a long time on this VM too. `docker stats` shows the memory rising to about `450MB/3.85GB` before dropping right back down and rising to 450 again.

Not sure if it's relevant but I initially gave `GITLAB_SECRETS_SECRET_KEY_BASE` and `GITLAB_SECRETS_OTP_KEY_BASE ` different values to the contents of `/home/git/data/.secret` before I saw the docs.

`cat /var/log/gitlab/gitlab/unicorn.stderr.log` shows:

```
I, [2016-11-07T01:03:36.684028 #602]  INFO -- : Refreshing Gem list
/usr/lib/ruby/2.3.0/psych.rb:377:in `parse': (<unknown>): could not find expected ':' while scanning a simple key at line 8 column 1 (Psych::SyntaxError)
	from /usr/lib/ruby/2.3.0/psych.rb:377:in `parse_stream'
	from /usr/lib/ruby/2.3.0/psych.rb:325:in `parse'
	from /usr/lib/ruby/2.3.0/psych.rb:252:in `load'
	from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/application.rb:391:in `secrets'
	from /home/git/gitlab/config/initializers/secret_token.rb:50:in `block in set_missing_keys'
```

So looks like I might have messed up the secrets stuff. Any ideas how to fix it?

**Comment by djskinner-sky** [comment]
I've made a bit more progress by going back to the original key I entered, which was the same value as what I'd used for `GITLAB_SECRETS_DB_KEY_BASE`. Now there is no unicorn loop and it appears to start but upon loading the page I am redirected to `/users/sign_in` and presented with a 500 error

**Comment by djskinner-sky** [comment]
From `/var/log/gitlab/gitlab/unicorn.stderr.log`:

```
** [Raven] Raven 2.0.2 configured not to capture errors.
** [Raven] Raven 2.0.2 configured not to capture errors.
Started GET "/users/sign_in" for XX.XX.XX.XX at 2016-11-07 07:55:05 +0000
Processing by SessionsController#new as HTML
Completed 500 Internal Server Error in 445ms (ActiveRecord: 28.6ms)

ActionView::Template::Error (undefined method `description_html' for #<Appearanc
e:0x0000000adfcd70>):
```

and also

```
Started POST "/api/v3/internal/allowed" for 127.0.0.1 at 2016-11-07 07:57:45 +00
00

ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column namespaces.d
eleted_at does not exist
LINE 1: ..."namespaces"."id" = "projects"."namespace_id" AND "namespace...
                                                             ^
: SELECT  "projects".* FROM "projects" INNER JOIN "namespaces" ON "namespaces"."
id" = "projects"."namespace_id" AND "namespaces"."deleted_at" IS NULL WHERE "pro
jects"."pending_delete" = $1 AND ((
            (namespaces.path = 'atomx'
          AND projects.path = 'conversr')
            OR (
              LOWER(namespaces.path) = LOWER('atomx')
              AND LOWER(projects.path) = LOWER('conversr')
            )
          ))  ORDER BY (CASE WHEN  namespaces.path = 'atomx' AND  projects.path
= 'conversr' THEN 0 ELSE 1 END) LIMIT 1):
  /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active
_record/connection_adapters/postgresql_adapter.rb:637:in `prepare'
```

**Comment by djskinner-sky** [comment]
How do I force the database migration scripts to run again?

**Comment by djskinner-sky** [comment]
Finally got it working and there is no issues. It came down to silly mistakes on my part.
