### ISSUE TITLE
backup failing

### ISSUE THREAD

**Issue by r2evans** [sameersbn/docker-gitlab#978]
I'm not certain if this is unique to your image or if it should go upstream to gitlab.

The backups are creating partial tar files that are incomplete backups. When I ran the backup manually:

```bash
root@07bb1f714235:/home/git/gitlab# sudo -u git bundle exec rake gitlab:backup:create SKIP= RAILS_ENV=production
Dumping database ...
Dumping PostgreSQL database gitlabhq_production ... [DONE]
done
Dumping repositories ...
 * bill.evans/adsRaceRS ... rake aborted!
Rugged::ConfigError: Error stat'ing config file '/root/.gitconfig'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/gitlab_git-10.7.0/lib/gitlab_git/repository.rb:49:in `new'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/gitlab_git-10.7.0/lib/gitlab_git/repository.rb:49:in `rugged'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/gitlab_git-10.7.0/lib/gitlab_git/repository.rb:90:in `local_branches'
/home/git/gitlab/app/models/repository.rb:759:in `local_branches'
/home/git/gitlab/app/models/repository.rb:278:in `block in branch_count'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/cache.rb:299:in `block in fetch'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/cache.rb:585:in `block in save_block_result_to_cache'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/cache.rb:547:in `block in instrument'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/cache.rb:547:in `instrument'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/cache.rb:584:in `save_block_result_to_cache'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/cache.rb:299:in `fetch'
/home/git/gitlab/lib/repository_cache.rb:20:in `fetch'
/home/git/gitlab/app/models/repository.rb:278:in `branch_count'
/home/git/gitlab/app/models/repository.rb:67:in `block in has_visible_content?'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/cache.rb:299:in `block in fetch'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/cache.rb:585:in `block in save_block_result_to_cache'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/cache.rb:547:in `block in instrument'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/cache.rb:547:in `instrument'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/cache.rb:584:in `save_block_result_to_cache'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/cache.rb:299:in `fetch'
/home/git/gitlab/lib/repository_cache.rb:20:in `fetch'
/home/git/gitlab/app/models/repository.rb:66:in `has_visible_content?'
/home/git/gitlab/app/models/project.rb:882:in `empty_repo?'
/home/git/gitlab/lib/backup/repository.rb:14:in `block in dump'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/batches.rb:51:in `block (2 levels) in find_each'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/batches.rb:51:in `each'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/batches.rb:51:in `block in find_each'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/batches.rb:124:in `find_in_batches'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/relation/batches.rb:50:in `find_each'
/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/querying.rb:9:in `find_each'
/home/git/gitlab/lib/backup/repository.rb:8:in `dump'
/home/git/gitlab/lib/tasks/gitlab/backup.rake:72:in `block (4 levels) in <top (required)>'
/home/git/gitlab/lib/tasks/gitlab/backup.rake:12:in `block (3 levels) in <top (required)>'
Tasks: TOP => gitlab:backup:repo:create
(See full trace by running task with --trace)
```

I would have assumed that it would be using `/home/git/.gitconfig` instead of `/root/.gitconfig`. So I copied the first over to the second and had to (temporarily) change the perms on `/root` to allow traversal. The backup worked at that point. Perhaps there's something under the hood that's using root's homedir?

**Comment by solidnerd** [comment]
Hey,

it seems that your backup command isn't correct. Because you try to make a backup as the root user. I indicated it because he looks on a different home as the diffened user. I would recommend to set the `-H` option from sudo and `-e` aswell. For more information about sudo have a look at https://linux.die.net/man/8/sudo

So the correct command would be:

```
sudo -HEu git bundle exec rake gitlab:backup:create SKIP= RAILS_ENV=production
```

If you use docker-compose I would recommend to use this 2 docker-compose commands to make your backup. #987

**Comment by r2evans** [comment]
Either I misunderstand or I didn't explain my position. I showed the command being run manually merely to provide the error. Normally the command is executed internally by setting `GITLAB_BACKUP_SCHEDULE=daily` in the `docker-compose.yml` file. This setting causes the following cron schedule to be set:

```bash
root@8609a78a95e2:/home/git/gitlab# crontab -u git -l
00 01 * * * /bin/bash -l -c 'cd /home/git/gitlab && bundle exec rake gitlab:backup:create SKIP= RAILS_ENV=production'
```

I verified it, and `cron` is correctly setting the following variables by default:

```
HOME='/home/git'
IFS='
'
LANG='C.UTF-8'
LC_MESSAGES='POSIX'
LOGNAME='git'
OPTIND='1'
PATH='/usr/bin:/bin'
PPID='5060'
PS1='$ '
PS2='> '
PS4='+ '
PWD='/home/git'
SHELL='/bin/sh'
```

So, whatever was causing the truncated tarfile was both (a) internal to the automated backups the scripts provide, and (b) not a function of my use of `sudo -u git` or `sudo -HEu git`. (BTW: using `-E` seems unnecessary if `HOME` is the only envvar needed. Just a thought.) I tried an image restart (`stop`, `rm`, `run`) a few times and it continued to fail. With the world-readable (empty) `/root/.gitconfig` file, it consistently worked with restarts (given that I re-opened that file). So, it appears that the problem is with the backup process itself, looking for that file.

Do you not get the error in your instance?

*\*pause\**

Okay, it looks like it may have been either an upstream issue (that was silently fixed), as it does not appear to be afflicting my 8.14.0 instance. I'll keep an eye on it the next day or so (after a restart or two) to make sure it is in fact gone, reopening only if I find out more. Thanks for the reply.
