### ISSUE TITLE
Gmail SMTP login problem

### ISSUE THREAD

**Issue by iamchanghyunpark** [sameersbn/docker-gitlab#993]
I tried setting my SMTP to gmail, and I had issues signing in.
I tried `allow less secure apps to access your account` and `Display unlock Captcha` however both failed me.
In the end I enabled 2-Factor Authentication and used the `application password`.
Now the `mail_room` does not die and restart every second.

The mail_room error I was getting was as follows:
```
/usr/lib/ruby/2.3.0/net/imap.rb:1196:in `get_tagged_response':  Please log in via your web browser: https://support.google.com/mail/accounts/answer/78754 (Failure) (Net::IMAP::NoResponseError)
        from /usr/lib/ruby/2.3.0/net/imap.rb:1250:in `block in send_command'
        from /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
        from /usr/lib/ruby/2.3.0/net/imap.rb:1232:in `send_command'
        from /usr/lib/ruby/2.3.0/net/imap.rb:436:in `login'
        from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/mail_room-0.9.0/lib/mail_room/connection.rb:84:in `log_in'
        from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/mail_room-0.9.0/lib/mail_room/connection.rb:68:in `setup'
        from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/mail_room-0.9.0/lib/mail_room/connection.rb:8:in `initialize'
        from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/mail_room-0.9.0/lib/mail_room/mailbox_watcher.rb:57:in `new'
        from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/mail_room-0.9.0/lib/mail_room/mailbox_watcher.rb:57:in `connection'
        from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/mail_room-0.9.0/lib/mail_room/mailbox_watcher.rb:28:in `run'
        from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/mail_room-0.9.0/lib/mail_room/coordinator.rb:19:in `each'
        from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/mail_room-0.9.0/lib/mail_room/coordinator.rb:19:in `run'
        from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/mail_room-0.9.0/lib/mail_room/cli.rb:52:in `start'
        from /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/mail_room-0.9.0/bin/mail_room:5:in `<top (required)>'
        from /home/git/gitlab/vendor/bundle/ruby/2.3.0/bin/mail_room:23:in `load'
        from /home/git/gitlab/vendor/bundle/ruby/2.3.0/bin/mail_room:23:in `<main>'
```

If anyone else had the same issue, I think it may be helpful to add the necessity of a 2FA to the gmail account in the README.md file.

**Comment by hhue13** [comment]
Thanks a lot @iamchanghyunpark for the hint! 

What's probably  worth mentioning is that the account need to be enabled for iMAP as well on Google at least (may on other mail providers as well). This [link](http://hawaii.edu/askus/1147)  - provides the required steps.
