### ISSUE TITLE
Gitlab Migration failed

### ISSUE THREAD

**Issue by Kaleesastha** [sameersbn/docker-gitlab#997]
While migrating from 8.13.6 to 8.14.0 facing gitlab migration failed and the detailed logs are given below  for your reference ,

est: sha256:d378dff3464c34b4f0f57704d900affcb0546e5a23ca289bf134d145e6890c2c
Status: Downloaded newer image for docker.io/sameersbn/gitlab:8.14.1
9ffe5d3744281667e9ed506997e0bd783ad36023597203386faffee899cfea49
2016-12-03T00:57:05.383375000+05:30 Mapping UID and GID for git:git to 1001:1001
2016-12-03T00:57:06.200390000+05:30 Initializing logdir...
2016-12-03T00:57:06.262307000+05:30 Initializing datadir...
2016-12-03T00:57:06.343253000+05:30 Updating CA certificates...
2016-12-03T00:57:09.593180000+05:30 Installing configuration templates...
2016-12-03T00:57:09.640053000+05:30 Configuring gitlab...
2016-12-03T00:57:09.720121000+05:30 Configuring gitlab::database
2016-12-03T00:57:09.751786000+05:30 Configuring gitlab::redis
2016-12-03T00:57:09.772531000+05:30 Configuring gitlab::secrets...
2016-12-03T00:57:09.792448000+05:30 Configuring gitlab::sidekiq...
2016-12-03T00:57:09.809977000+05:30 Configuring gitlab::gitlab-workhorse...
2016-12-03T00:57:09.836509000+05:30 Configuring gitlab::unicorn...
2016-12-03T00:57:09.863520000+05:30 Configuring gitlab::timezone...
2016-12-03T00:57:09.880781000+05:30 Configuring gitlab::rack_attack...
2016-12-03T00:57:09.910778000+05:30 Configuring gitlab::ci...
2016-12-03T00:57:09.933645000+05:30 Configuring gitlab::artifacts...
2016-12-03T00:57:09.953392000+05:30 Configuring gitlab::lfs...
2016-12-03T00:57:09.985995000+05:30 Configuring gitlab::project_features...
2016-12-03T00:57:10.021618000+05:30 Configuring gitlab::smtp_settings...
2016-12-03T00:57:10.171893000+05:30 Configuring gitlab::oauth...
2016-12-03T00:57:10.322159000+05:30 Configuring gitlab::ldap...
2016-12-03T00:57:10.424725000+05:30 Configuring gitlab::backups...
2016-12-03T00:57:10.459843000+05:30 Configuring gitlab::registry...
2016-12-03T00:57:10.492229000+05:30 Configuring gitlab-shell...
2016-12-03T00:57:10.519456000+05:30 Configuring nginx...
2016-12-03T00:57:10.521912000+05:30 Configuring nginx::gitlab...
2016-12-03T00:57:10.548344000+05:30 Configuring nginx::gitlab::ssl...
2016-12-03T00:57:10.573661000+05:30 Configuring nginx::gitlab::hsts...
2016-12-03T00:57:10.588824000+05:30 Configuring nginx::gitlab-registry...
2016-12-03T00:57:10.632224000+05:30 Migrating database...
2016-12-03T00:57:18.458865000+05:30 rake aborted!
2016-12-03T00:57:18.459452000+05:30 StandardError: An error has occurred, all later migrations canceled:
2016-12-03T00:57:18.460086000+05:30 Mysql2::Error: Lost connection to MySQL server during query: ALTER TABLE `users` ADD `authorized_projects_populated` tinyint(1)/home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `query'
2016-12-03T00:57:18.460381000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `block in execute'
2016-12-03T00:57:18.460658000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
2016-12-03T00:57:18.460970000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
2016-12-03T00:57:18.461263000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
2016-12-03T00:57:18.461531000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `execute'
2016-12-03T00:57:18.461832000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/mysql2_adapter.rb:231:in `execute'
2016-12-03T00:57:18.462122000+05:30 /home/git/gitlab/config/initializers/connection_fix.rb:20:in `execute'
2016-12-03T00:57:18.462411000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:407:in `add_column'
2016-12-03T00:57:18.462684000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:665:in `block in method_missing'
2016-12-03T00:57:18.462959000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:634:in `block in say_with_time'
2016-12-03T00:57:18.463236000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:634:in `say_with_time'
2016-12-03T00:57:18.463500000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:654:in `method_missing'
2016-12-03T00:57:18.463761000+05:30 /home/git/gitlab/db/migrate/20161017091941_add_authorized_projects_populated_to_users.rb:7:in `change'
2016-12-03T00:57:18.464045000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:608:in `exec_migration'
2016-12-03T00:57:18.464320000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
2016-12-03T00:57:18.464589000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:591:in `block in migrate'
2016-12-03T00:57:18.464855000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
2016-12-03T00:57:18.465143000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:590:in `migrate'
2016-12-03T00:57:18.465402000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:768:in `migrate'
2016-12-03T00:57:18.465668000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
2016-12-03T00:57:18.465948000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:1046:in `ddl_transaction'
2016-12-03T00:57:18.466217000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
2016-12-03T00:57:18.466488000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:959:in `block in migrate'
2016-12-03T00:57:18.466791000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:955:in `each'
2016-12-03T00:57:18.467070000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:955:in `migrate'
2016-12-03T00:57:18.467343000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:823:in `up'
2016-12-03T00:57:18.467619000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:801:in `migrate'
2016-12-03T00:57:18.467877000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
2016-12-03T00:57:18.468159000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
2016-12-03T00:57:18.468439000+05:30 ActiveRecord::StatementInvalid: Mysql2::Error: Lost connection to MySQL server during query: ALTER TABLE `users` ADD `authorized_projects_populated` tinyint(1)
2016-12-03T00:57:18.468741000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `query'
2016-12-03T00:57:18.469037000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `block in execute'
2016-12-03T00:57:18.469330000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
2016-12-03T00:57:18.469597000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
2016-12-03T00:57:18.469865000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
2016-12-03T00:57:18.470143000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `execute'
2016-12-03T00:57:18.470411000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/mysql2_adapter.rb:231:in `execute'
2016-12-03T00:57:18.470668000+05:30 /home/git/gitlab/config/initializers/connection_fix.rb:20:in `execute'
2016-12-03T00:57:18.470950000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:407:in `add_column'
2016-12-03T00:57:18.471253000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:665:in `block in method_missing'
2016-12-03T00:57:18.471526000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:634:in `block in say_with_time'
2016-12-03T00:57:18.471778000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:634:in `say_with_time'
2016-12-03T00:57:18.472055000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:654:in `method_missing'
2016-12-03T00:57:18.472311000+05:30 /home/git/gitlab/db/migrate/20161017091941_add_authorized_projects_populated_to_users.rb:7:in `change'
2016-12-03T00:57:18.472582000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:608:in `exec_migration'
2016-12-03T00:57:18.472836000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
2016-12-03T00:57:18.473110000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:591:in `block in migrate'
2016-12-03T00:57:18.473377000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
2016-12-03T00:57:18.473643000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:590:in `migrate'
2016-12-03T00:57:18.473907000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:768:in `migrate'
2016-12-03T00:57:18.474188000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
2016-12-03T00:57:18.474442000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:1046:in `ddl_transaction'
2016-12-03T00:57:18.474706000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
2016-12-03T00:57:18.474980000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:959:in `block in migrate'
2016-12-03T00:57:18.475239000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:955:in `each'
2016-12-03T00:57:18.475495000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:955:in `migrate'
2016-12-03T00:57:18.475759000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:823:in `up'
2016-12-03T00:57:18.476027000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:801:in `migrate'
2016-12-03T00:57:18.476286000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
2016-12-03T00:57:18.476536000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
2016-12-03T00:57:18.476790000+05:30 Mysql2::Error: Lost connection to MySQL server during query
2016-12-03T00:57:18.477055000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `query'
2016-12-03T00:57:18.477313000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `block in execute'
2016-12-03T00:57:18.477559000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'
2016-12-03T00:57:18.477815000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
2016-12-03T00:57:18.478073000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'
2016-12-03T00:57:18.478321000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:309:in `execute'
2016-12-03T00:57:18.478567000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/mysql2_adapter.rb:231:in `execute'
2016-12-03T00:57:18.478809000+05:30 /home/git/gitlab/config/initializers/connection_fix.rb:20:in `execute'
2016-12-03T00:57:18.479087000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:407:in `add_column'
2016-12-03T00:57:18.479324000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:665:in `block in method_missing'
2016-12-03T00:57:18.479558000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:634:in `block in say_with_time'
2016-12-03T00:57:18.479792000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:634:in `say_with_time'
2016-12-03T00:57:18.480039000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:654:in `method_missing'
2016-12-03T00:57:18.480277000+05:30 /home/git/gitlab/db/migrate/20161017091941_add_authorized_projects_populated_to_users.rb:7:in `change'
2016-12-03T00:57:18.480511000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:608:in `exec_migration'
2016-12-03T00:57:18.480752000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:592:in `block (2 levels) in migrate'
2016-12-03T00:57:18.481012000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:591:in `block in migrate'
2016-12-03T00:57:18.481245000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
2016-12-03T00:57:18.481471000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:590:in `migrate'
2016-12-03T00:57:18.481705000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:768:in `migrate'
2016-12-03T00:57:18.481951000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:998:in `block in execute_migration_in_transaction'
2016-12-03T00:57:18.482187000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:1046:in `ddl_transaction'
2016-12-03T00:57:18.482428000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:997:in `execute_migration_in_transaction'
2016-12-03T00:57:18.482674000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:959:in `block in migrate'
2016-12-03T00:57:18.482912000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:955:in `each'
2016-12-03T00:57:18.483161000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:955:in `migrate'
2016-12-03T00:57:18.483384000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:823:in `up'
2016-12-03T00:57:18.483622000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/migration.rb:801:in `migrate'
2016-12-03T00:57:18.483860000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
2016-12-03T00:57:18.484108000+05:30 /home/git/gitlab/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
2016-12-03T00:57:18.484346000+05:30 Tasks: TOP => db:migrate
2016-12-03T00:57:18.484588000+05:30 (See full trace by running task with --trace)

Kindly check and let me know the solution to proceed further .

**Comment by solidnerd** [comment]
Hey,

this seems to be an issue with your mysql database. I don't recommend to use mysql with Gitlab because in the upstream I won't be supported as well. For some more informations look at #983 .
